README.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkControllerConfig.java
helm/flink-operator/templates/flink-operator.yaml
helm/flink-operator/templates/webhook.yaml
helm/flink-operator/values.yaml

This PR introduces a new config option for watching a list of specific namespaces for FlinkDeployment resources.
The config can be set in the Helm chart as a list and is passed as an env variable to the operator.
It also includes a change to the webhook configuration name to include the operator namespace. This allows us to have multiple webhook configs in the same cluster pointing to different operators (which is necessary if all of them are watching their own namespace)

[FLINK-26260] Support watching specific namespaces only

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/DefaultConfig.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkControllerConfig.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorMetricUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EnvUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkOperatorWebhook.java

Move the scattered environments variables to the `EnvUtils` and make it clear whether the variable is required

[FLINK-26332]Move the operator env to common utils

---

.github/workflows/ci.yml
e2e-tests/data/cr.yaml
e2e-tests/test_last_state_upgrade.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/JobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingClusterClient.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/JobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java

This PR tries to support last-state upgrade mode. 
Given that the HA is enabled, if we want to upgrade the job with latest successful checkpoint, we could simply destroy the K8s deployment. All the HA related ConfigMaps will be retained. Then we start the job with same cluster-id and it should recover from the latest retained checkpoint.
[1]. https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/ha/overview/#high-availability-data-lifecycle
[2]. https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/ha/kubernetes_ha/#high-availability-data-clean-up

[FLINK-26141] Support last-state upgrade mode

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/BaseReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/JobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/JobReconcilerTest.java

First part following resource dependencies in the reconciler logic: Wait for the JM deployment to be ready before trying to access the JM. This will be built upon for improving the error detection/handling later on.

[FLINK-26261] Wait for JobManager deployment ready before accessing REST API

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java

Use the common method to construct service name. 
Besides, the `RestOptions.ADDRESS` is always generated at the server side we can not get it from the client config. 
Since the flink-operator is always deployed with the flink job in the same cluster, we can directly use the `Servicename.Namespace` to talk to Flink job rest server.
I'am not sure whether need to remove the `config.getString(RestOptions.ADDRESS, xx)`

[FLINK-26356] Use the common method to construct service name

---

e2e-tests/utils.sh

This pr is meant to print the debug log respect to the multi container. This has been verified by this [pipeline](https://github.com/apache/flink-kubernetes-operator/runs/5393653458?check_suite_focus=true). cc @wangyang0918

[FLINK-26435] Provide the container name for CI debug log

---

Dockerfile
docker-entrypoint.sh
flink-kubernetes-webhook/pom.xml

Currently the webhook module builds it's own shaded jar which includes the operator shaded jar contents as well that is unnecessary and simply adds to the size of the flink operator image. Operator dependencies should be configured in the `provided` scope and the operator shaded jar could be put on the classpath when the webhook starts.
- Updates the scope of the dependencies `flink-kubernetes-operator`to `provided` and remove the `flink-core` dependencies in the `pom.xml` of the `flink-kubernetes-webhook` module.
- Adds the classpath option with the path of `OPERATOR_JAR` for webhook starting in `docker-entrypoint.sh`.

[FLINK-26447] Clean up webhook jar and dependency management

---

README.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroup.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricOptions.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroupTest.java
helm/flink-operator/templates/flink-operator.yaml
helm/flink-operator/values.yaml

- added documentation on how to enable Prometheus metrics reporter on the operator
- add option for exposing a dedicated port for metrics on the operator container
- minor fix in the operator metric group name that works for Prometheus

[FLINK-26257] Enable metrics configuration for Prometheus

---

.github/workflows/ci.yml
Dockerfile
flink-kubernetes-operator/pom.xml
flink-kubernetes-shaded/pom.xml
pom.xml

When we compile the flink-kubernetes-operator, we could find the following overlapping classes of fabric8 kubernetes client dependencies. I propose to add a flink-kubernetes-shaded module to fix this in current project. If we are confident enough the shading works well, I will contribute it to the upstream project Flink.
```
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] flink-kubernetes_2.12-1.14.3.jar, kubernetes-model-coordination-5.12.1.jar define 18 overlapping classes:
[WARNING]   - io.fabric8.kubernetes.api.model.coordination.v1.LeaseFluentImpl$SpecNestedImpl
[WARNING]   - io.fabric8.kubernetes.api.model.coordination.v1.LeaseListFluentImpl$ItemsNestedImpl
[WARNING]   - io.fabric8.kubernetes.api.model.coordination.v1.LeaseSpec …
```

FLINK-26476 Introduce flink-kubernetes-shaded to avoid overlapping classes

---

Dockerfile
docker-entrypoint.sh
flink-kubernetes-operator/pom.xml

Solves a problem where we had a compile dependency on a fatjar which does not really work in many cases.

[hotfix] Make flink-kubernetes-shaded dep provided

---

e2e-tests/data/cr.yaml
examples/basic-checkpoint-ha.yaml
examples/basic-ingress.yaml
examples/basic-session.yaml
examples/basic.yaml
examples/custom-logging.yaml
examples/pod-template.yaml
helm/flink-operator/templates/_helpers.tpl
helm/flink-operator/templates/rbac.yaml
helm/flink-operator/templates/serviceaccount.yaml
helm/flink-operator/templates/webhook.yaml
helm/flink-operator/values.yaml

This separates the Flink job role from the operator role, which fixes two issues:
1. That when the `operatorNamespace` is the same as one of the `watchNamespaces` the install fails due to attempted duplicated role creation which I introduced in #35.
2. That deleting the operator role affected jobs described in FLINK-26471.
@wangyang0918 has raised another issue with #35 [here](https://github.com/apache/flink-kubernetes-operator/pull/35#issuecomment-1058750206), that prior to 1.15 when using `watchNamespaces` unless the user explicitly sets 
```
kubernetes.rest-service.exposed.type: ClusterIP
```
I would like to avoid overwriting the default Flink behavior in the operator, my suggestion is to present a warning to the user in the admission control validation and we might a line to the …

[FLINK-26308][FLINK-26471] Separate Flink job role from operator role

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobManagerDeploymentStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/Observer.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/JobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/Reconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/ObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/JobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DeploymentValidatorTest.java

The main goal of this PR is to allow upgrading/suspending clusters even if they are still deploying / failing under certain conditions:
- Session cluster
- Job cluster with stateless or last-state upgrade modes
To achieve this, the PR simplifies the observe -> reconcile flow by removing the sketchy isReadyToReconcile logic in between and moving the contained logic to the right places in the reconcilers.
I have also added test cases to validate the upgrade behaviour in cases where the cluster is not ready/running yet for all cluster types.

[FLINK-26507] Allow session and last-state jobs to reconcile in any state

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/OperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobManagerDeploymentStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

Make config names cleaner and reduce reschedule delays while the job is deploying.

[FLINK-26572] Improve reconcile reschedule configs and defaults

---

helm/flink-operator/conf/flink-default-config/flink-conf.yaml
helm/flink-operator/conf/flink-default-config/log4j-console.properties
helm/flink-operator/conf/flink-operator-config/flink-conf.yaml
helm/flink-operator/conf/flink-operator-config/log4j2.properties
helm/flink-operator/templates/flink-operator.yaml
helm/flink-operator/values.yaml

Main changes:
- Move the default config and logging properties to files from the helm templates
- Allow users to easily override operator and flink default configs from helm chart values
- Allow users to use easily use their own configmaps instead of ones created by helm
This PR should be merged only after https://github.com/apache/flink-kubernetes-operator/pull/51 as the config keys have already been adapted to that PR.

[FLINK-26574] Expose config files in helm chart

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java

A small improvement to have a good default when running the operator outside of k8s. (I find myself switching back and forth and don't want to rely on local files.) As mentioned in the comment, this can become an operator config if we agree that this is useful.

Use localhost for REST API when running outside k8s

---

README.md

- Update `Developer Guide` in README for the operator installation under the root path of this repo

[FLINK-26671] Update Developer Guide in README to fix operator installation

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/DeploymentFailedException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/BaseObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

Adds handling for listJobs errors and with that ongoing error checking for the underlying deployment.
Need to add test coverage, this is for early comments.

[FLINK-26473] Check for deployment errors when listJobs fails

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/JobStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/JobObserverTest.java
helm/flink-operator/crds/flinkdeployments.flink.apache.org-v1.yml

The current `JobStatus.updateTime` actually means the start time, not the last update time. We could introduce a new field `startTime` and make `updateTime` reflect its original intention.
- Adds the field `startTime` in `JobStatus` to represent the start time.

[FLINK-26649] Add startTime in JobStatus

---

docs/content/docs/custom-resource/overview.md
docs/content/docs/custom-resource/reference.md
e2e-tests/data/cr.yaml
examples/basic-checkpoint-ha.yaml
examples/basic-ingress.yaml
examples/basic-session.yaml
examples/basic.yaml
examples/custom-logging.yaml
examples/pod-template.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/FlinkDeploymentSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/FlinkVersion.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultDeploymentValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DeploymentValidatorTest.java
helm/flink-operator/crds/flinkdeployments.flink.apache.org-v1.yml

This PR changes the FlinkVersion from string to enum.
I simply copied the FlinkVersion enum from flink master so that we can adapt this directly once we bump the flink dep to at least 1.15.

[FLINK-26640] Make FlinkVersion enum and required

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/OperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobManagerDeploymentStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/JobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SessionObserverTest.java
helm/flink-operator/conf/flink-operator-config/flink-conf.yaml
helm/flink-operator/values.yaml

The `OperatorConfigOptions` options mostly have .sec in the names to denote seconds intervals. The Duration type configs should be used so that users can specify them in a more user friendly way and remove .sec from the name.
- Modifies the type of configs to `Duration` and removes `.sec` from `OperatorConfigOptions`.

[FLINK-26714] Remove .sec from OperatorConfigOptions and use Duration type config instead

---

.github/workflows/ci.yml
Dockerfile
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/OperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SessionObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/JobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SessionObserverTest.java

- Add `isJobManagerServing()` method to use the rest call(i.e. "/jobs/overview") to check if JM can actually serve requests after JM is deployed.
- Add the previous check in the `BaseObserver` logic to be executed every time before reconcile when JM state is `READY`.
- Enhance `SessionObserverTest` and `FlinkDeploymentControllerTest`  to include the case when JM port is ready but the rest service is not available.

[FLINK-26605] Check if JM can serve rest api calls every time before reconcile

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SessionObserver.java

- Adjust the check logic in `SessionObserver#observe()` method using same logic with `JobObserver#observe()` to reduce extra `observe()` call due to https://github.com/apache/flink-kubernetes-operator/pull/62#discussion_r830146506

[FLINK-26655] Improve the observe logic in SessionObserver

---

.github/workflows/ci.yml
e2e-tests/test_kubernetes_application_ha.sh
e2e-tests/test_last_state_upgrade.sh
e2e-tests/utils.sh

I implemented the additional test as GHA `strategy.matrix`, this seemed the best approach going forward. This provides full separation and parallel execution, but consumes an extra container.
Added additional checks for status messages after the e2e test job completes checkpoints as per @wangyang0918's suggestion. These show up in the logs as follows on successful execution:
```
Log "Completed checkpoint [0-9]+ for job" shows up.
Successfully verified that flinkdep/flink-example-statemachine.status.jobManagerDeploymentStatus is in READY state.
Successfully verified that flinkdep/flink-example-statemachine.status.jobStatus.state is in RUNNING state.
Kill the flink-example-statemachine-7fcf55c88b-qwpl9
Defaulted container "flink-main-container" out of: flink-main-container, …
```

[FLINK-26715] Extend e2e ci test matrix with watchNamespaces enabled

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
pom.xml

Upgrade the SDK version thus eliminating some annoying exception logs on cleanup caused by a race condition.

[FLINK-26554] Upgrade Operator SDK to avoid cleanup race condition

---

e2e-tests/test_kubernetes_application_ha.sh
e2e-tests/test_last_state_upgrade.sh
e2e-tests/utils.sh

I went with a simple extra wait-time approach as the tools already existed for this.
The meaningful alternative is to add expected whitelisted states, like `DEPLOYED_NOT_READY` instead of `READY` where we do wait and fail otherwise. I felt that this was unnecessarily complex. 
I will retrigger the e2e tests 3 times before merging this to establish confidence that it does solve the issue.

[FLINK-26804] Improve e2e test status check stability

---

examples/advanced-ingress.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/FlinkDeploymentSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/IngressSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/IngressUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultDeploymentValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/IngressUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DeploymentValidatorTest.java
helm/flink-operator/crds/flinkdeployments.flink.apache.org-v1.yml

- users can customise the endpoint address of the Flink UI
- eliminates the need for a wildcard DNS entry `*.example.com`
- enables path and domain based routing with ingress

[FLINK-26706] Introduce Ingress URL templating

---

.github/workflows/ci.yml
docs/content/docs/custom-resource/reference.md

We need to verity the java doc is consistent with the code implementation via the CI. Otherwise, it is very easy to forget to re-generate the java doc after some changes. Thanks `git diff` we could make the verification easier :)
A failed case could be found here. https://github.com/wangyang0918/flink-kubernetes-operator/runs/5656298427?check_suite_focus=true

[FLINK-26816] Verify the java doc is consistent with the code implementation

---

flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilderTest.java
pom.xml

- hot fix for the NPE caused by [FLINK-26706](https://issues.apache.org/jira/browse/FLINK-26706) Introduce Ingress URL templating
- bumped surfire version see https://issues.apache.org/jira/browse/SUREFIRE-1741

[FLINK-26815] Tests in FlinkConfigBuilderTest are skipped

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/BaseObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SessionObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

I change the `JobReconciler#reconcile()` a bit in this PR. Even though, the spec does not change, we still have a chance to update the reconciliationStatus.

[FLINK-26768] Clear errors when observed running job successfully

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/JobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SessionReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/JobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java

Break redeployments into two steps to avoid getting into an inconsistent state if job submission fails.

[FLINK-26830] Transition to SUSPEND before redeploying on job upgrades

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/BaseObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobObserver.java

- Make logger output current and next status in JobObserver/BaseObserver to help developers/users track status from k8s log

[FLINK-26832] Output more status info for JobObserver and BaseObserver

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultDeploymentValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DeploymentValidatorTest.java

Add sanity check for `state.savepoints.dir` when using savepoint upgrade mode and manually triggering endpoint for the running job.
- `DefaultDeploymentValidator` adds the check for `state.savepoints.dir` when the upgrade mode is `SAVEPOINT` or `savepointTriggerNonce` isn't null.

[FLINK-26836] Add sanity check for state.savepoints.dir when using savepoint upgrade mode

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/JobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultDeploymentValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/JobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DeploymentValidatorTest.java

> At the moment there are several corner cases which can lead to accidental state loss (or at least weird behaviour) when switching to last-state upgrade mode from other modes.
>
> 2 cases that immediately come to mind:
>
> savepoint to last-state: 
When the new upgrade mode is last-state, the job deployment will simply be deleted. If HA was not enabled previously, the last savepoint might be very far back in time.
>
> stateless to last-state:
If checkpointing and HA is not enabled, the deployment will simply be killed like previously and we might start a job from empty state. Maybe taking a savepoint would be the right approach in this case and continue from there.
After this PR, a savepoint will always be triggered when users change upgrade mode from stateless/savepoint to last-state. …

[FLINK-26577] Always trigger a savepoint when upgrade mode changed to last-state

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/FlinkDeploymentSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/JobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/JobReconcilerTest.java
helm/flink-operator/crds/flinkdeployments.flink.apache.org-v1.yml

This PR is meant to add ability to restart deployment with one-shot command. 
**Brief change**
- Add `restartNonce` in the `FlinkDeployment#spec`
- JobReconciler will react to the `restartNonce` change by restarting the flink deployment.

[FLINK-26538] Add ability to restart flink deployment

---

flink-kubernetes-operator/pom.xml

This fix disables the shade plugin for the flink-kubernetes-operator module when using the apache-release in order to not deploy the fatjar as part of the release process.

[hotfix] Disable flink-kubernetes-operator shade step on apache-release profile

---

.github/workflows/docker_push.yml

I managed to make this work with simply using `flink-operator` for the docker image name, after reconsideration I prefer this for brevity.
We only publish images for the `main` branch after this PR, I will proceed with working on the release branch/tag setup.
We should improve this ideally where we only tag the image with the `latest` tag if the CI finishes successfully.

[FLINK-26214] Publish Docker images to GitHub Registry

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/OperatorConfigOptions.java

Align with other duration option name format

[hotfix]Remove the .sec in the config option

---

flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.automaton
flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.checker-qual
flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.kryo
flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.minlog
pom.xml

Given that `flink-kubernetes-shaded` already contains a NOTICE file, and `flink-kubernetes-webhook` does not bundle any dependencies. This PR is trying to add a correct NOTICE file only for the `flink-kubernetes-operator` module.
I have reviewed all the bundled dependencies in the uber jar to make sure they are listed in the NOTICE file with correct license.
cc @gyfora @tweise correct me if I miss anything.

[FLINK-26903] Add correct NOTICE file to flink-kubernetes-operator

---

e2e-tests/data/cr.yaml
e2e-tests/test_last_state_upgrade.sh
e2e-tests/utils.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

[BP][FLINK-26916] Remove job graph from K8s HA ConfigMaps when submitting a Flink application cluster

---

.github/workflows/ci.yml
.github/workflows/docker-bake.hcl
.github/workflows/docker_push.yml
Dockerfile

This enables us to publish docker build for both `amd64` and `arm64`. You can verify this via:
```shell
% docker manifest inspect ghcr.io/mbalassi/flink-operator:149986a
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 3055,
"digest": "sha256:017787b0c5ccf724f676ed73f26c2928a2d9d58c4464e4ba7fb00ca3f2470158",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 3055,
"digest": "sha256:c37a552f048c0431672dc190e735f4a618bd0c42030de4fea9cdc02dbab88fee",
"platform": {
"architecture": "arm64",
"os": "linux"
}
}
]
}
```
While working on this I noticed instability of the …

[FLINK-26214] Support cross platform image builds

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultDeploymentValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DeploymentValidatorTest.java

Currently the validator only checks whether HA is enabled. Since our last-state logic only works with Kubernetes HA we should actually enforce the type of the Ha service also.

[FLINK-26917] Enforce Kubernetes HA during validation for last-state mode

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/Mode.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/BaseObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/Observer.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ObserverFactory.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SessionObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/JobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SessionObserverTest.java

- Adjust current logic in `FlinkDeploymentController` from `validate with new config -> observe with new config -> reconcile with new config `to `observe with latest validated config -> validate new config -> reconcile with new config` to get rid of the case that once a wrong config is applied without webhook, the controller will get stuck on the validation error and lose control of the previous running deployment.
- Refactor `FlinkConfigBuilder` to add support of building config with metadata and deployment spec.
- Add corresponding test.

[FLINK-26892] Observe current status before validating CR changes

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SessionReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/SessionReconcilerTest.java

When I test session cluster, I found that it will always start twice for the session cluster. I think this fix should be included in the release-0.1

[FLINK-26996] Break the reconcile after first create session cluster

---

docs/content/docs/operations/configuration.md

- Add `Deployment` -> `Configuration` tab in the doc website. This page can be used to document other configs as well. (e.g. https://issues.apache.org/jira/browse/FLINK-27008)
- Add document of operator config options.

[FLINK-26611] Document operator config options

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilderTest.java

When last-state upgrade mode is selected, the validation whether checkpointing is turned on (in addition to the HA settings) should be considered.
- `DefaultDeploymentValidator` adds the validation whether checkpointing is turned on when upgrade mode is `LAST_STATE`.

[FLINK-26893] Validate checkpoint config with last-state upgrade mode

---

.github/workflows/ci.yml

Using [cache](https://github.com/marketplace/actions/cache) to speed up workflows.

[FLINK-27012] Caching maven dependencies to speed up workflows in github actions

---

docker-entrypoint.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkOperatorWebhook.java
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

Provide a way to set jvm args and also print the start up options using the flink tools
---
By this we can also easily remote debug in the minikube environment 
```
helm install flink-operator helm/flink-kubernetes-operator  --set image.repository=aitozi/flink-java-operator --set image.tag=latest --set jvmArgs.operator='-agentlib:jdwp=transport=dt_socket\,server=y\,suspend=y\,address=*:5005'
kubectl port-forward {operator-pod} 5005:5005
```

[FLINK-27000] Support to set JVM args for operator

---

.asf.yaml

Making sure that notification schema is setup like it's currently for Flink core. Details about this file can be found in https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

[hotfix] Change email/repository notifications to match with Flink Core settings

---

docs/content/docs/operations/configuration.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/OperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractDeploymentReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
helm/flink-kubernetes-operator/conf/flink-operator-config/flink-conf.yaml

The current `waitForClusterShutdown` logic has a hardcoded 60 second timeout and prints a log message after every second, which should be improved to make the max timeout configurable and only log a message once every 5-10 seconds to make this more reasonable.
- `waitForClusterShutdown` adds the max timeout configuration `operator.reconciler.flink.shutdown.cluster.timeout` and logs a message once every 5 seconds.

[FLINK-27141] Improve FlinkService#waitForClusterShutdown logic

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilderTest.java

`web.cancel.enable` should be set to false for application deployments to avoid users accidentally cancelling jobs.
- `FlinkConfigBuilder` set `web.cancel.enable` to false for application deployments.

[FLINK-27154] Disable web.cancel.enable for application clusters

---

helm/flink-kubernetes-operator/templates/rbac.yaml

In issue [27211](https://issues.apache.org/jira/browse/FLINK-27211) found a problem where the Flink operator wouldn't deploy on an OpenShift cluster due to missing finalizers in the role and clusterrole.  When the lines are added, then the basic.yaml is able to deploy sucessfully:
```
Client Version: 4.8.35
Server Version: 4.8.35
Kubernetes Version: v1.21.8+ee73ea2
NAME                                         READY   STATUS    RESTARTS   AGE
basic-example-5cc7894895-chxzw               1/1     Running   0          19m
basic-example-taskmanager-1-1                1/1     Running   0          19m
flink-kubernetes-operator-697c4b866b-6jrkt   2/2     Running   0          20m
```

Flink 27211 deployments/finalizers missing for OpenShift Deployment

---

examples/basic-session-job.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/JobStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/context/ApplicationObserverContext.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/context/VoidObserverContext.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobHelper.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
flink-kubernetes-operator/src/test/resources/log4j2-test.properties

This PR is meant to support the upgrade/trigger savepoint for the session job. The brief change as below:
- Complete the `FlinkSessionJobReconciler` to handle spec change
- Complete the `SessionJobObserver` to observe the job status and savepoint result
- Add the `FlinkSessionJobReconcilerTest` and `SessionJobObserverTest` to verify the change.
I have done the basic verification locally to verify the upgrade with `sateless` and `savepoint` and trigger savepoint. But as I test, the `cancel` operation will always cleanup the HA data. So I have not figured out how to support `last_state` mode in session job. So I disable the `last_state` mode now.
An e2e test will be introduce in a following PR to guard the session job functional.

[FLINK-26871] Handle session job spec change

---

Dockerfile
flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EnvUtils.java
flink-kubernetes-operator/src/main/resources-filtered/.flink-kubernetes-operator.version.properties
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkOperatorWebhook.java
pom.xml

```
2022-04-07 11:48:01,357 o.a.f.k.o.FlinkOperator       [INFO ]  Starting Flink Kubernetes Operator (Version: 1.14.4, Scala: 2.12, Rev:895c609, Date:2022-02-25T11:57:14+01:00) 
```
The version information in `FlinkOperator` and `FlinkOperatorWebhook` come from Flink binary, not the flink-kubernetes-operator.
-` EnvUtils` adds the `logEnvironmentInfo` method to log information about the environment, like project version, code revision, current user, Java version, and JVM parameters.

[FLINK-27124] Flink Kubernetes operator prints starting logs with wrong version

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java

In the "FlinkService#stopSessionCluster" method, if 'deleteHaData=true', the 'FlinkUtils#waitForClusterShutdown' method will be called twice.
So we should only execute 'FlinkUtils#waitForClusterShutdown' again with 'deleteHaData=false',This will reduce two visits to the kubernetes cluster

[FLINK-27289]Do some optimizations for "FlinkService#stopSessionCluster"

---

.github/workflows/ci.yml
.gitignore
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/resources/log4j2-test.properties
pom.xml

- Fix FlinkOperatorITCase that not sets JM replica correctly.
- Due to the [doc of failsafe plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/), use the `mvn verify` to replace `mvn integration-test` so the `post-integration-test` phase can be executed and as a result, if the IT fails, the maven build will fail.

[FLINK-27310] Fix FlinkOperatorITCase

---

docs/content/docs/operations/configuration.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconcilerTest.java
helm/flink-kubernetes-operator/conf/flink-conf.yaml

Currently all upgrades (regardless of upgrade mode) are delayed as long as there is a pending savepoint operation, which should allow users to override this and execute the upgrade (thus potentially cancelling the savepoint) regardless of the savepoint status.
- Add the `kubernetes.operator.job.upgrade.ignore-pending-savepoint` option to allow users to force upgrade regardless of the savepoint status.

[FLINK-26926] Allow users to force upgrade even if savepoint is in progress

---

docs/content/docs/operations/rbac.md
examples/advanced-ingress.yaml
examples/basic-checkpoint-ha.yaml
examples/basic-ingress.yaml
examples/basic-session-job.yaml
examples/basic-session.yaml
examples/basic.yaml
examples/custom-logging.yaml
examples/pod-template.yaml

Remove hardcode default namespace from the flinkdeployment examples.
Document the step to create flinkdeployment in other namespaces when watchNamespaces not used.
Signed-off-by: ted chang <htchang@us.ibm.com>

[FLINK-27129][docs] Hardcoded namespace in FlinkDeployment manifests may fail to deploy

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java

It doesn't need to create temporary pod template files for JobManager and TaskManager if it is not configured explicitly via `.spec.JobManagerSpec.podTemplate` or `.spec.TaskManagerSpec.podTemplate`.
- `FlinkConfigBuilder#setPodTemplate` adds the check to create temporary pod template files for JobManager and TaskManager when it is configured explicitly via `.spec.JobManagerSpec.podTemplate` or `.spec.TaskManagerSpec.podTemplate`.

[FLINK-27422] Do not create temporary pod template files for JobManager and TaskManager if not configured explicitly

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/JobSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

This PR introduces the `allowNonRestoredState` in `JobSpec` to let the session job can enable/disable it individually.

[FLINK-27458] Expose allowNonRestoredState flag in JobSpec

---

docs/content/docs/operations/validator.md

Currently we allow users to specify custom validator implementations through the operator configuration. This can be very useful in production environments to implement custom validation logic that is specific to certain envs. How to custom validator implementations should have document to introduce.
- Adds the `validator.md` to document how to custom the `FlinkResourceValidator` implementation.

[FLINK-27097] Document custom validator implementations

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/ReconciliationState.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

This PR solves the issue detailed in https://issues.apache.org/jira/browse/FLINK-27500 by reconciling using the previous (valid) spec if validation fails for some reason.
This allows rollback/jm-recovery operations to proceed even if an invalid CR was submitted in thea meantime

[FLINK-27500] Validation errors should not block reconciliation

---

.github/workflows/ci.yml
docs/content/docs/custom-resource/job-management.md
docs/content/docs/custom-resource/overview.md
docs/content/docs/custom-resource/pod-template.md
docs/content/docs/custom-resource/reference.md
docs/content/docs/operations/ingress.md
e2e-tests/data/flinkdep-cr.yaml
e2e-tests/data/sessionjob-cr.yaml
e2e-tests/test_kubernetes_application_ha.sh
e2e-tests/test_last_state_upgrade.sh
e2e-tests/test_sessionjob_ha.sh
e2e-tests/utils.sh
examples/basic-session-job.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/FlinkVersion.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml

The core k8s related features:
- native k8s integration for session cluster, 1.10
- native k8s integration for application cluster, 1.11
- Flink K8s HA, 1.12
- pod template, 1.13
Hence required the minimum version could be set to 1.13 which allows more users to have a try on flink-kubernetes-operator. The e2e tests should be updated to cover all the supported versions.
- Add the `tests.sh` to cover all the supported versions for e2e tests.

[FLINK-27412] Allow flinkVersion v1_13 in flink-kubernetes-operator

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java

In [FLINK-27154](https://issues.apache.org/jira/browse/FLINK-27154), we disable `web.cancel.enable` for application cluster. We should also do this for session cluster.
- Sets `web.cancel.enable` to false at default in `FlinkConfigBuilder` to avoid users accidentally cancelling jobs.

[FLINK-27261] Disable `web.cancel.enable` for session cluster

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/OperatorUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java
pom.xml

This PR reworks how status updates of Flink resources are updated in kubernetes. This is necessary due to https://github.com/java-operator-sdk/java-operator-sdk/issues/1198
Based on offline discussion with the JOSDK team this seems to be the safest short term solution.
The caching of the latest status is necessary to avoid race condition between spec updates and status patches that are made by us.
Tests have been updated with some init logic to enable patching them through the kubernetes client + removed the reliance of mutating status.

[FLINK-27551] Update status manually instead of relying on updatecontrol

---

docs/content/docs/custom-resource/job-management.md
docs/content/docs/custom-resource/overview.md
docs/content/docs/custom-resource/pod-template.md
docs/content/docs/custom-resource/reference.md
e2e-tests/data/flinkdep-cr.yaml
e2e-tests/data/sessionjob-cr.yaml
examples/advanced-ingress.yaml
examples/basic-checkpoint-ha.yaml
examples/basic-ingress.yaml
examples/basic-session-job.yaml
examples/basic-session.yaml
examples/basic.yaml
examples/custom-logging.yaml
examples/pod-template.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/JobManagerSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/Resource.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

1. Revisit default values in org.apache.flink.kubernetes.operator.crd.spec (details is [here])(https://issues.apache.org/jira/browse/FLINK-27329?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)
2. Set default value of `crd.spec.Resource#cpu` to `1.0`
3. Set default value of  `crd.spec.FlinkDeploymentSpec#serviceAccount` to `flink`
4. Set default value of  `crd.spec.JobManagerSpec#replicas` to 1 and remove its usage in examples.

[Flink 27329] Add default value of replica of JM pod and not declare it in example yamls

---

.github/workflows/docker_push.yml

These should be tagged manually from the latest rc instead.

[FLINK-27036] Exclude final release tags from docker build

---

docs/content/docs/concepts/overview.md
examples/basic-checkpoint-ha.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

This is a workaround for  https://issues.apache.org/jira/browse/FLINK-27569 . It creates random job result stores :
```
ls -al /tmp/flink/ha/job-result-store/basic-checkpoint-ha-example/
total 0
drwxr-xr-x 6 9999 9999 120 May 11 15:39 .
drwxr-xr-x 3 9999 9999  60 May 11 14:52 ..
drwxr-xr-x 2 9999 9999  60 May 11 15:32 1e080985-a3a9-4390-8567-134bc1f4c2d1
drwxr-xr-x 2 9999 9999  40 May 11 15:39 a6031ec7-ab3e-4b30-ba77-6498e58e6b7f
drwxr-xr-x 2 9999 9999  60 May 11 15:11 b6fb2a9c-d1cd-4e65-a9a1-e825c4b47543
drwxr-xr-x 2 9999 9999  60 May 11 15:19 e569a5db-abb3-44ac-8169-545eeb46914a
```
It leaks the storage files on every upgrade, that is a know concern.
Verify:
- Run the basic-checkpoint-ha example
- suspend the job
- kill JM -> verify no jobs starts
- resume the job - verify the job …

[FLINK-27573] Configuring a new random job result store directory

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractDeploymentReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/IngressUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java
flink-kubernetes-operator/src/test/resources/log4j2-test.properties
helm/flink-kubernetes-operator/values.yaml

**This PR contains the following improvements/fixes for a number of loosely connected blocker issues:**
1. Eliminate bug that causes 0 delay infinite reconcile loop with the UpdateControl management logic
2. Ensure HA metadata is available when we are relying on it during stateful upgrades
3. Make JM deployment recovery condititional on availablity of HA metadata
4. Trigger fatal error when upgrade progress is stuck
5. Clean up and improve stateful upgrade conditions with added detailed debug logging
6. Greately simplify code around suspend/cancellation and restore operation in the reconciler
7. Make sure finished jobs are marked as stable to avoid rollback loop for short jobs

[FLINK-27572][FLINK-27594] Ensure HA metadata is present before restoring job with last state

---

docs/content/docs/custom-resource/reference.md
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/SavepointInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

Add savepoint history to status, with age and count based savepoint expiration. Example:
```
Status:
Job Manager Deployment Status:  READY
Job Status:
Job Id:    7cedf7c39c986e583dbebd372be3a8d3
Job Name:  State machine job
Savepoint Info:
Last Savepoint:
Location:    file:/flink-data/savepoints/savepoint-7cedf7-0fb4b50d72b6
Time Stamp:  1652671155388
Savepoint History:
Location:         file:/flink-data/savepoints/savepoint-7cedf7-ab75503094b5
Time Stamp:       1652670977699
Location:         file:/flink-data/savepoints/savepoint-7cedf7-1c12ca67aa68
Time Stamp:       1652671008035
Location:         file:/flink-data/savepoints/savepoint-7cedf7-0fb4b50d72b6
Time Stamp:       1652671124981
Trigger Id:         20342ead12977c31384dfd83cda82377
Trigger Timestamp:  1652671114901
Start Time: …
```

[FLINK-27435] Savepoint History

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java

Because we delete the jar after submitting the job, it's better to leave some logs for the end users

[FLINK-27600] Add minimal jar coping and deleting logs

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/FlinkDeploymentStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/CustomDashboardConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/CustomDashboardConfigurationHeaders.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml

This PR is meant to improve the ability to identify malicious Flink versions (CVE affected, deprecated, etc.) in managed environments. The operator propagates exact versioning information in status:
```
status:
clusterInfo:
flink-revision: 3a4c113 @ 2022-04-20T19:50:32+02:00
flink-version: 1.15.0
```

[FLINK-27609] Tracking flink-version and flink-revision in FlinkDeploymentStatus

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/DeploymentFailedException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java

- Separated the event related logic from the DeploymentFailedExceptions
- Introduced a new component type for JobManagerDeployment, reporting DeploymentFailedExceptions
- Reduced the event types to Warning and Normal only see [API docs](https://github.com/kubernetes/api/blob/master/events/v1/types.go#L84)

[FLINK-27665] Optimize event triggering on DeploymentFailedExceptions

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/SavepointInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointFetchResult.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java

Cancelling savepoint operation on application failures
Cancelling savepoint operation on savepoint fetching failures
Generating events for failed savepoint operations

[FLINK-27675] Improve manual savepoint tracking

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusHelper.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingStatusHelper.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/StatusHelperTest.java

Check whether status changed before applying patch to reduce load on the kubernetes API.

[FLINK-27686] Only patch status on change

---

tools/releasing/create_source_release.sh

I find a strange invalid image event when preparing the 1.0.0 release candidate after `helm install`.
```
Events:
Type     Reason         Age               From               Message
----     ------         ----              ----               -------
Normal   Scheduled      11s               default-scheduler  Successfully assigned default/flink-kubernetes-operator-7b95cdb948-54kj8 to minikube
Warning  InspectFailed  8s (x3 over 10s)  kubelet            Failed to apply default image tag "ghcr.io/apache/flink-kubernetes-operator:2.417603e+06": couldn't parse image reference "ghcr.io/apache/flink-kubernetes-operator:2.417603e+06": invalid reference format
Warning  Failed         8s (x3 over 10s)  kubelet            Error: InvalidImageName
Warning  InspectFailed  8s (x3 over 10s)  kubelet …
```

[hotfix] Make image tag in helm chart values as an explicit string

---

Dockerfile

Flink kubernetes operator docker image could not build with source release at present. The `.git` directory should be copied when the directory exists.

[FLINK-27746] Flink kubernetes operator docker image could not build with source release

---

tools/releasing/create_source_release.sh

`helm package` command will remove the apache license header in the `Chart.yaml`. Given that we already update the version in `update_branch_version`, it is unnecessary to specify the `--app-version` and `--version` again.
So we could simply use `tar` to prepare the helm package.

[FLINK-27747] Use tar instead of helm package when creating source release

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

UPGRADING state means we have either deleted the deployment for last-state upgrades or observed the result of the cancel with savepoint operation.
No need to further observe anything

[FLINK-27804] Do not observe cluster/job mid upgrade

---

docs/content/docs/operations/configuration.md

The Kubernetes operator now support dynamic config changes through the operator ConfigMap.This feature is not documented properly and it should be added to the operations/configuration page.
- Document dynamic operator configuration in the `operations/configuration` page.

[FLINK-27668] Document dynamic operator configuration

---

docs/content/docs/custom-resource/reference.md
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/Savepoint.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/SavepointInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/SavepointTriggerType.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobHelper.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/SavepointUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

This PR contains a few key improvements for savepoint triggering / management:
1. Unify and simplify savepoint triggering between application and session jobs
2. Simplify savepoint info update logic
3. Add trigger type information to savepoints (we can also add new features to the cleanup logic based on this as a next step)
4. Introduce periodic savepoint triggering
5. Improve test coverage

[FLINK-26179] Support for periodic savepoints

---

docs/content/docs/try-flink-kubernetes-operator/quick-start.md

Fixing the example from release-0.1 to release-1.0.0

[FLINK-27923] Update quick-start.md

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconcilerTest.java

This PR changes the savepoint triggering / observe flow by only updating the lastReconciledSpec.savepointTriggerNonce after the manual savepoint was successfully completed.
This change allows the reconciler to seamlessly retry the savepoints within the grace period without adding new complicated retry logic.
Other changes:
- Rename the grace period config to kubernetes.operator.savepoint.trigger.grace-period to more closely reflect the functionality and make it per-job configurable
- Some other related cleanups and minor refactorings in the SavepointObserver

[FLINK-27257] Retry failed savepoints within grace period

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

The validation for valid lastSavepoint path is obsolete and can actually cause issues when trying to resume a job after a last-state suspend operation.
With the current logic upgradeMode mostly affects how the job is suspended and not how they are restored, as the way the job was suspended directly affects what state is available for restore.
The only exception is stateless restore which directly forces empty state, otherwise the job will always use the last state available (in other words, last-state restore is implicit)

[hotfix] Remove incorrect savepoint path check

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java

Currently the event name do not include the uid of the target resource. If a resource is recreated, it will be associated with the former object's events. It's not expected and will be confusing with the empty events when describe the resource.

[FLINK-27961] Include the resource uid when generate the event name

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/context/VoidObserverContext.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingClusterClient.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java

This PR improve the logic in `JobStatusObserver`
- generate an event after each job state changed. 
- fetch the JobResult for `FAILED` job and forward the error to the CR status

[FLINK-27497] Track terminal job states in the observer

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/ConfigOptionUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ConfigOptionUtilsTest.java

Currently `savepointHistoryMaxCount` and `savepointHistoryMaxAge` is part of the `FlinkOperatorConfiguration` class which means that users cannot override this from their user deployment. `savepointHistoryMaxCount` and `savepointHistoryMaxAge` should be removed and get directly from the effective config. A max allowed value for these configurations that is configured on the FlinkOperatorConfiguration level so that users cannot infinitely grow the status size and cause problems for the k8s api should be introduced.

[FLINK-27913] Remove savepointHistoryMaxCount and savepointHistoryMaxAge from FlinkOperatorConfiguration

---

docs/content/docs/custom-resource/reference.md
examples/hpa/basic-hpa.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/FlinkDeploymentStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/TaskManagerInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractDeploymentReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml

This is a proof of concept of introducing Kubernetes scaling capabilities and support for using the Horizontal Pod Autoscaler for application deployments.
**Background:** 
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
**Scaling for Flink applications:**
Our initial idea was to use the parallelism as the scaling unit/parameter. This is however not a really good match for the Kubernetes scaling behaviour, where you have a concept of replicas and watch pods/containers to decide whether to scale up or down. By using parallelism you will end up with confusing terminology and half used task managers (where not all the slots are taken)
We decided it …

[FLINK-27685] Scale subresource prototype

---

docs/content/docs/operations/upgrade.md

1. Add document of #204 in the `Operator Upgrade Process` to emphasize the change of default values when upgrading from 0.1.0 to 1.0.0

[FLINK-28025] Document the change of serviceAccount in upgrading doc of k8s opeator

---

.github/workflows/ci.yml
e2e-tests/data/multi-sessionjob.yaml
e2e-tests/test_multi_sessionjob.sh
e2e-tests/utils.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventSourceUtils.java

Creating the primary cache indexers using composite keys [name,namespace] in EventSourceUtils. Added a sample job to the comments to reproduce the issue: https://issues.apache.org/jira/browse/FLINK-27892. 
Note: Added a one liner method to emphasise what we are doing, can be removed if needed.

[FLINK-27892] More than 1 secondary resource related to primary

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
flink-kubernetes-webhook/src/test/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandlerTest.java

The meta.name of FlinkDeployment CR must be match the regex:
` '[a-z]([-a-z0-9]*[a-z0-9])?'`
By RRC-1035, a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?').
The rest service name of Flink Cluster uses the meta.name of FlinkDeployment CR, So the value of meta.name must follow the convention of DNS-1035 label.
To avoid operator repeatedly creating and destroying flink clusters due to invalid service name, So I suggest add validation for the meta.name of FlinkDeployment CR.

[FLINK-28087]Add validation for the meta.name of FlinkDeployment CR.

---

.github/workflows/ci.yml

- Moved the e2e tests into a new matrix dimension:
```
matrix:
version: ["v1_15","v1_14","v1_13"]
namespace: ["default","flink"]
test:
- test_application_kubernetes_ha.sh
- test_application_operations.sh
- test_sessionjob_kubernetes_ha.sh
- test_sessionjob_operations.sh
- test_multi_sessionjob.sh
```
- Removed the seemingly redundant mvn build from e2e_ci job
- The e2e test total execution time has been reduced to sub 10min range.

[FLINK-28059] Parallelize e2e tests

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/FlinkDeployment.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/ReconciliationStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/SavepointUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/StatusRecorderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

This change allows the operator to recover from errors during and directly after Flink cluster submissions. One common cause for this would be a temporary unavailability of the kubernetes API which would prevent us from updating the status after deployment.
Before this change this would lead to a fatal error where the operator would try to submit the flink cluster again and again (even though it is already deployed)
To solve this case the following changes were introduced:
- LastReconciledSpec now contains the CR generation for the deployed spec. During upgrades this is recorded during the first SUSPEND step of the upgrade operation
- The CR generation is also added as an annotation to the Flink Cluster Deployment object
- The default ReonciliationStatus for new deployments is now …

[FLINK-27820] Handle deployment errors on observe

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorRetryConfigurationTest.java
helm/flink-kubernetes-operator/conf/flink-conf.yaml

JOSDK defaults to the following retry configuration (exponential backoff)
```
GenericRetry.defaultLimitedExponentialRetry()
.setInitialInterval(2000)
.setIntervalMultiplier(1.5D)
.setMaxAttempts(5);
```
This PR makes it configurable via the following operator config options:
```
kubernetes.operator.retry.initial.interval: 5 s
kubernetes.operator.retry.interval.multiplier: 2
kubernetes.operator.retry.max.attempts: 10
```

[FLINK-28166] Configurable Automatic Retries on Error

---

docs/content/docs/custom-resource/job-management.md
docs/content/docs/operations/configuration.md
docs/content/docs/operations/helm.md
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
helm/flink-kubernetes-operator/conf/flink-conf.yaml
helm/flink-kubernetes-operator/values.yaml

[FLINK-27912] Improve operator config names
From | To
-- | --
kubernetes.operator.reconciler.flink.cancel.job.timeout | kubernetes.operator.flink.client.cancel.timeout
kubernetes.operator.reconciler.flink.cluster.shutdown.timeout | kubernetes.operator.resource.cleanup.timeout
kubernetes.operator.observer.flink.client.timeout | kubernetes.operator.flink.client.timeout
kubernetes.operator.reconciler.jm-deployment-recovery.enabled | kubernetes.operator.jm-deployment-recovery.enabled
kubernetes.operator.reconciler.reschedule.interval | kubernetes.operator.reconcile.interval
kubernetes.operator.reconciler.max.parallelism | kubernetes.operator.reconcile.parallelism
- change helm default flinkconfig values
- html doc for **kubernetes_operator_config_configuration.html**
- Replaced related fields …

[FLINK-27912] Improve operator config names

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/CommonStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractDeploymentReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java

We used to try clearing errors out by setting this `null` but due to how Status patching works, this basically means no update was made.
This commit fixes this by setting to empty string instead.

[FLINK-28233] Clear error status correctly for stable deployments

---

e2e-tests/test_sessionjob_operations.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventSourceUtils.java
flink-kubernetes-operator/src/main/resources/log4j2.properties
pom.xml

- bumping JOSDK version v3.0.2 -> v3.0.3
- add primaryToSecondary mapper for session jobs
- removing the workaround for setting namespaces (not needed anymore from JOSDK v3.0.3+)
- Changing config dumps into a one-liner

[FLINK-28008] Can not get secondary resource from context after operator restart

---

tools/releasing/create_source_release.sh

Newer git clients seem to return 8 letter hashes sometimes by default. This fix ensures that our release scripts always uses only the first 7 letters.

[tooling] Use 7 letter hash in release scripts

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/listener/FlinkResourceListenerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java

Record events that may be of interest to users when looking at the deployment with describe. Generally, these will be conversions of existing log messages. I added couple examples for illustration, will add more like submit or trigger/complete savepoint if there is agreement on the approach.

[FLINK-26891] Record important deployment events

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/ReconciliationStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ReconcilerFactory.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java

This PR makes some major improvements to the spec upgrade and initial deployment flow.
Most importantly, everytime before deploying a new spec (initial deployment or during upgrade) we patch the status and record the spec being upgraded to in the `lastReconciledSpec` with `UPGRADING` ReconciliationState.
This allow us to always detect when an UPGRADE was successful even if the subsequent status upgrade failed for any reason.

[FLINK-28228] Never skip generations when observing already upgraded deployment

---

helm/flink-kubernetes-operator/values.yaml

When I added the`imagePullSecrets`, I found it now worked as expected.
The reason is that there exists an `imagePullSecrets` field at the bottom of the file that is not easy to notice.

chore: move up imagePullSecrets field in the Helm values

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java

- Moving the status patching from the SavepointObserver to the main reconcile() loop
- Added extra status assertions to verifyBasicReconcileLoop to better reflect the complete lifecycle

[FLINK-28331] Persist status after every observe loop

---

.github/workflows/ci.yml
flink-kubernetes-docs/src/main/java/org/apache/flink/kubernetes/operator/docs/configuration/ConfigOptionsDocGenerator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/artifact/ArtifactFetcher.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/FlinkVersion.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/CommonStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/SavepointInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/Reconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/ConfigOptionUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/mutator/DefaultRequestMutator.java

- Fix all javadoc errors and warnings
- Add `javadoc:javadoc` to CI build to ensure that we don't merge javadoc errors.

[hotfix] Clean up javadoc errors & build javadoc as part of the CI

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

Introducing `kubernetes.operator.job.upgrade.last-state-fallback.enabled` variable to enable configurable fall-back to last-state upgrade when the job is not running but HA is available.

[FLINK-28348] Add configurable flag to disable last-state fallback for savepoint upgrade

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

This error may happen if I use Golang to submit the job with some bugs.

[FLINK-28385] Change the validator to return an error if the Jar URI is an empty string

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

As HA metadata is not always compatible (for example Flink 1.14 <-> 1.15) we should always take a savepoint between version upgrades and not allow rollbacks.

[FLINK-28350] Always use savepoint when switching between Flink versions

---

examples/flink-sql-runner-example/Dockerfile
examples/flink-sql-runner-example/README.md
examples/flink-sql-runner-example/pom.xml
examples/flink-sql-runner-example/sql-example.yaml
examples/flink-sql-runner-example/sql-scripts/simple.sql
examples/flink-sql-runner-example/sql-scripts/statement-set.sql
examples/flink-sql-runner-example/src/main/java/org/apache/flink/examples/SqlRunner.java
examples/flink-sql-runner-example/src/main/resources/log4j2.properties
pom.xml

This PR introduces a complete example for running SQL Scripts directly using the operator. 
With this we provide users a straightforward way of running SQL scripts without relying on any new operator or upstream features. This should satisfy the general need.

[FLINK-27009] Add example for running SQL scripts using the operator

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/MetricManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingStatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/listener/FlinkResourceListenerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/StatusRecorderTest.java

Moved the `MetricManager` into` StatusRecorder`. All (status related) metrics are maintained now via the StatusRecorder.

[FLINK-28356] Move operator metric recording logic into statusrecorder

---

.github/workflows/ci.yml
helm/flink-kubernetes-operator/Chart.yaml

Adds helm chart linting to ci and fixes a warning in the chart.
Please observe this run I triggered on my own fork to simulate an intentional failure:
https://github.com/mbalassi/flink-kubernetes-operator/runs/7236387391?check_suite_focus=true

[FLINK-28450][ci] Validate Helm Chart linting during CI

---

docs/content/docs/operations/configuration.md
docs/content/docs/operations/metrics-logging.md
docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/kubernetes_operator_metric_configuration.html
docs/layouts/shortcodes/generated/system_advanced_section.html
docs/layouts/shortcodes/generated/system_section.html
flink-kubernetes-docs/src/main/java/org/apache/flink/kubernetes/operator/docs/configuration/ConfigOptionsDocGenerator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroup.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesResourceMetricGroup.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesResourceNamespaceMetricGroup.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesResourceNamespaceScopeFormat.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesResourceScopeFormat.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/MetricManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorMetricUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingStatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/listener/FlinkResourceListenerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroupTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/StatusRecorderTest.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkOperatorWebhook.java

Clean up and formalize operator metric scopes:
- `system`: Operator level metrics
- `namespace`: Resource Namespace level metrics (belonging to one of the watched namespaces)
- `resource` : Resource level metrics
Before:
```
hostname.k8soperator.default.flink-kubernetes-operator.Status.JVM.Memory.Mapped.MemoryUsed: 0
hostname.k8soperator.default.flink-kubernetes-operator.resourcens.default.FlinkDeployment.DEPLOYING.Count: 0
```
After:
```
hostname.k8soperator.default.flink-kubernetes-operator.system.Status.JVM.Memory.Mapped.MemoryUsed: 0
hostname.k8soperator.default.flink-kubernetes-operator.namespace.default.FlinkDeployment.DEPLOYING.Count: 0
```
One given metric called `Metric` in the 3 scopes:
```
<prefix>.system.Metric
<prefix>.namespace.resourceNs.Metric …
```

[FLINK-28297][FLINK-27914]  Improve operator metric groups + Add JOSDK metric integration

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java

This PR is meant to use the same mechanism of the `AbstractDeploymentObserver`. It can recognize the lost job information now, based on the fixed jobId generator. 
- Use the `uid.hashcode` + `generation` to make up the `JobID`.
- Detect the jobs in the session cluster with the same uid prefix and generation. 
- new tests to verify the change. 
- Core observer or reconciler logic that is regularly executed: (yes)

[FLINK-28187] Handle SessionJob errors on observe

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetrics.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetricsTest.java

Currently the JOSDK metrics forwarder logic doesn't implement the `timeControllerExecution` function.  We should implement it with the following logic.
1. Measure execution time for successful failed executions
2. Based on the name of the ControllerExectution (reconcile/cleanup) and controller name, track the following histogram metrics metrics
`JOSDK.{ControllerExecution.controllerName}.{ControllerExecution.name}.{ControllerExecution.successTypeName}/failed`
- Introduces the `Histogram` metric in the `timeControllerExecution` with the metric name format `JOSDK.{ControllerExecution.controllerName}.{ControllerExecution.name}.{ControllerExecution.successTypeName}/failed`.
- *`OperatorJosdkMetricsTest` adds the `testTimeControllerExecution` to verify whether the `Histogram` metric is …

[FLINK-28480] Forward timeControllerExecution time as histogram for JOSDK Metrics interface

---

docs/content/docs/operations/metrics-logging.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetrics.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/StatusRecorderTest.java

Add JmDeploymentStatus as a group for JobManagerDeploymentStatuscount metrics.
Before:
```
localhost.k8soperator.default.flink-kubernetes-operator.namespace.default.FlinkDeployment.READY.Count: 1
```
After:
```
localhost.k8soperator.default.flink-kubernetes-operator.namespace.default.FlinkDeployment.JMDeploymentStatus.READY.Count: 1
```
This change is already covered by existing tests, such as:
- `StatusRecorderTest` (removed redundant tests)
- `FlinkDeploymentMetricsTest` (updated existing tests)
- Does this pull request introduce a new feature? (no) 
- Metrics documentation is …

[FLINK-28472] Add JmDeploymentStatus as a group for JobManagerDeploymentStatuscount metrics

---

docs/content/docs/operations/metrics-logging.md
docs/layouts/shortcodes/generated/kubernetes_operator_metric_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/KubernetesClientUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetricsTest.java

This pull request adds metrics and KPIs related to Kubernetes API server access. Metrics can be enabled by `kubernetes.operator.kubernetes.client.metrics.enabled` (defaults to `true`). Sample history for histograms is controlled by `kubernetes.operator.metrics.histogram.sample.size` (defaults to 1000).
- added various request/response counters
```
-- Counters -------------------------------------------------------------------
localhost.k8soperator.default.flink-kubernetes-operator.KubeClient.HttpRequest.Count: 94
localhost.k8soperator.default.flink-kubernetes-operator.KubeClient.HttpRequest.POST.Count: 6
localhost.k8soperator.default.flink-kubernetes-operator.KubeClient.HttpRequest.PATCH.Count: 10
localhost.k8soperator.default.flink-kubernetes-operator.KubeClient.HttpRequest.DELETE.Count: …
```

[FLINK-28476] Add metrics for Kubernetes API server access

---

docs/content/docs/custom-resource/overview.md
examples/basic-session-job.yaml
examples/flink-sql-runner-example/Dockerfile
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
pom.xml

Bump Flink version to 1.15.1
- Changed the Flink version from 1.15.0 to 1.15.1 in relevant project files
- Removed redundant `<flink.shaded.version>15.0</flink.shaded.version>` from main `pom.xml` file
```
eval $(minikube docker-env)
DOCKER_BUILDKIT=1 docker build . -t flink-kubernetes-operator
helm install flink-kubernetes-operator helm/flink-kubernetes-operator
k create -f examples/basic.yaml
```
- Dependencies (does it add or upgrade a dependency): (yes)

[FLINK-28517] Bump Flink version to 1.15.1

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_section.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java
helm/flink-kubernetes-operator/conf/flink-conf.yaml

Adds support for labelselector on Flink custom resources. This enables having multiple operators potentially watch the same namespace for blue/green deployment scenarios. When no selector is set the existing behavior of watching all resources of a namespace is reatined.
I have added a test for it verifying that we properly pass the labelselector configuration to JOSDK. Unfortunately the test fails when run together with a specific other test, have to fix this. It might make sense to add an e2e test to cover this too.
- Does this pull request introduce a new feature? (yes)
- If yes, …

[FLINK-28496] Label selector setting for operator

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java

Fix sending unnecessary spec change events during upgrades
Fixed sending unnecessary spec change events during upgrades
Modified existing tests to verify the events triggered during upgrades
- Core observer or reconciler logic that is regularly executed: (yes)

[FLINK-28534] Spec change event is triggered twice per upgrade

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconcilerTest.java

Fix bug where session upgrade would not be completed if an exception was thrown directly before submission.
Fix invalid logic in AbstractFlinkResourceReconciler#checkNewSpecAlreadyDeployed to always return false in UPGRADING state.
Added new cases to SessionReconcilerTest to cover this failure scenrio
- Core observer or reconciler logic that is regularly executed: (yes)

[FLINK-28478] Always complete in-progress update

---

docs/layouts/shortcodes/generated/kubernetes_operator_metric_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorMetricUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetricsTest.java

Fix a few smaller bugs/issues with the JOSDK metrics reporting logic that was added recently.
- *Use correct class for FlinkSessionJobController to avoid nullpointer exception*
- *Avoid creating metric groups again and again for counters and histograms*
- *Remove unnecessary synchronization for built in histogram*

[FLINK-27914] Fix SessionJobController name + avoid creating new metric groups all the time

---

.github/workflows/ci.yml
docs/content/docs/operations/helm.md
docs/content/docs/try-flink-kubernetes-operator/quick-start.md
helm/flink-kubernetes-operator/templates/_helpers.tpl
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/templates/webhook.yaml
helm/flink-kubernetes-operator/values.yaml

Improve and clarify webhook configuraiton in helm chart.
- webhook.create provides the default enable/disable flag for both mutating and validating webhook
- webhook.mutator/validator.create can optionally override this setting
- Upgrade cert-manager 1.8.0 -> 1.8.2
Manually tested on minikube

[FLINK-28207] Improve webhook helm configuration

---

README.md

Remove explicit list of versions/image tags from README . These versions are already listed/updated on the Flink website during the upgrade process.

[docs] Do not list explicit versions / imagetags in README

---

flink-kubernetes-operator/pom.xml
flink-kubernetes-webhook/pom.xml
pom.xml

Setting explicit version for okhttp until we can upgrade to new version of JSODK with the fix.
- Setting explicit version for okhttp to 4.10.0 to fix PRISMA-2022-0239

[FLINK-28637] Set explicit version for okhttp to fix vulnerability (release-1.1)

---

flink-kubernetes-operator/pom.xml

Include JMX metrics reporter plugin to enable local developer to view metrics with simple console tools. JMX also facilitates integration with collectors such as Jolokia and New Relic Java agent.
Include JMX metrics reporter as an available plugin for the operator container image.
After building Docker image, plugin is verified on container file system
```
$ docker run --rm -it flink-operator ls -lah /opt/flink/plugins/flink-metrics-jmx/
total 36K
drwxr-xr-x 1 flink flink 4.0K Jul 25 13:42 .
drwxr-xr-x 1 flink flink 4.0K Jul 25 13:42 ..
-rw-r--r-- 1 flink flink  18K Jul 24 16:21 flink-metrics-jmx-1.15.1.jar
``` …

[FLINK-28654] Include JMX metrics reporter plugin

---

flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingClusterClient.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkServiceFactory.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroupTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ValidatorUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

Clean up warnings and some unnecessary, duplicated in the operator tests. 
- Fix missing generic parameters
- Remove unused methods/params
- Code style cleanup
- Remove some code duplications
- Replace deprecated junit.assert use

[hotfix] Clean up warnings and unnecessary code in tests

---

docs/layouts/shortcodes/generated/kubernetes_operator_metric_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/FlinkSessionJobMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroup.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesResourceNamespaceMetricGroup.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesResourceNamespaceScopeFormat.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesResourceScopeFormat.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/LifecycleMetrics.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkSessionJobMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroupTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/TestingMetricListener.java

This PR should be merged only after https://github.com/apache/flink-kubernetes-operator/pull/338
Include the resource class name `FlinkDeployment/FlinkSessionJob` directly in the KuberentesOperatorResourceNamespace metric group and expose it as part of the first component before the metric name.
This eliminates the need to add custom logic for any metric to include the resource name and makes it unifies across the codebase.
This PR introduces some changes to the reporting of some (previously inconsistently named) metrics:
**JmDeploymentStatus metrics**
```
BEFORE:
namespace.default.JmDeploymentStatus.READY.Count
AFTER:
namespace.default.FlinkDeployment.JmDeploymentStatus.READY.Count
```
**JOSDK metrics metrics**
```
BEFORE
resource.default.basic-example.JOSDK.Reconciliation.finished.Count …
```

[FLINK-28749] Include resource type in KubernetesOperatorResourceNamespaceMetricGroup

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/ReconciliationStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationMetadata.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java

Fix a bug that would cause the `initialSavepointPath` to be ignored if first deploy attempt fails completely.
- *Intorduce metadata flag in lastReconciledSpec for first deployments*
- *If first deployment fails, completely clear lastReconciledSpec so we once again trigger the first deploy logic instead of upgrade*
- *Added new testcase to FlinkDeploymentControllerTest to verify full flow*
- *Extended deployment/session job observer tests*
- If yes, how is the feature documented? not …

[FLINK-28845] Do not ignore initialSavepointPath if first deploy fails completely

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/CommonStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

Trigger Warning event on validation error. This is very useful in cases where the webhook is not enabled.
- Add event triggering to validation logic
- Improve ResourceLifecycleState in case of failed initial valiadation: `CREATED` -> `FAILED`
Extended `FlinkDeploymentControllerTest` to cover the new event triggering.

[FLINK-28846] Trigger event on validation error

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

Emit warning events for ClusterDeploymentException
- Trigger a K8s warning event when ClusterDeploymentException occurs.
This change added tests

[FLINK-28869] Emit a warning event for ClusterDeploymentException

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java

`pipeline.name` should be set to the resource name by default for application deployments.
- Sets the `pipeline.name` with the resource name in `applyFlinkConfiguration`.
- Updates the `FlinkConfigBuilder#testApplyFlinkConfiguration` to verify whether the default value of `pipeline.name` is the resource name.
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

[FLINK-28694] Set pipeline.name to resource name by default for application deployments

---

flink-kubernetes-operator/src/main/resources/META-INF/NOTICE

[FLINK-28892] Update NOTICE for flink-kubernetes-operator 1.1.1

[FLINK-28892] Update NOTICE for flink-kubernetes-operator 1.1.1

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/listener/FlinkResourceListener.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/listener/FlinkResourceListenerTest.java

Expose timestamp in FlinkResourceListener context so it's easier to build deterministic listeners.
- *Add timestamp to context*
- *For events use event timestamp, for status updates use wall clock time*
Updated `FlinkResourceListenerTest` to cover the new functionality.
- If yes, how is the feature documented? not documented

[FLINK-29033] Expose timestamp in resource listener context

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml

This pull request adds subPaths for each flink config file volume mount. Introducing subPaths in the template makes it possible use emptyDirs for mounting the config files which in return allows to enable `readOnlyRootFilesystem: true` for the operator. Without emptyDir volumes for the configs the operator refuses to start with readOnlyRootFilesystem enabled.
* Add subPaths for conf files to allow readOnlyRootFilesystem operation
- If yes, how is the feature …

[FLINK-28554] Add subPaths for conf files to allow readOnlyRootFilesystem operation

---

docs/content/docs/operations/metrics-logging.md

Add docs about how to enable Prometheus for `FlinkDeployment`

[docs] Add an example about how to enable Prometheus for FlinkDeployment

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml

Fix the Helm chart's env vars params
Helm chart small fix

[FLINK-29086] Fix the Helm chart's pod env params reference

---

examples/basic-reactive.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/AbstractFlinkSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/JobSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/TaskManagerSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/Diff.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/DiffBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/DiffResult.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/DiffType.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/Diffable.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/ReflectiveDiffBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/SpecDiff.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/diff/SpecDiffTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

Enable reactive scaling for standalone deployments by detecting and handling spec changes that do not require full application upgrades.
The standalone integration for session clusters and application clusters allows for more efficient scaling operations when only the parallelism changes. We should distinguish this operation in the reconciler/service and implement this for standalone mode.
- Added a new method `FlinkService.reactiveScale()` to handle reactive scaling for standalone deployments
- Added spec change detection that results a `DiffType`. Values can be:
- `IGNORE` - the job is not upgraded
- `SCALE` - if reactive mode is enable the job is rescaled, upgraded otherwise
- `UPGRADE` - the job is upgraded
- Added `diff` package to the public operator API, classes marked with …

[FLINK-28646] Handle scaling operation separately in reconciler/service

---

flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
helm/flink-kubernetes-operator/templates/_helpers.tpl
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/templates/rbac.yaml
helm/flink-kubernetes-operator/templates/webhook.yaml
helm/flink-kubernetes-operator/values.yaml

The names of the roles and rolebindings in the helm chart are not yet configurable. In this PR it's made configurable.
* Configurable role(binding) names
* Added option to bind rolebinding to clusterrole
Manually on minikube.

[FLINK-28734][helm] Configurable role(binding) names

---

pom.xml

This PR bumps Flink version to 1.15.2.
Bump Flink version to 1.15.2.
Existing tests.

[FLINK-29140] Bump Flink version to 1.15.2

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/listener/AuditUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/listener/ListenerUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/ResourceLifecycleState.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/main/resources/log4j2.properties

Being able to tell what status updates and events are being sent via the ResourceListener interfaces. It allows easy tail/grep for related messages reported under a specific resource.
- Added `Unified audit logging for StatusRecorder/EventRecorder`
- Added `description for ResourceLifecycleState`
- Minor fix in EventRecorded to avoid creating redundant `ctx` objects if multiple ResourceListeners are registered.
Manual verification:
```
2022-09-07 06:53:23,661 o.a.f.k.o.l.AuditUtils         [INFO ] [default.basic-example] >>> Event  | Info    | SPECCHANGED     | UPGRADE change(s) detected (FlinkDeploymentSpec[serviceAccount=flink] differs from FlinkDeploymentSpec[serviceAccount=flinkk]), starting reconciliation.
2022-09-07 06:53:23,680 o.a.f.k.o.l.AuditUtils         [INFO ] …
```

[FLINK-29194] Add logging for ResourceListener

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/fs/FileSystemWatchService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/ssl/ReloadableSslContext.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/fs/FileSystemWatchServiceTest.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkOperatorWebhook.java

At the moment SSL context is not realoading the certificate when changed. In this PR I've added this functionality.
* `FsWatchService` added with tests in `FsWatchServiceTest`
* `ReloadableSslContext` added
* Additional logging to see more
* Newly added unit tests
* Manually: https://gist.github.com/gaborgsomogyi/014054be6ef40326a2ade870f5f3dd02

[FLINK-28272] Handle TLS Certificate Renewal in Webhook

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/listener/FlinkResourceListenerTest.java

- Send initial CREATED status update
- Send Events when cancelling resources
- Modified the `StatusRecorder`, `FlinkDeploymentController`, `FlinkSessionJobController` with the changes
- Some minor fixes
Unit tests were updated `FlinkDeploymentControllerTest`, `FlinkResourceListenerTest`
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*
- The public API, i.e., is any changes …

[FLINK-29251] Send CREATED status and Cancel event via FlinkResourceListener

---

docs/content/docs/operations/helm.md
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

This pull request updates the helm chart to add the ability to set `dnsPolicy` and `dnsConfig` of the operator pod.
- Support setting `dnsPolicy` and `dnsConfig` of the operator pod
Manually verified this change on a Kubernetes cluster.

[FLINK-29302] Add helm chart support for setting dns policy and config

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
pom.xml

Java Operator SDK has released 3.2.1 version. Bump the JOSDK version to 3.2.1.
- Bump the Java Operator SDK to 3.2.1
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens …

[FLINK-28574] Bump the JOSDK version to 3.2.1

---

examples/basic-session-deployment-and-job.yaml
examples/flink-sql-runner-example/Dockerfile
examples/pod-template.yaml

There were several places where 1.15.1 was hardcoded. In this PR I've changed them to the latest 1.15.2.
Changed version from 1.15.1 to 1.15.2.
* Manually checked jar URIs.
* Existing tests.

[FLINK-29393] Upgrade Kubernetes operator examples to use 1.15.2 Flink base image

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/JobStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/ReconciliationStatus.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

Add `PrinterColumn` annotation to the state fields, so that we can use `k get flinksession -o wide` to see session job list with status fields.
- Add `@PrinterColumn` annotation to the state fields
I think the generated CRDs have covered the change 

[FLINK-29383] Add PrinterColumn annotation for status fields

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecorator.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesJobManagerParameters.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/standalone/KubernetesStandaloneClusterDescriptorTest.java

Pass JobSpec `args` through to Flink in Standalone mode.
- Add JobSpec args to flinkConfig in `FlinkConfigBuilder`
- Add a getter in `StandaloneKubernetesJobManagerParameters` that is used in `KubernetesStandaloneClusterDescriptor` to get the JobSpec args
- Added test to make sure that the `FlinkConfigBuilder` appends JobSpec args to the `flinkConfig`
- Added test to make sure that the `KubernetesStandaloneClusterDescriptor` appends JobSpec args
- If yes, how is the feature …

[FLINK-29388] Fix to use JobSpec arguments in Standalone Application Mode

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/CommonStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/ReconciliationStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationMetadata.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Fixes a small flaw in the initialDeployment logic that made it useless after the job was actually submitted. This also simplifies code in other places.
- *Rename ReconStatus#isFirstDeployment to isBeforeFirstDeployment to better reflect logic*
- *Fix reconciliation metadata isFirstDeployment computation*
- *Add some tests*
Partly covered by existing tests + new tests added for the fixed logic

[FLINK-29159] Harden initial deployment logic

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Automatically set jobId for Flink version < 1.16 to avoid conflicts in checkpoint path (and other jobId based effects).
* Set a jobId when no jobID is defined by user and Flink version is < 1.16.
* Rotate jobId when upgrade mode is stateless
Manual verification:
* No jobId set in Flink config
* Set upgrade mode to stateless. Trigger CR changes and check that every redeploy uses a new ID.
* Set upgrade mode to last_state. Trigger CR changes and check that ID does not change
- Core observer or reconciler logic that is regularly executed: (**yes** / no)
- Does this pull request …

[FLINK-29109] Avoid checkpoint path conflicts (Flink < 1.16)

---

flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
flink-kubernetes-shaded/pom.xml
flink-kubernetes-standalone/pom.xml
pom.xml

Also bumped the jackson version as snakeyaml is only transitively pulled by jackson to keep the versions closer and more up to date.

[FLINK-29384] Bump snakeyaml version to 1.32

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java

If the user incorrectly sets a Flink version lower than 1.15 when using 1.15 or above:
```
image: flink:1.15
flinkVersion: v1_14
```
then a spec change ends-up in exception and restart loop. In this PR we set `SHUTDOWN_ON_APPLICATION_FINISH` to `false` when Flink version is less than 1.15.
* Set `SHUTDOWN_ON_APPLICATION_FINISH` to false only on 1.15 and above
* Added unit test for all available Flink versions
* New unit test
* Manually
* Deploy app where
`image: flink:1.15 flinkVersion: v1_14`
* Wait for RUNNING state
* Change Flink config
* Double check that Flink is re-deployed and in RUNNING state again …

[FLINK-29376] Set SHUTDOWN_ON_APPLICATION_FINISH to false only on 1.15 and above

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventCollector.java

Fix a bug where without HA a deployed SessionJob could be lost without any errors triggered.
- *Detect when a session job is completely lost*
- *Trigger error event and set error status*
- *Add tests*
SessionJobObserverTest have been extended to cover the expected cases for HA/non-HA configs.

[FLINK-29392] Trigger error when session job is lost without HA

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Always persist the generated job id in status before the deploy attempt otherwise this info might be lost and lead to state recovery failure.
- *Record generated job id into status*
- *Add test*
Extended ApplicationReconcilerTest with new test case

[FLINK-29464] Persist generated jobid in status before deploy attempt

---

docs/content/docs/operations/metrics-logging.md

Provide an option to retrieve credentials for local prometheus/grafana setup
- Documentation updated
Manually

[docs] Prometheus/Grafana credentials via command

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/LifecycleMetrics.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/ResourceLifecycleMetricsTest.java

Fix the metric group of the global lifecycle metric histograms to contain resource type and thus avoid collision.
- fix metric group
- add test
Added new test to verify the groups

[FLINK-29474] Fix global lifecycle metrics group to include resource type

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/Savepoint.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/SavepointFormatType.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/SavepointInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SavepointObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

Currently it is not clear how one would associate completed manual savepoints with savepointTriggerNonce-es when using the operator. This makes it difficult to track when a savepoint was completed vs when it was abandoned. This solution adds the `triggerNonce` to the completed checkpoint info for `MANUAL` savepoints. Furthermore, the solution adds the format type too that was used to trigger the savepoint.
`Savepoint` class was extended by `triggerNonce` and `formatType` fields
- the change for `triggerNonce` is covered by changing existing unit test
- the change for `formatType` is covered by a new unit test
Manually by observing the `savepointInfo` in the CR:
```
savepointInfo:
formatType: CANONICAL
lastPeriodicSavepointTimestamp: 1664356683858
lastSavepoint:
formatType: CANONICAL …
```

[FLINK-29413] Make it possible to associate triggered and completed savepoints

---

docs/content/docs/custom-resource/overview.md

* Adding documentation about Native and Standalone deployment modes

Add CRD Documentation about the Flink Deployment Modes

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconcilerTest.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/factory/StandaloneKubernetesTaskManagerFactory.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesTaskManagerParameters.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/factory/StandaloneKubernetesJobManagerFactoryTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/factory/StandaloneKubernetesTaskManagerFactoryTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/ParametersTestBase.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/utils/TestUtils.java

Add owner reference to `FlinkDeployment` object when create `Deployment`
- add owner reference to `FlinkDeployment` object when create `Deployment`
---
**NOTE:** 
With this change, we can see relation of `FlinkDeployment` with other resources in ArgoCD Web UI
**AS-IS:**
**TO-BE:**

[FLINK-28979] Add owner reference to flink deployment object

---

e2e-tests/test_application_kubernetes_ha.sh
e2e-tests/test_application_operations.sh
e2e-tests/test_multi_sessionjob.sh
e2e-tests/test_sessionjob_kubernetes_ha.sh
e2e-tests/test_sessionjob_operations.sh

Currently e2e tests can be executed only from the main directory of the operator repo. In this PR I've made it current directory independent.
I've made e2e tests current directory independent.
Executing all e2e tests.

[FLINK-29507] Make e2e tests independent of the current directory

---

docs/content/docs/custom-resource/job-management.md
docs/content/docs/custom-resource/reference.md
docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/FlinkDeploymentStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/ClusterHealthInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/UnhealthyDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/health/ClusterHealthInfoTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluatorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

Flink has its own restart strategies which are working fine. But there are certain circumstances when Flink can stuck in a restart loop. A good example is when checkpointing is activated and the restart strategy has not been configured, then the fixed-delay strategy is used with `Integer.MAX_VALUE` restart attempts. When the JobManager (JM from now on) is able to solve its temporary issue, it can be that a permanent issue appears on TaskManager (TM from now on) side. A good example is that TM has a memory leak and just crashes. Such case the Flink job requires a restart from the outside, which can be done by the Flink k8s operator.
In this PR I've added job health check feature. Please be aware that the implementation is simple and has the following caveats:
* Restart count is watched in …

[FLINK-29394] Add observe Flink job health

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetrics.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/TestingMetricListener.java

The `KubernetesClientMetrics` class has a redundant background thread that periodically updates the `MeterView` metrics. However the `MetricRegistryImpl` already has a built in solution for this.
- Removed the periodic updater from `KubernetesClientMetrics`
- Updated the `TestingMetricListener` to follow the logic implemented in `MetricRegistryImpl`
- Updated the `KubernetesClientMetricsTest` to use the `TestingMetricListener`
- Covered by existing unit tests
- Verified manually

[FLINK-29619] Remove redundant MeterView updater thread from KubernetesClientMetrics

---

flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecorator.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesJobManagerParameters.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecoratorTest.java

Passing `initialSavepointPath` from the JobSpec as a `fromSavepoint` argument in the standalone mode.
- Updated `StandaloneKubernetesJobManagerParameters` to include savepoint path.
- Updated `CmdStandaloneJobManagerDecorator` to pass that as `fromSavepoint`.
- Also dropping the boolean parameter for the `allowNonRestoredState` flag: Flink may not parse it properly.
- Modified `CmdStandaloneJobManagerDecoratorTest` to confirm the argument is passed properly.
- Confirmed it's working after deploying to an internal staging environment.
- If …

[FLINK-29633] Pass fromSavepoint argument

---

flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecorator.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesJobManagerParameters.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecoratorTest.java

Backporting https://github.com/apache/flink-kubernetes-operator/pull/403 to the 1.2 release branch.

[FLINK-29633] Backport to 1.2

---

docs/content/docs/operations/helm.md
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

Support for `tolerations` in helm chart to allow operator pod to tolerate nodes with taints
- Add tolerations in operator deployment manifest
Tested with `helm template` to ensure `tolerations` is added to the operator's deploymentSpec when `tolerations` is set in the `values.yaml` file

[FLINK-29694] Support tolerations in helm template for flink operator deployment

---

flink-kubernetes-operator/pom.xml

*Added CRD compatibility check to Kubernetes operator 1.2.0*
- *Extending the CRD compatibility check against the Kubernetes operator in the pom.xml*
*This change is already covered by existing tests, such as *(CRD compatibility check)*. Extended the compatibility check against the 1.2.0 Kubernetes operator.*

Added the CRD compatability check to kubernetes operator 1.2.0

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/DeploymentFailedException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java

Handle cases when pod is unable to pull images. (a.k.a `ImagePullBackOff`)
Code is already handling `CrashLoopBackOff` this PR adds extra `ImagePullBackOff ` handling.
Added parameterized `FlinkDeploymentControllerTest.verifyInProgressDeploymentWithBackoff()`

[FLINK-29744] Throw DeploymentFailedException on ImagePullBackOff

---

helm/flink-kubernetes-operator/conf/flink-conf.yaml

Minor change based on mailng list discussion to align default confs with Flink for subtask number and parallelism.

[hotfix] Change default Helm operator configs to align with Flink

---

docs/content/docs/custom-resource/job-management.md
docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FailedDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java

It would be good to have the possibility to restart the Flink Application if it goes to `FAILED` state.
This could be used to restart, and reconfigure the job dynamically in the application `main` method if the current application can not handle the incoming data.
- Creates a new configuration `cluster.restart.failed` with the default `false`
- If the Application state is `FAILED` and the configuration is set to `true` then the application is removed and redeployed
- Added tests where the configuration is turned on, and the application is redeployed …

[FLINK-29713] Kubernetes operator should restart failed jobs

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/ReflectiveDiffBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EnvUtils.java

This PR attempts to add root cause (if exists) to RuntimeException, for a consistent trace & easier debug.
- Add root cause (if exists) to RuntimeException for a consistent trace & easier debug

[FLINK-29794]Flink Operator Need to Include Cause for Exceptions If Possible

---

docs/content/docs/concepts/overview.md
docs/content/docs/custom-resource/job-management.md
docs/content/docs/custom-resource/overview.md
docs/content/docs/custom-resource/pod-template.md
docs/content/docs/operations/ingress.md

The latest Flink operator version supports the deployment of Flink jobs that require version 1.16 but this is not specified in the overview page.
Added Flink 1.16 version in Features -> Core -> Multiple Flink version support

[hotfix][docs]Update overview.md to include flink version 1.16

---

flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/lifecycle/ResourceLifecycleState.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/CommonStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/listener/AuditUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/OperatorMetricUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/LifecycleMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/ResourceLifecycleMetricTracker.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/ResourceLifecycleMetricsTest.java

I missed this in my previous PR, this is needed for the EventListener functionality.

[FLINK-29655][hotfix] Move ResourceLifecycleState to api module

---

examples/kubernetes-client-examples/src/main/java/org/apache/flink/examples/Basic.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/FlinkDeploymentList.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/FlinkSessionJobList.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkOperatorWebhook.java

Removes deprecated fabric8 api usage after the 6.2.0 upgrade

[FLINK-29851] Remove deprecated fabric8 api usage

---

Dockerfile
docs/content/docs/development/guide.md
flink-kubernetes-operator/pom.xml
flink-kubernetes-standalone/pom.xml

Fix the `flink-kubernetes-standalone` dependency in the `flink-kubernetes-operator` submodule to actually use the shaded classifier which is required to avoid fabric8 conflicts when running from IntelliJ (and it's also the actual dependency we use at runtime also)
This change is already covered by existing e2e tests.

[FLINK-29851] Correctly depend on flink-kubernetes-standalone shaded classifier

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkSessionJobController.java

Trigger warning event for session job reconciliation exception.
Will be useful for monitoring.
Trigger warning event for session job reconciliation exception
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: ( no)

[FLINK-29581] Trigger warning event for session job reconciliation exception

---

.github/workflows/ci.yml
e2e-tests/data/flinkdep-cr.yaml
e2e-tests/data/multi-sessionjob.yaml
e2e-tests/data/sessionjob-cr.yaml

Enable 1.16 CI tests as a first step to support Flink 1.16. As agreed on JIRA we will move to using the 1.16 flink dependency once 1.16.1 is out.
Added new e2e test case for 1.16

[FLINK-29871] Add 1.16 to CI tests

---

flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
pom.xml

Signed-off-by: James Busche <jbusche@us.ibm.com>
The existing version 2.13.4 of jackson-databind has a high vulnerability (CVSS 7.5) that is fixed in 2.14.0
https://nvd.nist.gov/vuln/detail/CVE-2022-42003
Bumping the version in the pom.xml and src/main/resources/META-INF/NOTICE
- Successfully built new operator image from branch
- Twistlock security scan shows vulnerability no longer an issue.
- Tested new image on an OpenShift cluster, image worked as expected:
```
oc get pods
NAME                                         READY   STATUS    RESTARTS   AGE
basic-example-56876dc586-52g48               1/1     Running   0          2m40s
basic-example-taskmanager-1-1                1/1     Running   0 …
```

[FLINK-29853] Update with latest jackson databind

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_advanced_section.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java

This PR exposes the JOSDK feature described in https://javaoperatorsdk.io/docs/patterns-best-practices#stopping-or-not-operator-in-case-of-informer-errors-and-cache-sync-timeouts.
This allows ignoring recoverable informer errors on startup to increase the robustness of the opreator in prod environments.
- *Add new config option*
- *Add test*
Extended `FlinkOperatorTest`
- If yes, how is the feature documented? JavaDocs

[FLINK-29936] Add option to ignore informer errors on startup

---

docs/content/docs/operations/configuration.md
docs/content/docs/operations/helm.md
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_section.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java
helm/flink-kubernetes-operator/conf/flink-conf.yaml
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/templates/rbac.yaml
helm/flink-kubernetes-operator/values.yaml
pom.xml

Support enabling and configuring leader election for the kubernetes operator to make it possible to run standby operator instances.
- *Add configs to enable and configure the leader election service*
- *Add tests*
- *Update helm chart*
1. Extended the `FlinkOperatorTest` to cover the leader election config.
2. Manually tested on minikube

[FLINK-29919] Support operator leader election

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java

* Cleanup underlying deployment resources after cancel with savepoint. Flink version < 1.15 is supposed to do that automatically but we see instances where stray HA config maps cause resume/restore to fail.
* if the Flink version is < 1.15, cleanup deployment after cancel
* unit test modified to cover the version specific behavior
* manual verification with existing deployment

[FLINK-30004] Cleanup deployment after savepoint for Flink versions < 1.15

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Currently Flink 1.15+ application JMs are never shut down after termination.
This is not necessary as we only rely on them for one succesful observe step from the operator logic perspective.
This PR introduces a configured time after which the operator shuts down terminated application JMs. This allows users to still inspect the cluster for some time but not have lingering pods forever.
- *Add shutdown ttl config for application JMs*
- *Some FlinkService cleanup*
Extended the `ApplicationReconcilerTest` to cover for custom shutdown ttl. …

[FLINK-29609] Shut down JM for terminated applications after configured duration

---

docs/content/docs/custom-resource/reference.md
e2e-tests/test_application_operations.sh
e2e-tests/test_sessionjob_operations.sh
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/CommonStatus.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/Savepoint.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/SavepointInfo.java
flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/utils/BaseTestUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/StatusConflictException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SavepointUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingStatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/ResourceLifecycleMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SavepointObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Currently the operator uses `patchStatus()` without any resource version locking to update the Flink resources. This means that the operator overwrites whatever status was there previously. This was convenient so far but with leader election it is much more likely to get into a situation where this can be problematic.
This change introduces optimistic locking for the status which detects if someone externally modified the status without the reconciliation logic being aware of it.
There are 2 main problems that we target here:
1. Status updates by zombie operators who has last lost leadership but not realized/dead yet.
2. Stale status received when a new leader starts
**Why would these happen?**
Zombie operator: 
It could in theory happen that an operator loses leadership in a middle of …

[FLINK-29959] Use optimistic locking when updating the status

---

e2e-tests/test_application_kubernetes_ha.sh
e2e-tests/test_application_operations.sh
e2e-tests/test_multi_sessionjob.sh
e2e-tests/test_sessionjob_kubernetes_ha.sh
e2e-tests/test_sessionjob_operations.sh
e2e-tests/utils.sh

At the moment we're not checking that the operator is not having an error in its log. In this PR I've added an assertion when error exists in the log. There is an exclusion list which is easy to extend.
Add error checker for the operator in e2e tests

[FLINK-29475] Add error checker for the operator in e2e tests

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

To emit specific events along the following cases:
- JM recovery
- Unhealthy Job Restarts
`ApplicationReconciler` has been updated with the extra event logic
Unit tests where added to `ApplicationReconcilerTest` that covers the functionality.

[FLINK-30157] Trigger Events Before JM Recovery and Unhealthy Job Restart

---

e2e-tests/utils.sh

The condition is simply wrong, please see the following case:
```
$ expected=0
$ actual=""
$ if [[ expected -ne actual ]] then echo "Not same"; else echo "Same"; fi
Same
$ if [[ $expected != $actual ]] then echo "Not same"; else echo "Same"; fi
Not same
```
In this PR I've fixed this edge case.
Fixed the bash logic.

[FLINK-30176] Fix assert_available_slots when curl is returning empty response

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

Since 1.16 it is possible to set `kubernetes` as a value for `high-availability`
Operator needs to accept this as a valid value
- Changed the `FlinkUtils.isKubernetesHAActivated` to accept the new value
- Added a new test for it
- Added a new unit tests for the config checking
- Also run manual testing using the e2e tests to create a cluster using v1_16 flink and using the new config

FLINK-30222: Operator should handle 'kubernetes' as a valid setting for the 'high-availability' config key

---

.github/workflows/ci.yml
docs/content/docs/development/guide.md
e2e-tests/run_tests.sh
e2e-tests/utils.sh

Adding a possibility to run the e2e tests manually and using this same script to run the tests on the CI
- Refactored the test steps to `functions` in the util.sh
- Changed the `ci.yml` to use these new fuctions
- Created a shell script to run the tests
- This change is already covered by existing e2e - will see the test results
- Also manually executed the test script
- If yes, how is the feature documented? There is a help text in the script

FLINK-30199: Add a script to run Kubernetes Operator e2e tests manually

---

e2e-tests/utils.sh

Now e2e tests are not providing any operator or job logs when failing which makes it impossible to debug them. In this PR I've enabled debug logs when tests are failing.
Enabled debug logs when tests are failing.
Trivial change.

[hotfix][FLINK-30265] Turn on debug logs for k8s operator e2e tests in CI when tests failing

---

e2e-tests/utils.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java

When session jobs are in a specific states and cancel called they throw exceptions. In this PR I've added test for each state and changed the code to handle states correctly.
* Allow session job cancel to be called for each job state
* Minor refactor in the app cancel area
Existing + additional unit tests.

[FLINK-29974] Allow session job cancel to be called for each job state

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java

Revert an "improvement" to the HA metadata checking logic that actually only causes problems. In this case it did not allow jobs to recover without checkpoints in last-state mode.
revert change
manually verified 
- If yes, how is the feature documented? no

[FLINK-30266] Roll back change to HA metadata check logic

---

e2e-tests/utils.sh

The operator log error parser identified the metric as error which is definitely false positive:
```
Found error in log files.
flink-kubernetes-operator-7456697448-mgw42.k8soperator.flink.flink-kubernetes-operator.namespace.default.FlinkDeployment.JmDeploymentStatus.ERROR.Count: 0
```
In this PR I'm parsing for log4j error entry instead of plain error string in e2e tests.
* Parsing for log4j error entry instead of plain error string in e2e tests.
* Added whitelist entry: `Error while patching status`
- If yes, how is …

[FLINK-30281] Parsing for log4j error entry instead of plain error string in e2e tests

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

* Previously the logic to assign jobId to avoid checkpoint path collision was applied for Flink versions >= 1.16. Since even with the newer version the jobId is constant, albeit derived from clusterId, we need to overwrite it regardless of Flink version.
Modified existing tests.
- Dependencies (does it add or upgrade a dependency): (yes / no)
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no)

[FLINK-29109] Generate random jobId for stateless upgrade mode irrespective of Flink version

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EnvUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/templates/webhook.yaml

OLM currently provides the ability to install an operator either into a single namespace or all namespaces (though multiple namespaces may come later). The only way to determine what namespace the operator is targeted to watch for CR's is by looking at the annotations that olm injects into the operator deployment i.e. `olm.targetNamespaces`. By adding the WATCH_NAMESPACE env var that references this annotation we will be able to get the operator to correctly monitor the targeted namespace. N.b. if the operator is installed to watch all namespaces then the annotation is just an empty string
- Add the WATCH_NAMESPACE env var to EnvUtils
- Override Flink config to use this env var if it is defined i.e. not empty
- Modified helm charts so that the env vars for the pod use the deployments …

FLINK-29536 - Add WATCH_NAMESPACE env var to operator

---

e2e-tests/utils.sh

E2E tests are failing because several errors appear in the operator log. We've sorted out lot of issues but we're turning it off for the release temporarily.
Turn off e2e test error check temporarily
E2E tests.

[hotfix][FLINK-30307] Turn off e2e test error check temporarily

---

e2e-tests/utils.sh

In [#467](https://github.com/apache/flink-kubernetes-operator/pull/467) we've switched to `[ERROR]` parsing instead of case-insesitive `error`. `AuditUtils` is emitting only info level logs so we can safely remove from the whitelist.
Remove AuditUtils from error log check whitelist

[FLINK-30151] Remove AuditUtils from error log check whitelist

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/RecoverableDeploymentFailureException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/RecoveryFailureException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java

Make it possible to recover from the missing HA errors
- Created a new Exception signalling recoverable errors
- Made sure that the state of the cluster/job is not changed when a recoverable error happens
- Added unit test
- Added a unit test recovering from missing HA

[FLINK-30268] HA metadata and other cluster submission related errors should not throw DeploymentFailedException

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

At the moment it's not possible to add any flinkConfiguration in SessionJob which is blocking to submit session jobs. I can imagine configs which can be harmful in case of session jobs but we must have a blacklist like all other cases.
Allow to set flinkConfiguration in SessionJob.
Existing unit tests.

[FLINK-30154] Allow to set flinkConfiguration in SessionJob

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java

Delete the Job manager resources first when deleting a standalone Flink cluster as part of an upgrade in order to prevent HA configmaps from getting cleaned up. As described in the ticket, I was seeing job HA data getting deleted between cluster upgrades.
Changed the resource clean up order from TM then JM to JM then TM for standalone clusters.
Manually verified when upgrading a standalone session cluster with a SessionJob running on it, configmaps didn't get cleaned up after switching operator to deleting JM resources first.

[FLINK-30287] Delete job manager deployment first when cleaning up standalone cluster

---

docs/content/docs/operations/helm.md
helm/flink-kubernetes-operator/templates/_helpers.tpl
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

Tested it via running the following and similar commands:
```
% helm install flink-kubernetes-operator helm/flink-kubernetes-operator --set image.repository=ghcr.io/apache/flink-kubernetes-operator --set image.tag=main --set image.digest=sha256:a90c87d28f4e8832b8ac6cfa7318b01289f85fa35e46cc206d4de49212460111  --debug | grep image -C 5 
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /Users/mbalassi/git/apple/apache-flink-kubernetes-operator/helm/flink-kubernetes-operator
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
install.go:165: [debug] Clearing discovery cache
wait.go:48: [debug] beginning wait for 2 resources with timeout of 1m0s
client.go:128: [debug] creating 14 resource(s)
NAMESPACE: default …
```

[FLINK-30046] Support for operator docker image digest

---

e2e-tests/utils.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java

There are circumstances when job listing is not possible. Most of the errors what seen are temporary issues and the code is doing retry. In this PR I've changed the error message to a warning.
Log job listing exception as warning.

[FLINK-30146] Log job listing exception as warning

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml

When mounted volumes use subPath, the volume that uses them is not updated automatically. So, even you do update the ConfigMap in k8s, the flink-conf.yaml file will never see those updates. All of the entires in the flink-operator-config-volume configMap are mounted in each container anyway, so we might as well just mount the flink-operator-config-volume directly at /opt/flink/conf witihout specifying the subPath of each file.
This allows for Dynamic Operator Configuration to work when deployed with these helm charts.
https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/operations/configuration/#dynamic-operator-configuration
This pull request allows flink-kubernetes-operators deployed with the built in helm chart to work with Dynamic Operator Configuration.
- Mount …

[FLINK-30329] Mount flink-operator-config-volume at /opt/flink/conf without subPath

---

docs/content/docs/try-flink-kubernetes-operator/quick-start.md
e2e-tests/utils.sh

The operator uses a quite old version of kubernetes for minikube. The latest supported version is v1.25.3. I've bumped it.
Bump minikube kubernetes version for operator.
Executed `basic.yaml` on local minikube.

[FLINK-30381] Bump minikube kubernetes version for operator

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/DeploymentFailedException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java

Throw DeploymentFailedException on ErrImagePull.
This would add more info for the user to understand why the issue happened.
- Introduce a new value to check in the `ContainerStateWaiting.reason`
- Updated the relevant tests
- Removed a method which was accidentally added during a previous change
This change is already covered by the existing `FlinkDeploymentControllerTest.verifyInProgressDeploymentWithBackoff` test, just added a new reason to check 

[FLINK-30315] Add more information about image pull failures to the operator log

---

e2e-tests/test_application_kubernetes_ha.sh
e2e-tests/test_sessionjob_kubernetes_ha.sh
e2e-tests/utils.sh

e2e test change to ignore `REST service in session cluster is bad now` errors when we intentionally kill the JobManager
Adds the possibility to add more filters to the `check_operator_log_for_errors` function.
This change is already covered by existing tests, such as *e2e tests*.

[FLINK-30150] Ignore "REST service in session cluster is bad now" where we kill the JobManager manually

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/FlinkSessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java

Additional testing for FlinkSessionJob.
Also during the testing I have found an issue with the SessionJob savepoint handling.
- Additional tests
- Fixes for savepoint handlin
New tests are added to `FlinkSessionJobControllerTest`

[FLINK-28875] Add FlinkSessionJobControllerTest

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/FlinkSessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java

backport of https://github.com/apache/flink-kubernetes-operator/commit/c8ed11dfde1e0fc57d8fa45b0121ecec362bd03d
Contains a fix for `SessionJob` savepoint handling

[backport][FLINK-28875] Add FlinkSessionJobControllerTest

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java

We were tracking the stabilization period from the job start time which can greatly vary from the time the job goes into RUNNING state. This can result in no stabilization period at all leading to poor scaling decisions.
Thus, we change the logic to use the update time in combination with a RUNNING job status.

[FLINK-30463] Start stabilization period only after job goes into RUNNING

---

tools/olm/csv-template/bases/flink-kubernetes-operator.clusterserviceversion.yaml
tools/olm/docker-entry.sh
tools/olm/generate-olm-bundle.sh

Signed-off-by: James Busche <jbusche@us.ibm.com>
Fixes OLM Documentation issues that I noticed 
- basic.yaml was described using an old version
- The labels were hardcoded to 1.2.0
- The empty Provider needs to change to something to avoid future operator-sdk CI issues.  Changing to "Community" for now but possibly can make "The Apache Software Foundation" if people agree.
Fix basic.yaml version in:
- generate-olm-bundle.sh
- docker-entry.sh
Fix label version issues in:
- docker-entry.sh
Fix Provider in the csv-template
- csv-template/bases/flink-kubernetes-operator.clusterserviceversion.yaml
git clone https://github.com/jbusche/flink-kubernetes-operator.git
git checkout FLINK-30456
cd /tools/olm
vi env.sh and replace:
```
OPERATOR_IMG=ghcr.io/apache/flink-kubernetes-operator:main
with …
```

[FLINK-30456] Fixing Version and provider in OLM Description

---

e2e-tests/test_application_kubernetes_ha.sh
e2e-tests/test_sessionjob_kubernetes_ha.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FailedDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/UnhealthyDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

The purpose of this PR is to fix the long standing annoying case where the job was stuck after a non-upgradable state after starting/upgrading from a savepoint but the JobManager never starts.
In these cases previously we only supported last-state (HA based) upgrade which was impossible to do if the JM never started and never created the HA metadata configmaps.
The PR introduces a check whether the JobManager pods ever started by checking the Availability conditions on the JM deployment and comparing condition times with the deployment creation timestamp.
If availability is False and the Deployment never transitioned out of this state after creation, we can then assume that the JM never started and we can perform the upgrade using the last recorded savepoint.
This also removes the …

[FLINK-30406] Detect when jobmanager never started

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Trigger other reconciliation actions even if upgrademode is currently not available to not cause a stuck upgrade loop.
- Improved spec reconciliation logic
- Unit tests
Added new reconciler unit tests

[FLINK-30528] Reconcile other changes if upgrade is not available

---

flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/TaskManagerSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/diff/SpecDiffTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

Backport:
- 6e597f76  [FLINK-30527] Validate flinkVersion change for suspended jobs
- 0d2595ac [FLINK-30528] Reconcile other changes if upgrade is not available
- abc8e6b7 [FLINK-30361] Do not redeploy task managers when scaling standalone session cluster

Backport remaining fixes for 1.3.1

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

This PR validates `FlinkDeployment` without `jobManager` or `taskManager` spec. Currently, `FlinkDeployment` gets stuck in `UPGRADING` state if you don't specify `jobManager` or `taskManager` spec. 
By adding validation, `helm install` directly fails.
**Example: `basic.yaml`**
```yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
name: basic-example
spec:
image: flink:1.15
flinkVersion: v1_15
flinkConfiguration:
taskmanager.numberOfTaskSlots: "2"
serviceAccount: flink
job:
jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
parallelism: 2
upgradeMode: stateless
```
- Validate `FlinkDeployment` without `jobManager` or `taskManager` spec.
- Extended existing unit test for the change as part of …

[FLINK-30411] Validate empty JmSpec and TmSpec

---

docs/content/docs/custom-resource/pod-template.md
docs/layouts/shortcodes/generated/auto_scaler_configuration.html
e2e-tests/data/flinkdep-cr.yaml
examples/pod-template.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScaler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScaler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingSummary.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetric.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerInfoTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScalerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java

Refactor:
- Move parallelism computation logic from JobScalingExecutor to JobVertexScaler
Improvement:
- Improve scaling history management (added configs + cleanup) + tests
New Feature:
- Add configurable option to detect ineffective scaling decision by checking the capacity increase
Added new unit tests

[FLINK-30574] Detect ineffective scale up operations to avoid scaling further

---

pom.xml

Based on https://github.com/apache/flink/pull/21606
Artifacts are populated to maven deploy, e.g.:
https://repository.apache.org/content/repositories/snapshots/org/apache/flink/flink-core/1.17-SNAPSHOT/flink-core-1.17-20230110.001959-122-cyclonedx.json

[FLINK-30599][build] Publish SBOM artifacts

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/MetricAggregator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetricsTest.java

Make busyTime aggregation configurable and use MAX instead of AVG by default.
The previous AVG aggregation was very susceptible to overestimating the true processing/output rates in the presence of any data skew. This could lead to situations when the autoscaler assumed the operators were within their target capacity but in fact they were already backpressuring the whole pipeline.
Changing the default aggregation to MAX solves this problem.
Modified existing tests to verify the new aggregation scheme, and the configurable setting. Verified this manually on a skewed job.
- Does this pull …

[FLINK-30652] Use max busytime to compute true processing rate

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/docs/CrdReferenceDoclet.java

*This PR will resolve the CRD reference generation process. Currently the CRD reference generator does not respect JsonProperty annotation in case of enums (eg.: `public enum JobState`) which means the procedure generates the name of the ENUM instead of the value of the particular json property (eg.: `SUSPENDED` instead of suspended from `@JsonProperty("suspended")`). With these modifications generator will return with the values of the json properties in case of enums.*
- A new method added: `getNameOrJsonPropValue(Element e)`
- Call the `getNameOrJsonPropValue(Element e)` inside the `public Void scan(Element e, Integer depth)` method
- First I suggest to check the current version here: [/custom-resource/reference/](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/do …

[FLINK-30705] Fix CR ref gen to use JsonProperty annotation values

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FailedDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/UnhealthyDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java

- Improve test speed by only parameterizing with FlinkVersions that have different operator behaviour.
- Fix flaky rollback test and make it deterministic instead of relying on sleeps
Covered by existing unit tests.

[FLINK-30766][tests] Do not parameterize tests with all Flink versions

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml

In openshift when the operator is installed into a restricted namespace the operator is unable to create the /opt/flink/artifacts dir in order to download remote jars for jobs
- Modified the flink-operator.yaml to add an emptyDir volume mount for /opt/flink/artifacts
This change can be verified as follows:
- On an opensshift cluster create a new namespace
- Install the helm chart
- Apply the examples/basic-session-deployment-and-job.yaml
- Verify the jobs are running correctly

FLINK-30577 unable to access flink artifacts dir

---

examples/autoscaling/autoscaling.yaml
examples/autoscaling/src/main/java/autoscaling/AutoscalingExample.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScaler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScaler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/listener/AuditUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScalerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventCollector.java

The autoscaler currently doesn't trigger any events. We should use Kube events to notify users about scaling actions on a per-vertex level or in cases where the autoscaler blocked some scaling action due to past history.
- Added event triggering to `ScalingExecutor` in case of any parallelism change
- Added event triggering to `JobVertexScaler` in case of ineffective scaling 
- Added hotfix for autoscaling example
Added new unit tests:
- `ScalingExecutorTest.testScalingEvents()`
- `JobVertexScalerTest.testIneffectiveScalingDetection()`
- …

[FLINK-30653] Trigger resource Events on autoscaler actions

---

docs/content/docs/operations/helm.md
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

This pull request adds the possibility for helm chart users to specify resources block for operator pod.
- Allow configuring resources block for operator pod

[FLINK-30804] helm/flink-kubernetes-operator - allow specifying resources for operator pod

---

docs/README.md

At the moment CI notifies contributors that the doc needs to be re-generated which is fine. It would be good to add the command how to re-generate to the readme not to dig CI yaml all the time.
Added doc entry how to re-generate java doc.
Just a look at the doc readme.

[FLINK-30800] Add doc entry how to re-generate java doc

---

docs/content/docs/custom-resource/job-management.md
docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/ClusterHealthInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/UnhealthyDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/health/ClusterHealthInfoTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluatorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

There are workloads which stuck in such a way that they're in RUNNING state most of the time but not able to proceed and make checkpoints. Such cases must be detected by the operator. In this PR I've added the possibility to ask the operator to watch the number of successful checkpoints. If the feature is enabled by `cluster.health-check.completed-checkpoints.enabled` and there are no successful checkpoint within the defined window in `cluster.health-check.completed-checkpoints.window` then the operator considers it as unhealthy deployment and re-creates it.
* Added config `cluster.health-check.completed-checkpoints.enabled`
* Added config `cluster.health-check.completed-checkpoints.window`
* Added number of successful checkpoints watching
Changed/added automated tests + manually on …

[FLINK-30781] Add completed checkpoint check to cluster health check

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java

JIRA: https://issues.apache.org/jira/browse/FLINK-30669
This pull request fix an issue where incorrect job status is updated in FlinkDeployment resource.

[FLINK-30669] update recent job status in flinkdeployment object

---

examples/flink-beam-example/Dockerfile
examples/flink-beam-example/README.md
examples/flink-beam-example/beam-example.yaml
examples/flink-beam-example/pom.xml
pom.xml

Add beam application example for flink operator
Add beam application example for flink operator with a Word Count Beam application, dockerfile and an example flink deployment yaml.
This change is tested end to end on minikube
- If yes, how is the feature documented? (documented)

[FLINK-27831][example] add apache beam example for operator

---

docs/content/docs/operations/helm.md
helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

This pull request adds the possibility for helm chart users to specify resources block for operator pod on flink-webhook container.
Forgot to add this in previous PR... https://github.com/apache/flink-kubernetes-operator/pull/516
- Allow configuring resources block for operator pod flink-webhook container

[FLINK-30832] helm/flink-kubernetes-operator - allow specifying resources for operator pod on flink-webhook container

---

flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecorator.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesJobManagerParameters.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecoratorTest.java

* This Pull Request modified the Standalone JobManager CMD decorator to start the pods with their IP address instead of the k8s service. (https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/resource-providers/standalone/kubernetes/)
* This fixes the issue where Kubernetes HA doesn't work with standalone mode
- JobManager pods start with their IP Address when in standalone mode and K8s HA is enabled
Added unit tests and verified on EKS cluster
- If yes, how is the …

[FLINK-30518] Pass JM Pod IP to Flink when starting up with K8s HA 

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Record reconciled generation even if no Flink deployment took place in order to allow users to determine whether a given spec version has been reconciled or not.
Unit test added.

[FLINK-30858] Always record reconciled spec generation

---

Dockerfile

The main intention is the following:
* Fix the following JDK bug which is solved in `11.0.18`: [JDK-8221218](https://bugs.openjdk.org/browse/JDK-8221218)
* Migrate from OpenJDK which is announced to be deprecated [here](https://hub.docker.com/_/openjdk)
Compile docker images.

[FLINK-30594] Fix JDK-8221218 + change to eclipse-temurin due to openjdk deprecation

---

docs/content/docs/concepts/overview.md
docs/content/docs/custom-resource/job-management.md
flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsZookeeperHATest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecorator.java
flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesJobManagerParameters.java
pom.xml

https://issues.apache.org/jira/browse/FLINK-27273
This PR makes sure that Flink applications which use Zookeeper-based HA can be deployed via the Kubernetes Operator.
It wasn't previously possible mainly due to the lack of proper clean-up of Zookeeper data which could cause unexpected behaviour in Flink applications, as mentioned in the ticket.
- JobGraph-related data is now properly cleaned in Zookeeper (same behaviour as when using Kubernetes HA)
- All HA metadata is now properly cleaned when application is deleted or suspended in some cases (same behaviour as when using Kubernetes HA)
- Code has been updated to support both Kubernetes and Zookeper-based HA settings. All features which worked with Kubernetes HA (such as JM deployment recovery, unhealthy job restarts or rollbacks) should …

[FLINK-27273] Zookeeper HA support

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/artifact/HttpArtifactFetcher.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/artifact/ArtifactManagerTest.java

The HttpArtifactFetcher now only keeps the actual file name without the URI params as the file name. Previously the params were part of the resulting file name. This lead to problems submitting job files as Flink checks that the name of job files submitted end with ".jar".
- Filename determined from Job URIs do not contain URI-params anymore
This change is already covered by existing tests, such as *ArtifactManagerTest*.

[FLINK-30845] HttpArtifactFetcher: Fix filename

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
helm/flink-kubernetes-operator/conf/flink-conf.yaml

This pull request increases the default value of `kubernetes.operator.deployment.readiness.timeout` to 5 minutes from 1 minute.
Discussed with @gyfora that the current default value of 1 minute might be too short in many prod deployment scenarios.
- simply updated the current `kubernetes.operator.deployment.readiness.timeout` to 5 minutes.
This change is a trivial rework / code cleanup without any test coverage. -> quick config default value update.

[chore] increase the default ReadinessTimeout to 5 minutes

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/IngressUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/IngressUtilsTest.java

`networking.k8s.io/v1/Ingress` is not available in Kubernetes with version < 1.19 ( https://kubernetes.io/docs/reference/using-api/deprecation-guide/).
Instead, we can check the Kubernetes version and use `networking.k8s.io/v1/Ingress` or  `networking.k8s.io/v1beta1/Ingress`.
Reworked ingress creation depending on Kubernetes version.
This change is already covered by existing tests, such as *IngressUtilsTest*.

[FLINK-30825] Change Ingress to work with Kubernetes version < 1.19

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/lifecycle/ResourceLifecycleState.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/CommonStatus.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/ReconciliationStatus.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

*I had to remove the JsonIgnore annotation above the ResourceLifecycleState getter in CommonStatus and also I had to expose this as a printer column instead of the reconciliation status that is used currently.*
- *Remove the `@JsonIgnore` annotation above the `ResourceLifecycleState` getter*
- *Added a new private field to `CommonStatus` with `@PrinterColumn` annotation*
- *Remove the `@PrinterColumn` annotation above the `state` field within the `ReconciliationStatus` class*
1. Checkout this PR
2. And go through the quick-start guide
3. Finally use the `kubectl get flinkdeployments` command to check the results
*(OR)*
1. (After you checked out this PR) Build the flink-kubernetes-operator with `mvn clean install -Pgenerate-docs -DskipTests` command
2. Upgrade the `flinkdeployments` and …

[FLINK-30405] Add ResourceLifecycleStatus to CommonStatus and printer column

---

docs/content/docs/custom-resource/pod-template.md
e2e-tests/data/flinkdep-cr.yaml
e2e-tests/utils.sh
examples/pod-template.yaml

Since [e2e test](https://github.com/apache/flink-kubernetes-operator/actions/runs/3895555690/jobs/6662337363) is flaky with latest busybox image in init container, we [pinned](https://github.com/apache/flink-kubernetes-operator/commit/8e41ed5ec1adda9ae06bc0b6203abf42939fbf2b) the image version to a relatively old version. This pull request would like to enable e2e test print init container log and try to upgrade busybox version to the latest pinned version.
- Add log printing for init container if e2e test is failed.
- Upgrade the busybox version to the latest in a pinned way.
This change is already covered by existing tests, such as `e2e-tests/test_application_kubernetes_ha.sh`.
To reproduce the failed tests locally and test modified init container log printing code:
- Change the init …

[FLINK-30757] Upgrade busybox version to a pinned version for operator

---

docs/content/docs/operations/metrics-logging.md

Using the reporter class directly is not supported anymore with Flink 1.16.

[docs] Use Prometheus factory class in metric reporter examples

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java

- This pull request adds a new config parameter to exclude vertex ids for autoscaler to ignore for scaling
- Changes in ScalingExecutor `computeScalingSummary` method and adds config parameter in AutoScalerOptions
- Dependencies (does it add or upgrade a dependency): *no*
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: *no*
- Core observer or reconciler logic that is regularly executed: *yes*
- Does this pull request introduce a new feature? *yes*
- Update docs/layouts/shortcodes/generated/auto_scaler_configuration.html

[FLINK-30920] [AutoScaler] adds exclude vertex ids for autoscaler to ignore for evaluation and scaling

---

flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecorator.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecoratorTest.java

Standalone mode with HA enabled will call the JobManager entrypoint with a `--host` argument, but in case there are any dynamic properties in `JobSpec.args`, this will only be added after those, and thus will be ignored by the JobManager.
- Move `--host` to be added before `JobSpec.args` in `CmdStandaloneJobManagerDecorator.java`
- Corresponding unit test changed
- Manually tested in local environment
- Dependencies (does it add or upgrade a dependency): (yes / no) no
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no) no
- Core observer or reconciler logic that is regularly executed: (yes / no) no
- Does this pull request introduce a new feature? (yes / no) no …

[FLINK-31187] Fix standalone HA JobManager --host argument order

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java

The current JM Deployment logic that restarts missing deployments strictly requires HA metadata event for stateless deployments.
This is inconsistent with how the cluster health check related restarts work which can cause the operator to delete an unhealthy deployment and potentially leave it missing if the first deploy attempt fails.
- Allow JM deployment recovery for stateless jobs
- Require HA meta based on the HA config
- Add hotfix for missing wait for cluster shutdown 
Extended deployment recovery test to cover the stateless case.
- …

[FLINK-31277] Fix deployment recovery logic HA meta check

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/DiffBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/DiffResult.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/ReflectiveDiffBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/diff/SpecDiffTest.java

Currently the Spec Change message contains the full PodTemplate twice.
This makes the message seriously big and also contains very little useful information.
We should abbreviate the message
- When we found different pod templates, we just print `before` and `after` instead of printing out the pod template itself
*(example:)*
- *Added unit test verifying the text*

[FLINK-31246] Beautify the SpecChange message

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java

The Kafka pendingRecords metric is only initialized on receiving the first record. For empty topics or checkpointed topics without any incoming data, the metric won't appear.
We need to handle this case in the autoscaler and allow downscaling.

[FLINK-31299] PendingRecords metric might not be available

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluator.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetric.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScalerTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluatorTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetricsTest.java

When catching up (processing backlog) the best thing for the autoscaler is to remain stable as long as the job can keep up with the required / target data rate.
Currently however it can be possible that the operator would trigger the scale down some underutilized vertices triggering a restart and even more backlog, putting the job in a vicious cycle.
Also it would not make sense to scale vertices even further for minimal utilization gains if the current parallelism is enough to process the backlog in a timely manner.
- *Compute CURRENT_PROCESS_RATE metric for sources and use it together with LAG to detect the backlog processing state*
- *Set the scale down utilization threshold to 0% and scale up to 100% to avoid triggering unnecessary scaling actions*
New unit tests added.
- Dependencies …

[FLINK-31318] Improve stability during backlog processing

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerInfo.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluator.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/EvaluatedScalingMetric.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerInfoTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator-autoscaler/src/test/resources/log4j2-test.properties

Compresses (GZip) the autoscaler info (metrics and scaling history) before storing in the configmap to greately reduce the size and allow keeping longer histories without reaching the 1MB limit.
We also introduce a 3 decimal place rounding for metrics to further reduce size and make the reported metrics nicer.
Change is covered by existing tests.

[FLINK-31345] Reduce AutoScalerInfo size by rounding metrics and compression

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
examples/autoscaling/autoscaling.yaml
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluator.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/MetricAggregator.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetricsTest.java

Previous changes removed the requirement for sources to have the `pendingRecords` metric. This allows to refactor and consolidate the source scaling code. We remove the option to disable scaling sources because the primary motivation was to skip scaling legacy sources which we can achieve without an extra configuration option. 
The refactored source scaling logic works like this:
* Modern sources (busy time available)
Scale source based on the busy time up. Add extra capacity if the lag
information, provided by the pending records metric, is available. Otherwise
assume 0 lag. Cap by the maximum number of partitions, if available.
* Legacy sources (busy time unavailable)
Leave the source parallelism unchanged, use the current processing rate as the
target rate downstream.

[FLINK-31326] Consolidate source scaling logic

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetricsTest.java

When the rates drop to zero, we set near zero values to continue to use the same scaling logic. There is a gap in this logic when only the input rate drops to zero but the output rate is still measured to be greater than zero. This is because we do not pass on the output rates directly but the output / input ratio which becomes very large in this special scenario.
In this change we cap the output rate in case we use near zero input rates. This has been tested to effectively prevent scale up spikes in pipelines which only occasionally receive data.

[FLINK-30575] Limit output ratio in case of near zero values

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_advanced_section.html
examples/canary.yaml
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/FlinkDeployment.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/FlinkSessionJob.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/CanaryResourceManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/HealthProbe.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkSessionJobController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/health/HealthProbeTest.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkValidator.java

While the current health probe mechanism is able to detect different types of errors like startup / informer issues it can be generally beneficial to allow a simply canary mechanism that can verify that the operator recieives updates and reconciles resources in a timely manner.
This PR introduces a simple canary mechanism that allows platform admins/users to deploy simple canary resources identified by a special label. The canary resource reconciliation logic then feeds into the Health probe through a configurable timeout which will be able to detect if the operator did not reconcile the resource.
The canary resource won't deploy any Flink resources. 
- *Add canary resource logic and canary resource manager to handle timeouts*
- *Wire canary logic into HealthProbe*
- *Add unit tests* …

[FLINK-31219] Add support for canary resources

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

Allow users to select the pod template merging strategy for object arrays.
Currently we use a strictly position based merge strategy which can be difficult to use when defining multiple levels of pod templates.
With the new name based optional merge strategy, object arrays containing the name fields would be merged by the name instead of position.
Unit tests extended, manual and cluster tests.

[FLINK-30786] Support merge by name for podTemplate array fields

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/HealthProbe.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/InformerHealthSummary.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/InformerIdentifier.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/health/HealthProbeTest.java

The current healthprobe will report unhealthy if any informers cannot start. This is in contradiction with the setting that can allow the operator to start while some informers are unhealthy (and keep trying to start them)
- *Add fine grained informer health check to probe*
New unittests added to HealthProbeTest, tested on local and cloud envs.

[FLINK-31218] Improve health probe to only detect newly unhealthy informers

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_advanced_section.html
e2e-tests/test_application_operations.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java

Currently we use the default (background) deletion propagation when we delete Kubernetes resources such as the JobManager deployment.
In most cases this is acceptable however this can lead to lingering resources when the garbage collection is slow on the k8s cluster. We therefore propose to make this configurable and also change the default to Foreground which is more predictable and works better for our purposes in the operator.
- *Change default resource deletion to foreground propagation*
- *Make it configurable*
- *Add tests*
Added unit test to NativeFlinkServiceTest
- Does this pull …

[FLINK-31592] Improve Flink dependent resource deletion

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

This pr adds priorityClassName to operator pod.
PR is simple and self-descriptive.

[FLINK-31680] Add priorityClassName to flink-operator's pods

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/Savepoint.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/CheckpointHistoryWrapper.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

Introduce config to block last-state upgrades if the checkpoint is too old and either wait for pending checkpoint completion or use savepoints instead.
When the max-age checkpoint age is configured we will do the following if the last completed checkpoint/savepoint is older:
- If there is any pending checkpoint triggered within the max-age, we wait for it to complete
- If the job started within max-age we use last-state restart
- If no pending checkpoint and the job wasn't started recently, we fall back to savepoint upgrade mode.
We also introduce a validation to only allow the max-age config if savepoint dir is set.
As a followup improvement we could consider triggering chekpoint instead of savepoint for Flink 1.17 in the future.
- *Introduce new logic in available upgrade mode method*
- …

[FLINK-31630] Limit max checkpoint age for last-state upgrade

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

- *Exposed JobManager and TaskManager resource usage to clusterInfo in status of the CR*
- *The clusterInfo is then used to populate the metrics for the FlinkDeployment*
Manually verified via submitting applications to a local cluster. TODO to add suitable unit tests, ideally extending `FlinkDeploymentMetricsTest` however given my reliance on the status of the CR this is more involved than ideal.

[FLINK-31303] Expose Flink application resource usage via metrics and status

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetricsTest.java

This fixes an unreleased bug which would clear user-set vertex exclusions from the config for non-legacy sources.

[FLINK-30920] Prevent clearing any manually defined vertex exclusions

---

docs/content/docs/custom-resource/reference.md
examples/kubernetes-client-examples/src/main/java/org/apache/flink/examples/Basic.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/CrdConstants.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/Resource.java
flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/utils/BaseTestUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorITCase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml

Add ephemeral storage to CRD, so that users can apply ephemeral storage as resource requirement to containers of JM and TM.
- Add ephemeral storage to Resource of flink deployment spec
- Changes are tested in unit test in FlinkConfigBuilderTest
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes)
- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (not documented)

[FLINK-30609] Add ephemeral storage to CRD

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerInfo.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerInfoTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/TestingMetricsCollector.java

The autoscaler uses a ConfigMap to store past metric observations which is used to re-initialize the autoscaler state in case of failures or upgrades.
Whenever trimming of the ConfigMap occurs, we need to make sure we also update the timestamp for the start of the metric collection, so any removed observations can be compensated with by collecting new ones. If we don't do this, the metric window will effectively shrink due to removing observations.
This can lead to triggering scaling decisions when the operator gets redeployed due to the removed items.
The solution we are opting here is to treat the first metric observation timestamp as the start of the metric collection.

[FLINK-31866] Start metric window with timestamp of first observation

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoscalerFactoryImpl.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java

Currently when there is an error in the atuoscaler logic due to some misconfiguration / invalid metrics etc we only log the problem in the operator side but don't show this to the user. From the user's perspective the autoscaler simply doesnt do anything in these cases if they dont have access to the operator logs.
This PR triggers a CR event in case an error happens in the autoscaler logic.
- Add error when exception happens
- Add test
new unit test added

[FLINK-31885] Trigger event on autoscaler error

---

flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
flink-kubernetes-standalone/pom.xml
pom.xml

Eliminates a vulnerability related to snakeyaml 1.33 by bumping the jackson version.
- Bump version
- Update NOTICE
Change covered by CI and e2es

[FLINK-31815] Bump jackson version to eliminate snakeyaml vulnerability

---

flink-kubernetes-operator-api/pom.xml

Update the CRD compatibility check to reference the most recent stable version and remove older versions from the check as the checks should be transitive.

[hotfix] Update CRD compat check to 1.4.0

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java

The goal is to make the make the out-of-the-box experience as smooth as possible. Hence, the defaults are adjusted to have a larger metric window, wider bounds for scaling up and down, less quick downscaling, and a maximum parallelism of 200.

[FLINK-32002] Adjust autoscaler defaults for release

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScaler.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScalerTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java

Support setting scale up max factor for autoscaler.
- Add new option _kubernetes.operator.job.autoscaler.scale-up.max-factor_ for setting scale up max factor.
- Cap scale factor in `JobVertexScaler#computeScaleTargetParallelism` by max scale-up factor.
- Record capped target processing rate instead as the expected processing rate in `JobVertexScaler#computeScaleTargetParallelism`.
- Adapt UTs accordingly.
- Extended existing unit test
- If yes, how is the feature documented? auto-generated doc

[FLINK-31936] Support setting scale up max factor

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoscalerFlinkMetrics.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImplTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkResourceContextFactory.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkResourceContextFactory.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java

If any of the autoscaled deployment produce errors they are only visible in the logs or in the k8s events. Additionally, it would be good to have metrics to detect any potential issues.

[FLINK-32005] Add a per-deployment error metric to signal about potential issues

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java

Recent changes broke the podTemplate configuration logic when no pod template or ephemeral storage is configured resulting in an invalid null object serialized and set.
- Fix invalid logic
- Add unit test
New unit test case has been added.

[FLINK-32067] Do not configure invalid null podTemplate

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScalerTest.java

Some further minor improvements to the autoscaler default config: 
- Turn off ineffective scaling detection by default as it probed to be a little unstable
- Set a large (but not too large) number for max scale up factor to improve the doc

[FLINK-32002] Autoscaler default config improvements

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java

So far, we've taken the max number partitions we can find. However, the correct way to calculate the max source parallelism would be to sum the number of partitions of all topis.

[FLINK-32100] Use the total number of Kafka partitions as the max source parallelism

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/RestApiMetricsCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/FlinkMetric.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/RestApiMetricsCollectorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java

Some source expose multiple `.pendingRecords` metrics. If that is the case, we must sum up these records to yield the correct internal pending records count.

[FLINK-32102] Aggregate multiple pendingRecords metric per source if present

---

docs/content/docs/operations/plugins.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/CheckpointHistoryWrapper.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java

Fix NPE while getting in progress checkpoints.
- Add null check CheckpointHistoryWrapper#getInProgressCheckpoint
- Added 2 Unitests to verify NPE is not thrown when calling getInProgressCheckpoint when history obj is null.
- Dependencies (does it add or upgrade a dependency): (yes / no) no
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no) no
- Core observer or reconciler logic that is regularly executed: (yes / no) no
- Does this pull request introduce a new feature? (yes / no) no

[FLINK-32111] - Add Null  check for checkpoints history obj

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScaler.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScalerTest.java

Currently the min/max parallelism configs for the autoscaler are handled strictly and they can potentially override the user defined current parallelism. This is incorrect and the limits should be adjusted by the current parallelism
New unit test cases added.

[FLINK-32134] Autoscaler min/max parallelism configs should respect current parallelism

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/CollectedMetricHistory.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java

The metrics get reported only after the metric window is full. This is not helpful for observability after rescaling. We need to make sure that metrics are reported even when the metric window is not yet full.

[FLINK-31684] Report autoscaling metrics before metric window is full

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScaler.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java

Reduce logging noise from the operator by changing the log level to debug in many cases. Currently the operator is very noisy and outputs a lot of redundant / usless logs during normal operations.
Tested locally.

[FLINK-32148] Make operator logging less noisy

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java

The operator currently always uses the event message content to generate the event name/uid. This is good in most cases and does not lead to duplicate events but in case of the scaling reports we include metrics in the event message that change all the time.
- *Introduce mechanism to replace message with key for event recorder*
- *Add tests*
- *Use dedicated key for scaling report events*
New unit tests have been added.

[FLINK-32147] Deduplicate scaling report messages

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml

mountPath repeats when operatorVolumeMounts persistence is turned on.
when operatorVolumeMounts turned on, mountPath conflict with flink-operator.yaml  flink-artifacts-volume, flink-artifacts-volume emptyDir No need.
**values.yaml config**
```yaml
operatorVolumeMounts:
create: true
data:
- name: flink-artifacts
mountPath: /opt/flink/artifacts  #  when true , mountPath conflict with flink-operator.yaml  flink-artifacts-volume.
operatorVolumes:
create: true
data:
- name: flink-artifacts
persistentVolumeClaim:
claimName: flink-artifacts-pvc
```

fix : enable operatorVolumeMounts mountPath repeat

---

helm/flink-kubernetes-operator/templates/rbac.yaml

The operator doesn't have the ability to manage leases in its own namespace when using `watchNamespaces`. This fixes that by adding a `Role` and `RoleBinding` for it when `watchNamespaces` is set.
- Add Role and RoleBinding for the operator in release namespace when using namespace-scoped RBAC
- Remove the ability to create leases from `watchNamespaces` when using namespace-scoped RBAC
This change is a trivial rework / code cleanup without any test coverage. We do, however, currently have this change [deployed](https://github.com/wikimedia/operations-deployment-charts/commit/e06d57b5bdf06f827e4e1ca081320aee4cc82cb0) in our production setup
- Core observer …

[FLINK-32041] - Allow operator to manage leases when using watchNamespaces

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java

Fix a minor issue that happens during evaluating empty metrics during stabilization:
```
023-06-08 09:32:11,288 o.a.f.k.o.a.ScalingMetricCollector [INFO ][default/autoscaling-example] Job updated. Clearing metrics.
2023-06-08 09:32:11,288 o.a.f.k.o.a.ScalingMetricCollector [INFO ][default/autoscaling-example] Skipping metric collection during stabilization period until 2023-06-08T09:32:24.840Z
2023-06-08 09:32:11,288 o.a.f.k.o.a.JobAutoScalerImpl  [ERROR][default/autoscaling-example] Error while scaling resource
java.util.NoSuchElementException
at java.base/java.util.TreeMap.key(TreeMap.java:1324)
at java.base/java.util.TreeMap.lastKey(TreeMap.java:296)
at java.base/java.util.Collections$UnmodifiableSortedMap.lastKey(Collections.java:1810)
at …
```

[hotfix] Fix evaluation error during stabilization period

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollectorTest.java

Minor fix for the Flink 1.17 client upgrade that corrects a change in behaviour of the JobDetailsInfo access that the autoscaler relies on.
Unit test added
- If yes, how is the feature documented? no

[hotfix] Fix JobDetailsInfo json extraction for 1.17

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoscalerFlinkMetrics.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluator.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetric.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/RecommendedParallelismTest.java

It is beneficial to report the recommended parallelism and overlay it with the current parallelism on the same chart when auto scaler is running in advisor mode.
- Added a new `RECOMMENDED_PARALLELISM` entry to `ScalingMetric`
- And the latest recommended parallelisms are now being reported as evaluated scaling metric
- Recommended parallelisms follow the logic below:
- On job start all scaling metrics are registered to null until the job is in RUNNING state
- `RECOMMENDED_PARALLELISM` will be kept `null` while the metric window is filling up
- `RECOMMENDED_PARALLELISM` will be populated only after the metric window is full
-  `RECOMMENDED_PARALLELISM` will pick up the PARALLELISM value by default
-  `RECOMMENDED_PARALLELISM` on each vertex can be updated according to the calculated …

[FLINK-32271] Report RECOMMENDED_PARALLELISM as an autoscaler metric V2

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluator.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetric.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluatorTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetricsTest.java

LOAD can be used to identify the busiest vertices in a job graph, hence it's useful to have it as a metric. 
- Removing the seemingly obsolete? `LOAD_MAX` and `LOAD_AVG` scaling metrics
- Storing the `busyTimeMsPerSecond`  Flink metric as `LOAD` instead as an  EvaluatedScalingMetrics. 
The auto scaler logic is using the `MetricAggregator.(MIN,MAX,AVG)` config option to determine with value to be used from the `busyTimeMsPerSecond` aggregates when calculating various rates for a given vertex. The same logic is reused when calculating the `LOAD` values.
This change is already covered by existing tests, some extra test data and assertions where added
- Manually by looking at the reported metrics:
```
AutoScaler.jobVertexID.90bea66de1c231edf33913ecd54406c1.LOAD.Average: 0.954 …
```

[FLINK-32272] Expose LOAD as autoscaler metric

---

docs/content/docs/operations/helm.md

`syncOptions` field should reside under `.spec.syncPolicy`
- Does this pull request introduce a new feature? (yes / no)
no

 [hotfix][docs] Fix ArgoCD CRDs application

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/FlinkSessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

Instead of using Java's hashCode, which is an integer value (32bit), a long representation of the uid is used. This decreases the chance for an ID collision drastically:
For a 50% collision chance with random integers, 77000 numbers need to be generated. For a long value (64 bit) a 50% change of a collision needs 5.1×10^9 random longs. For details look up: "the birthday problem".
A test is added to increase awareness of the problem when changing this part of the code.
Lower the chance of JobID collisions in session job deployments.
- *Increase the lower part of the JobID to use the 64 most significant bits of the ressources uid instead of the 32 bit hashCode of the uid*
- *Added unit test*
- *Adapted existing tests*
- *Manually tested the upgrade of the operator when having a job deployed …

[FLINK-32412] Reduce JobID collision chance

---

flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/validation/CrdCompatibilityChecker.java
flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/validation/CrdCompatibilityCheckerTest.java

Fix build failure on windows via `mvn clean package -DskipTests`.
- Modify  method `getSchema` in `CrdCompatibilityChecker`.
- Added unit test to verify CrdCompatibilityCheckerTest.
- Core observer or reconciler logic that is regularly executed: (yes )

[FLINK-32527] Fix build failure on windows

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

There are certain cases where the JM enters a startup crash loop for example due to incorrect HA config setup. With the current operator logic these cases require manual user intervention as we don't have HA metadata available for the last checkpoint and it also seems like the JM actually started already.
To solve this properly we suggest adding a default JM startup probe that queries the rest api (/config) endpoint. This simple mechanism allows us to piggyback on the existing mechanism that allows the operator to simply delete the JM deployment when it never successfully started.
- *Add configurable startup probe for JM deployments to detect failed start*
- *Unit tests for startup probe config*
Unit tests + manual tests
- The …

[FLINK-32529] Add startup probe for JM deployment

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/FlinkMetric.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/topology/JobTopology.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/topology/VertexInfo.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/utils/AutoScalerUtils.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobTopologyTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollectorTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/utils/AutoScalerUtilsTest.java

Improve the autoscaler metric collection logic to be aware of finished vertices and do not collect metrics from them. Simplify topology handling. 
For finished metrics we use hardcoded metrics that show 0 incoming data / lag etc in order to allow downstream operators to be scaled accordingly even if they have other inputs.
- *Add finished flag to VertexInfo*
- *Exclude finished vertices from scaling metric collection*
- *Simplify topology and metric name collection*
- *Unit test*
New unit tests 
- If yes, how is the feature documented? …

[FLINK-32572] Do not collect metrics for finished vertices

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkResourceExceptionUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkResourceExceptionUtilsTest.java
helm/flink-kubernetes-operator/conf/flink-conf.yaml

CR Error field is improved in https://issues.apache.org/jira/browse/FLINK-29708.
The error field is more structured with exception type, stackTrace, additionalMetadata, etc.
This ticket is a proposal to expose a config ("kubernetes.operator.exception.metadata.mapper") to enrich the additionalMetadata further.
The config consists of key-value pairs, for example:
```
kubernetes.operator.exception.metadata.mapper: IOException:Found IOException,403:Found 403 error code
```
The key is a REGEX string that will be used to match against the whole stack trace and if found, the value will be added to additionalMetadata. For example:
```
apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
....
name: basic-session-job-example
namespace: default
resourceVersion: "70206149"
uid: …
```

[FLINK-32317] Enrich metadata in CR error field

---

flink-kubernetes-webhook/pom.xml
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandler.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkValidator.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/mutator/DefaultRequestMutator.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/mutator/FlinkMutator.java
flink-kubernetes-webhook/src/main/resources/META-INF/NOTICE
flink-kubernetes-webhook/src/test/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandlerTest.java
pom.xml

Replace the deprecated admission controller framework with the equivalent web hook library
- Replace maven dependency / imports
No new functionality added, covered by existing tests

[FLINK-32282] Migrate to webhook framework

---

helm/flink-kubernetes-operator/templates/rbac.yaml

Adds `deployments/scale` to RBAC rules so the operator can scale deployments with the /scale API
- Add new RBAC rule
Manually tested after editing ClusterRole `flink-operator` by hand

[FLINK-32652] Add deployments/scale to RBAC rules

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ReconcilerFactory.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/OperatorTestBase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkSessionJobController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/FlinkSessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java

Add an operator option to make savepoint on FlinkDeployment/FlinkSessionJob deletion. Default behaviour is not changed and no savepoint are being made.
Rework of the https://github.com/apache/flink-kubernetes-operator/pull/627. Since current contributor is OOO, made another PR.
- Adds a new operator configuration
- Inject the Operator config to all reconcilers upon creation
- Factorise cleanUp job interface to unify Upgrade mode determination upon cleanup
- Added unit test to the new cleanup behaviour
- Additional unit tests
- Manual tests on K8s
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: yes, Adds a new operator configuration
- Does …

[FLINK-32551] Add option to take a savepoint when deleting a flinkdeployment/flinksessionjob

---

docs/content/docs/custom-resource/job-management.md

Update documentation of the rollback features. 
Flink devs who is not aware about internals of the operator's CRDs is not obvious why rollbacks of incompatible Helm chart changes will not lead to the job running.
Documentation of the corner case to reduce miss-understanding of the roll back feature behaviour

Update doc to ensure that users keep in mind how rollback feature works

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoscalerFlinkMetrics.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerFlinkMetricsTest.java

Change null values to Double.NAN for autoscaler metrics during blackout periods when no data is gathered. This appears to be a more common practice then null. Also consistent with other metrics we have.
This is a minor fix in `AutoscalerFlinkMetrics`
Manually + Unit tests
```
resource.default.autoscaling-example.FlinkDeployment.AutoScaler.jobVertexID.cbc357ccb763df2852fee8c4fc7d55f2.RECOMMENDED_PARALLELISM.Current: NaN
resource.default.autoscaling-example.FlinkDeployment.AutoScaler.jobVertexID.90bea66de1c231edf33913ecd54406c1.RECOMMENDED_PARALLELISM.Current: NaN
resource.default.autoscaling-example.FlinkDeployment.AutoScaler.jobVertexID.cbc357ccb763df2852fee8c4fc7d55f2.MAX_PARALLELISM.Current: NaN
resource.default.autoscaling-example.FlinkDeployment.AutoScaler.jobVertexID.90bea66de1c231edf …
```

[FLINK-32690] report Double.NAN instead of null for missing autoscaler metrics

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/OperatorTestBase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Fix some corner cases introduced by the combination of the observe already upgraded checks and autoscaler parallelism override logic that may cause stuck upgrades. 
- *Fix already upgraded observe logic to ignore deployments that are pending deletion*
- *Do not run check already upgraded logic in the middle of savepoint upgrades*
- *Add unit tests*
New unit test added and manually verified.

[FLINK-32774] Improve checking for already upgraded deployments

---

e2e-tests/data/autoscaler.yaml
e2e-tests/test_autoscaler.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/OperatorTestBase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

*(or)*
*(or)*
*(example:)*
- *Extended integration test for …

[backport][FLINK-32774] Improve checking for already upgraded deployments

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/LifecycleMetrics.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetricsTest.java

The per namespace lifecycle state count metrics are incorrectly show a global count at [LifecycleMetrics.java#L145](https://github.com/apache/flink-kubernetes-operator/blob/main/flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/LifecycleMetrics.java#L145). LifecycleState count metrics should be reported by namespace.
- Corrects the LifecycleState count metrics of per namespace for `LifecycleMetrics`.
- Updates `FlinkDeploymentMetricsTest#testMetricsMultiNamespace` to verify the LifecycleState count metrics of per namespace.
- Core observer or reconciler logic that is regularly executed: …

[FLINK-32164] LifecycleState count metrics are not reported correctly by namespace

---

examples/flink-sql-runner-example/src/main/java/org/apache/flink/examples/SqlRunner.java

Fixing bug in Flink SQL Runner example preventing the user to provide a PEM certificate.
Changes in the sample code to avoid removing the BEGIN/END from PEM certificates.
This change can be verified as follows (for Kafka) when having ssl enabled in Kafka.
- In https://github.com/apache/flink-kubernetes-operator/blob/main/examples/flink-sql-runner-example/sql-scripts/statement-set.sql you should have the property `properties.ssl.truststore.certificates`
**Example**
```
WITH (
'connector' = 'kafka',
...
'properties.ssl.truststore.certificates' = '-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
'
);
```
- Deploy and check that there is no error to create the Kafka producer/consumer.
- Dependencies (does it add or upgrade a dependency): (yes / no) **no**
- The public API, i.e., is …

[FLINK-32773] Support PEM certificates in the SQL Runner example

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsZookeeperHATest.java

* This pull request correct the path used to check if HA metadata are available in zookeeper. Previous path check was leading to operator taking action based on availability of those metadata while the jobs one were not available see https://issues.apache.org/jira/browse/FLINK-32890 for some case leading to bad action
- Correct HA patch check for zookeeper metadata store
This change is already covered by existing tests, such as `FlinkUtilsZookeeperHATest.zookeeperHaMetaDataCheckTest`.
- If …

[FLINK-32890] Correct HA patch check for zookeeper metadata store

---

examples/autoscaling/autoscaling-canary.yaml
examples/autoscaling/autoscaling-dynamic.yaml
examples/autoscaling/src/main/java/autoscaling/LoadSimulationPipeline.java

The current provided example pipeline generates an infinite amount of load, only yielding only scaleup decisions. It would be desirable to have a pipeline which scales up and down in a periodic fashion. Users do not always have enough data available to do that. Hence, the load needs to be simulated.
The pipeline has been tested and proven to yield very accurate load numbers.

[FLINK-32903] Add a load simulation example pipeline for canary testing

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SnapshotObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtilsTest.java

Current functionality to trigger savepoints and checkpoints is based on specifying a fixed interval. This approach gives little control to prevent potentially overlapping snapshots running simultaneously in adjacent deployments and can cause issues for high scale, large state jobs. Moreover, lastTrigger information is not retained across deployment restarts which leads to immediate firing based on creation time. In order to have better control over the exact schedule, triggering based on cron expressions should be added.
- Adds cron expression config options for checkpoint and savepoint triggering
- Extends SnapshotUtils logic to process both interval- and cron-based triggers
-  Added unit and integration tests
- The …

[FLINK-32904] Support cron expressions for periodic snapshots triggering

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java

* This PR add capability to configure kubernetes.operator.job.savepoint-on-deletion on a per-resource level
- Add capability to configure kubernetes.operator.job.savepoint-on-deletion on a per-resource level
This change added tests: `SessionJobReconcilerTest.testSubmitAndCleanUpWithSavepointOnResource` and `ApplicationReconcilerTest.testSubmitAndCleanUpWithSavepointOnResource` added
- Does this pull request introduce a new feature? no, the feature already exist and is already documented as a per-resource level configuration

[FLINK-32973] Add capability to configure kubernetes.operator.job.savepoint-on-deletion on a per-resource level

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java

This pull request adds an option called `kubernetes.operator.job.drain-on-savepoint-deletion` to indicate whether a job should be drained before deleting a FlinkDeployment or FlinkSessionJob, only if savepoint on deletion is enabled.
- Add new configurable option to drain a job before deletion, if the savepoint on deletion is enabled
- Added unit tests with the new configuration option enabled `testSubmitAndDrainOnCleanUpWithSavepoint` in `ApplicationReconcilerTest` and `SessionJobReconcilerTest`
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: yes
- Does this pull request introduce a …

[FLINK-32700] Support job drain for Savepoint upgrade mode

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImplTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/JobAutoScaler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/NoopJobAutoscalerFactory.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

1. Move parallelism override application to JobAutoscaler instead of reconciler to not leak autoscaler logic
2. Allow users to override excluded vertex parallelisms to avoid the corner case where excluded vertex parallelisms are stuck
Improved and extended unit test coverage

[FLINK-33027] Allow users to override parallelism of excluded vertices

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_section.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfigurationTest.java

There are certain cases currently when the operator can stuck in an infinite no wait retry loop under certain circumstances (see https://github.com/operator-framework/java-operator-sdk/issues/2046 for details).
As a solution we introduce rate limiter configuration with a default that should already safeguard against prod problems that may arise without it.
The PR also fixes and improves the default retry configuration and fixes a bug with exponential backoff.
- *Expose rate limiter config and enable by default*
- *Update default retry config*
- *Unit Tests*
Unit tests, manual verification …

[FLINK-33067] Expose rate limiter config and enable by default

---

docs/content/docs/operations/configuration.md

Add doc for run Flink Operator in IPV6 env
Add config needed as a workaround for supporting IPV6 env
Only documentation change. 
- If yes, how is the feature documented? (docs)

[FLINK-32777] add doc for supporting IPV6 env

---

flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImpl.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/BacklogBasedScalingTest.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScalerImplTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/JobAutoScaler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/NoopJobAutoscalerFactory.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Simplify the scale / parallelism override flow based on previous feedback. This change is a refactor and does not introduce new behaviour.
- *Unify scale / applyParallelismOverride methods*
- *Move scaling before reconciling spec diffs*
- *Refactor JobAutoscalerImpl and extract some methods to simplify the core flow*

[FLINK-33081] Apply parallelism overrides in scale

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java

`ClusterInfo` fetch error can happen in normal situation which can show temporary issues so I've lowered the log level from error to warning.
`ClusterInfo` fetch error level to warning
Trivial change.

[FLINK-33105] Log ClusterInfo fetch error as warning

---

e2e-tests/data/flinkdep-cr.yaml
e2e-tests/data/sessionjob-cr.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

JM and TM memory settings is only supported in bibytes format. This change will help interpreting the flink memory according to the actual user input.
- Added the implementation 
- Added tests
Example values for the change
The below table property applies for the 
- jobManager.resource.memory
- taskManager.resource.memory
| Configuration | Previous InterpretedValue 			| New InterpretedValue 	|
|---------------|---------------------------------------|-----------------------|
| 2g …

[FLINK-31871] Interpret Flink MemoryUnits according to the actual user input

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/config/AutoScalerOptions.java
flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutorTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java

https://issues.apache.org/jira/browse/FLINK-33187
Suppress duplicate event for scaling report within the interval defined by a new operator config "scaling.report.interval" in second, defaulted to 1800.
- Add a new method in EventUtil to suppress duplicate event within an interval.
- Suppress duplicate event for scaling report within the interval defined by a new operator config "scaling.report.interval" in second, defaulted to 1800.
- manually verify by reading records
- Core observer or reconciler logic that is regularly executed: No
- Does this pull request introduce a new feature? No
- If yes, how …

[FLINK-33187] Don't record duplicate event if no change

---

e2e-tests/data/autoscaler.yaml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

*Currently the AutoScaler configurations are not validated, hence they fail at runtime. This change intends to introduce a validator plugin for validating AutoScaler configuration*
- *AutoScaler Validator implemented using FlinkResourceValidator plugin*
- *Unit tests added for the same, please find below details of all the rules being validated*
- *Added the META-INF/services file for the validator to pick the right autoscaler plugin while available in classpath*
- *Added Unit tests to cover all the rules validated on the autoscaler configuration.*
- *Extended e2e-tests to make sure the AutoScaler validator plugin is picked and validated on the tests*
- *Manually verified the change by running a test on the operator with a …

[FLINK-33007] Integrate autoscaler config validation into the general validator flow

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/AutoScalerEventHandler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/FlinkMetric.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingMetric.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingMetrics.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/realizer/ScalingRealizer.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/AutoScalerStateStore.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/InMemoryAutoScalerStateStore.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RestApiMetricsCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/metrics/ScalingMetricsTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoscalerFactory.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ConfigMapStore.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesAutoScalerStateStore.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesAutoScalerStateStoreTest.java

The aim of this PR is to address the cases when operator incorrectly reports low busy time (high idleness) for sources that are in fact cannot keep up due to the slowness of the reader/fetchers. As the metrics cannot be generally fixed on the Flink - connector side we have to detect this and handle it when collecting the metrics.
The main symptom of this problem is overestimation of the true processing rate and not triggering scaling even if lag is building up as the autoscaler thinks it will be able to keep up.
To tackle this we differentiate two different methods of TPR measurement:
1. **Busy-time based TPR** (this is the current approach in the autoscaler) : computed from incoming records and busy time 
2. **Observed TPR** : computed from incoming records and back pressure, measurable …

[FLINK-33306] Use observed source throughput as true processing rate

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/AutoScalerEventHandler.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/event/TestingEventCollector.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesAutoScalerEventHandler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesAutoScalerEventHandlerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java

This is to implement the scaling report comparison algorithm for event suppression by using hashcodes of the parallelism maps. Originally I used the full string of report message which contains the metrics fluctuating with current load. As long as parallelism map doesn't change, we don't need to generate new events within the defined interval.
- Save hashcode of the parallelism map to metadata labels
- Use the hashcode to compare two scaling report for advice
- Updated and added unit tests.
- Verified in integration test env.
- Core observer or reconciler logic that is regularly executed: No
- Does this pull request introduce a new feature? No
- If yes, …

[FLINK-33187] using hashcode for parallelism map comparison

---

flink-autoscaler/README.md

This adds a README to the flink-autoscaler module, to clarify its purpose and usage.

[docs] Add a README to the flink-autoscaler module

---

docs/config.toml

Note: it can be merged after 1.6.1 is released.
Update the doc version to 1.6.1

[release] Update the doc version to 1.6.1

---

.github/workflows/ci.yml
docs/content/docs/concepts/overview.md
docs/content/docs/custom-resource/reference.md
examples/autoscaling/Dockerfile
examples/basic-checkpoint-ha.yaml
flink-kubernetes-operator-api/pom.xml
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/FlinkVersion.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/ValidatorUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml

Based on community agreement we drop support for 1.13/1.14 to allow the removal of specific (deprecated) codepaths and reduce CI time overall.
With this we introduce an explicit check and short-circuit exit on unsupported versions.
- *Remove 1.13/1.14 specific codepaths and tests*
- *Short-circuit the controller loop on unsupported versions and trigger user event*
- *New unit test*
New unit tests added, manual verification
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: yes
- If yes, how is the feature documented? [TODO]

[FLINK-33089] Drop support for Flink 1.13 and 1.14 and clean up related codepaths

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java

Fixes a bug where vertices with 0 busy time and low incoming records wouldn't be scaled down due to TPR computed as NAN instead of Infinity.
Unit test added

[FLINK-33306] Always use busy tpr when observed is nan

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/exceptions/NotReadyException.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/exceptions/RecoverableException.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/MetricNotFoundException.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricCollectorTest.java

The new code for the 1.7.0 release introduces metric collection during the stabilization phase to allow sampling the observed true processing rate. Metrics might not be fully initialized during that phase, as evident through the error metrics. The following error is thrown:
```
java.lang.RuntimeException: Could not find required metric
NUM_RECORDS_OUT_PER_SEC for 667f5d5aa757fb217b92c06f0f5d2bf2
```
To prevent these errors shadowing actual errors, we should detect and ignore this recoverable exception.

[FLINK-33429] Tolerate missing metrics in the stabilization phase

---

.github/workflows/ci.yml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkResourceContext.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventSourceUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/OperatorTestBase.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FailedDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/RollbackTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/UnhealthyDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/health/HealthProbeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkSessionJobMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricGroupTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/Fabric8FlinkStandaloneKubeClientTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneJobManagerDecoratorTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/CmdStandaloneTaskManagerDecoratorTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/InitStandaloneTaskManagerDecoratorTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/decorators/UserLibMountDecoratorTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/factory/StandaloneKubernetesJobManagerFactoryTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/factory/StandaloneKubernetesTaskManagerFactoryTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesJobManagerParametersTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesTaskManagerParametersTest.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/standalone/KubernetesStandaloneClusterDescriptorTest.java
flink-kubernetes-webhook/src/test/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandlerTest.java
pom.xml

The PR is aiming to support compilation with java 21
Since spotless and google java format needs to be updated to work with java 21
new spotless/google-java-format rules are applied as well
Also lombok dependency is bump to the version which supports  java 21
This change is a trivial rework
- Dependencies (does it add or upgrade a dependency): (yes )

[FLINK-33471] Make flink kubernetes operator compilable with jdk21

---

docs/content/docs/custom-resource/autoscaler.md
flink-autoscaler/README.md

[FLINK-33102][autoscaler] Document the autoscaler standalone and Extensibility of Autoscaler
The following is the documentation on My Mac.

[FLINK-33102][autoscaler] Document the autoscaler standalone and Extensibility of Autoscaler

---

flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/flinkcluster/FlinkClusterJobListFetcher.java

[hotfix] Fix the checkstyle after supporting jdk21
https://github.com/apache/flink-kubernetes-operator/pull/701 didn't rebase master branch after FLINK-33099 is merged, and checkstyle is changed in https://github.com/apache/flink-kubernetes-operator/pull/701 , so the checkstyle are broken.
https://github.com/apache/flink-kubernetes-operator/actions/runs/6822258542/job/18554006329#step:5:22559  showed the checkstyle is failed.

[hotfix] Fix the checkstyle after supporting jdk21

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ReconcilerFactory.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java

There are a few config defaults that should be improved based on prod usage:
- Metric window : 10 -> 15m
- Catch up duration: 15 -> 30m
- Restart time: 3 -> 5m
- Utilisation boundary: 0.4 -> 0.3
These configs help make the default autoscaler behaviour smoother and less aggressive.
- *Config improvements*
- *Javadoc method naming cleanup*
- *Support autoscaler for session jobs*

[FLINK-33526] Autoscaler config improvement + cleanup

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java

Under certain circumstances, savepoint creation can succeed but the job fails afterwards. One example is when there are messages being distributed by the source coordinator to finished tasks. This is possibly a Flink bug although it's not clear yet how to resolve the issue.
After the savepoint succeeded Flink fails the job like this:
```
Source (1/2) (cd4d56ddb71c0e763cc400bcfe2fd8ac_4081cf0163fcce7fe6af0cf07ad2d43c_0_0) switched from RUNNING to FAILED on host-taskmanager-1-1 @ ip(dataPort=36519). 
```
```
An OperatorEvent from an OperatorCoordinator to a task was lost. Triggering task failover to ensure consistency. Event: 'AddSplitEvents[[[B@722a23fa]]', targetTask: Source (1/2) - execution #0
Caused by:
org.apache.flink.runtime.operators.coordination.TaskNotRunningException: Task is …
```

[FLINK-33522] Use created savepoint even if job cancellation fails

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingHistoryUtils.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/AutoScalerStateStore.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/InMemoryAutoScalerStateStore.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesAutoScalerStateStore.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesAutoScalerStateStoreTest.java

The new interfaces make use of Optional in many places where returning the object directly would result in less and more readable code.

[FLINK-33097] Cleanup use of Optional for new interfaces

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerContext.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingRecord.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingTracking.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingHistoryUtils.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/AutoScalerStateStore.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/InMemoryAutoScalerStateStore.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/utils/AutoScalerUtils.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingTrackingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/TestingAutoscalerUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStore.java

This PR does not yet contain tests since I would like to first reach consensus on the general approach.
Currently the autoscaler uses a preconfigured restart time for the job. This PR adds the ability to dynamically adjust this based on the observed restart times for scale operations
- Adds `ScalingTracking` for tracking job-scoped scaling data.
- Adds autoscaler properties for enabling the observed restart times usage in the rescaling logic(opt in).
**High level approach:**
The autoscaler adds a `ScalingTracking` object into the config map in the following format:
```
scalingTracking: |                                                                                                                                                         
---
scalingRecords: 
"2023-11-13T13:36:35.240245Z": …
```

[FLINK-30593][autoscaler] Determine restart time on the fly fo Autoscaler

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesScalingRealizer.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesScalingRealizerTest.java

The operator supports two modes to apply autoscaler changes:
1. Use the internal Flink config {{pipeline.jobvertex-parallelism-overrides}} 
2. Make use of Flink's Rescale API 
For (1), a string has to be generated for the Flink config with the actual overrides. This string has to be deterministic for a given map. But it is not.
Consider the following observed log:
```
>>> Event  | Info    | SPECCHANGED     | SCALE change(s) detected (Diff: FlinkDeploymentSpec[flinkConfiguration.pipeline.jobvertex-parallelism-overrides : 92542d1280187bd464274368a5f86977:3,9f979ed859083299d29f281832cb5be0:1,84881d7bda0dc3d44026e37403420039:1,1652184ffd0522859c7840a24936847c:1 -> 9f979ed859083299d29f281832cb5be0:1,84881d7bda0dc3d44026e37403420039:1,92542d1280187bd464274368a5f86977:3,1652184ffd0522859c7840a249 …
```

[FLINK-33710] Prevent NOOP spec updates from the autoscaler parallelism override map

---

flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/parameters/StandaloneKubernetesTaskManagerParameters.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/kubeclient/utils/TestUtils.java
flink-kubernetes-standalone/src/test/java/org/apache/flink/kubernetes/operator/standalone/KubernetesStandaloneClusterDescriptorTest.java

Bug fix. In standalone mode if config defining env vars for taskmanager are defined they are not being propagated to the taskmanagers
- Modify getEnvironments in StandaloneKubernetesTaskManagerParameters to retrieve env vars from config
- Extended KubernetesStandaloneClusterDescriptorTest to check envVars are correctly set
- KubernetesStandaloneClusterDescriptorTest extended to include check for env vars from additional config
- If yes, how is the feature documented? (not …

[FLINK-33645] Taskmanager env vars in config not given to taskmanager

---

docs/content/docs/custom-resource/job-management.md
docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/diff/DiffType.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/diff/SpecDiff.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/AbstractFlinkSpec.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/JobSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/DiffResult.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/ReflectiveDiffBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/diff/SpecDiffTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

A common request is to support a streamlined, user friendly way of redeploying from a target savepoint.
Previously this was only possible by deleting the CR and recreating it with initialSavepointPath. A big downside of this approach is a loss of savepoint/checkpoint history in the status that some platforms may need, resulting in non-cleaned up save points etc.
We  introduce a `savepointRedeployNonce` field in the job spec similar to other action trigger nonces.
If the nonce changes to a new non null value the job will be redeployed from the path specified in the initialSavepointPath (or empty state If the path is empty)
As redeployment requires the deletion of HA metadata and previous checkpoint info, rollbacks are not supported after redeployments (changing the nonce)
The PR also …

[FLINK-33763] Support savepoint redeployment through a nonce

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/IngressSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/IngressUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/IngressUtilsTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml

The managed ingress `IngressSpec` doesn't support TLS. It means that the ingress can't be used with secrets to secure the hosts. We can extend the `IngressSpec` to have `tls: List<IngressTlsSpec>`. In theory we shouldn't need a List spec here since the template only supports one host but I thought it was better to follow the Kubernetes spec since the change is pretty simple.
The managed ingress also doesn't have the ability to pass labels through to the Ingress. It would be nice to support this. It could be in a separate PR if we'd like but is very trivial.
Open to `IngressTLSSpec` if folks think that is better. I didn't like the double capital S beside each other.
Added an `IngressTlsSpec` to support tls entries in the `IngressSpec`
Added a labels entry to the `IngressSpec` to support …

[FLINK-33454] [Operator] Add IngressTls to support TLS within the managed Ingress, also add Label Passthrough

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/utils/DateTimeUtils.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/utils/DateTimeUtilsTest.java

[FLINK-33813][autoscaler] Improve time formatting for easier reading inside the autoscaler
The default format of Instant is UTC time, it's better to format it to the corresponding Time Zone.It will be easier reading.
- Added the DateTimeUtilsTest

[FLINK-33813][autoscaler] Improve time formatting for easier reading inside the autoscaler

---

helm/flink-kubernetes-operator/conf/log4j-operator.properties

In #725 we coverted the deprecated keys fallback keys and added test coverage. This additional change silences logs for fallback keys by setting the configuration logging to WARN instead of the default INFO.
This avoids spamming the log with unneccessary messages on every reconciliation loop, while still reporting warnings and errors.

[FLINK-33770] Silence Configuration logging for INFO messages

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/RestApiMetricsCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/AutoscalerFlinkMetrics.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/EvaluatedMetrics.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/FlinkMetric.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingMetric.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingMetrics.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/AutoScalerFlinkMetricsTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RestApiMetricsCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/TestingMetricsCollector.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/metrics/ScalingMetricsTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStore.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStoreTest.java

The autoscaler currently doesn't use any GC/HEAP metrics as part of the scaling decisions.
While the long term goal may be to support vertical scaling (increasing TM sizes) currently this is out of scope for the autoscaler.
However it is very important to detect cases where the throughput of certain vertices or the entire pipeline is critically affected by long GC pauses. In these cases the current autoscaler logic would wrongly assume a low true processing rate and scale the pipeline too high, ramping up costs and causing further issues.
Using the improved GC metrics introduced in https://issues.apache.org/jira/browse/FLINK-33318 we should measure the GC pauses and simply block scaling decisions if the pipeline spends too much time garbage collecting and notify the user about the …

[FLINK-33764] Track Heap usage and GC pressure to avoid unnecessary scaling

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java

This pull request tries to fix a bug, that when the autoscaler decides to scale up/down a standalone application deployment, the taskmanager's replica number does not change accordingly.
- When calculating the number of tm replicas, give priority to `PipelineOptions.PARALLELISM_OVERRIDES`
Unit tests + manual validation
- The public API, i.e., is any changes to the `CustomResourceDescriptors`:no)

[FLINK-33812] Autoscale not working properly for standalone application deployment

---

docs/content/docs/operations/helm.md

The default empty `operatorPod.resources` will lead to `BestEffort` Pod QoS.
And the `kubelet` prefers to evict BestEffort Pods if the node comes under resource pressure.
Add a notice for this.
Maybe we should set a meaningful defaults in the `values.yaml`?
https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#besteffort

[docs] Add a notice for operator pod resources

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java

https://issues.apache.org/jira/browse/FLINK-33917
Fix hostname being null under certain edgecases. 
- refactor AbstractFlinkService#isJobManagerReady to use URL instead of URI
You can reproduce this locally
```
@ParameterizedTest
@ValueSource(
strings = {"http://127.0.0.1:8081", "http://dev-test:8081", "http://dev-test.01:8081"})
void testURLAddresses(String inputAddress) {
assertDoesNotThrow(
() -> {
final URL url = new URL(inputAddress);
new InetSocketAddress(url.getHost(), url.getPort());
});
}
@ParameterizedTest
@ValueSource(
strings = {"http://127.0.0.1:8081", "http://dev-test:8081", "http://dev-test.01:8081"})
void testURIAddresses(String inputAddress) {
assertDoesNotThrow(
() -> {
final URI uri= new URI(inputAddress);
new InetSocketAddress(uri.getHost(), uri.getPort());
});
}
``` …

[FLINK-33917] fix hostname can't be null for certain edgecases

---

docs/content/docs/operations/configuration.md
docs/layouts/shortcodes/generated/autoscaler_standalone_configuration.html
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerEntrypoint.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/config/AutoscalerStandaloneOptions.java
flink-kubernetes-docs/pom.xml
flink-kubernetes-docs/src/main/java/org/apache/flink/kubernetes/operator/docs/configuration/ConfigOptionsDocGenerator.java

Currently, all configurations of autoscaler standalone are maintained in string key.
When autoscaler standalone has a little options, it's easy to maintain. However, I found it's hard to maintain when we add more options.
During I developing the JDBC autoscaler state store and control loop supports multiple thread. It will introduce more options.
Introducing the AutoscalerStandaloneOptions to manage all options of autoscaler standalone. And output the doc for it.
- [FLINK-33965][autoscaler] Introducing the AutoscalerStandaloneOptions to simplify options for autoscaler standalone
- [FLINK-33965][autoscaler] Generate the configuration doc for autoscaler standalone
- Dependencies (does it add or upgrade a dependency): …

[FLINK-33965][autoscaler] Introducing the AutoscalerStandaloneOptions to simplify options for autoscaler standalone

---

docs/layouts/shortcodes/generated/autoscaler_standalone_configuration.html
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/JobListFetcher.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerEntrypoint.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutor.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/config/AutoscalerStandaloneOptions.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/flinkcluster/FlinkClusterJobListFetcher.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutorTest.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/realizer/RescaleApiScalingRealizerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/event/TestingEventCollector.java

When the job list has a lot of jobs, single thread isn't enough. So Autoscaler Standalone control loop supports multiple thread is very useful for massive production, it's similar to `kubernetes.operator.reconcile.parallelism`.
Introduce `autoscaler.standalone.control-loop.parallelism`.
- Added `StandaloneAutoscalerExecutorTest#testScalingParallelism`

[FLINK-33814][autoscaler] Autoscaler Standalone control loop supports multiple threads

---

flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutor.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutorTest.java

Sorry for this fix!
After #744 is merged, I rebased it. During developing other features, I found `StandaloneAutoscalerExecutorTest.testScaling fails occasionally due to race condition`.
Here is my fork repo, it fails with :
https://github.com/1996fanrui/flink-kubernetes-operator/actions/runs/7405774151/job/20149240482#step:5:22232
```
Error:  Failures: 
Error:    StandaloneAutoscalerExecutorTest.testScaling:93 
Actual and expected should have same size but actual size is:
1
while expected size is:
2
Actual was:
[org.apache.flink.autoscaler.event.TestingEventCollector$Event@6b580b88,
org.apache.flink.autoscaler.event.TestingEventCollector$Event@6d91790b]
Expected was:
[9fe5243cd23e0727710fcd0b4d423970, 9eec17388e32cb02ec205ac9f638e2fe]
```
From this log, we know the reason is race …

[hotfix][autoscaler] Fix the StandaloneAutoscalerExecutorTest.testScaling fails occasionally due to race condition

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingMetrics.java

Fix the getNumRecordsInPerSecond Utility Function to addresses the redundant check and ensures correct metric fetching for non-source operators.

[FLINK-33966] Fix the getNumRecordsInPerSecond Utility Function

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java

When the ineffective scaling decision feature is turned off, events are regenerated which look like this:
```
Skipping further scale up after ineffective previous scale up for 65c763af14a952c064c400d516c25529
```
This is misleading because no action will be taken. It is fair to inform users about ineffective scale up even when the feature is disabled but a different message should be printed to convey that no action will be taken.

[FLINK-33993] Fix misleading events for scaling effectiveness detection

---

docs/content/docs/custom-resource/autoscaler.md
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/FlinkSessionJobObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkSessionJobController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/FlinkSessionJobObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

This PR resolves some bugs related to the job id management for session jobs which prevent submitting jobs when the spec generation doesn't change (causing a collision and error currently).
This is required for autoscaler support without the rescale api.
- *Generate random job ids for session jobs*
- *Improve / simplify deployment checks and test coverage*
Existing and new unit tests

[FLINK-33535] Support autoscaler for session jobs

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingRecord.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingTracking.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingTrackingTest.java

This PR contains the following improvements to the restart tracking logic:
* Adds more debug logs
* Stores restart Duration directly instead of the endTime Instant
* Fixes a bug that makes restart duration tracking dependent on whether metrics are considered fully collected

[FLINK-30593][autoscaler] Improve restart time tracking

---

flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutor.java
flink-autoscaler-standalone/src/main/resources/log4j2.properties

[FLINK-33814](https://issues.apache.org/jira/browse/FLINK-33814) has supported the multiple threads scaling for autoscaler standalone. When a lot of jobs are scaling, autoscaler standalone will print too many logs. Currently, all logs don't have the job key, it's hard to maintain.
- [FLINK-34021][autoscaler] Print jobKey in the Autoscaler standalone log
- Add `job.key` to the MDC
- `log4j.properties` print the `job.key`

[FLINK-34021][autoscaler] Print jobKey in the Autoscaler standalone log

---

docs/content/docs/operations/plugins.md
flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/mutator/DefaultFlinkMutator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/mutator/FlinkResourceMutator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/MutatorUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/mutator/TestMutator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/MutatorUtilsTest.java
flink-kubernetes-operator/src/test/resources/META-INF/services/org.apache.flink.kubernetes.operator.mutator.FlinkResourceMutator
flink-kubernetes-webhook/pom.xml
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkOperatorWebhook.java
flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/mutator/FlinkMutator.java
flink-kubernetes-webhook/src/test/assembly/test-plugins-assembly.xml
flink-kubernetes-webhook/src/test/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandlerTest.java

This PR is to provide pluggable mutators. Currently the operator allows for pluggable validators, we would like to extend this capability to provide custom mutation. Our organisation, for example, requires certain fields to be present on the deployment. Whilst we can do this using the podTemplate overrides it makes the CR quite unwieldy. Having a custom mutator would mean we could automatically add these values to the CR.
Implemented custom mutator for the flink kuberenetes operator.
* Implemented the interface FlinkResourceMutator.
* FlinkResourceMutator interface contains - mutateDeployment and mutateSessionJob which is implemented by Default and custom mutator.
* MutatorUtils discoverMutators methods helps to identify all the mutators which are implemented using FlinkResourceMutator …

[FLINK-33632] Adding custom flink mutator

---

flink-autoscaler-standalone/README.md

Fix a minor typo in `Adaptive` word in Standalone Autoscaler Documentation. 
Doc update
N/A
- Dependencies (does it add or upgrade a dependency): (yes / no) no 
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no) no
- Core observer or reconciler logic that is regularly executed: (yes / no) no 
- Does this pull request introduce a new feature? (yes / no) no 
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) N/A

Fix Typo in Standalone Autoscaler Documentation

---

flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/utils/BaseTestUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/UnhealthyDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluatorTest.java

Add a check on the cluster.health-check.checkpoint-progress.window before to access if the cluster is healthy from checkpointing
cluster.health-check.checkpoint-progress.window must be greater than max(execution.checkpointing.interval * execution.checkpointing.tolerable-failed-checkpoints, execution.checkpointing.timeout * execution.checkpointing.tolerable-failed-checkpoints)
If it is below it can leads to unwanted restart of the flink cluster
- *Ensure cluster.health-check.checkpoint-progress.window is well configure*
- *Added unittest ensuring the checkpoint evalutaion is always true if the window value is not well configured*
- …

[FLINK-34131] Ensure cluster.health-check.checkpoint-progress.window is well configure

---

e2e-tests/test_application_kubernetes_ha.sh
e2e-tests/test_application_operations.sh
e2e-tests/test_autoscaler.sh
e2e-tests/test_multi_sessionjob.sh
e2e-tests/test_sessionjob_kubernetes_ha.sh
e2e-tests/test_sessionjob_operations.sh
e2e-tests/utils.sh

There is a dead test code inside the operator tests which was planned to be fixed and re-enabled. The code is planned to be checking the operator log for error type messages and fail tests when this happens. However there are too many false positives because of negative test cases and its not realistic to be so strict that error typed messages can't appear in the operator log.
Remove e2e test operator log error check.
E2E tests still passing.

[FLINK-34198] Remove e2e test operator log error check

---

flink-autoscaler-plugin-jdbc/pom.xml
flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/state/JdbcAutoScalerStateStore.java
flink-autoscaler-standalone/src/main/resources/META-INF/NOTICE
flink-autoscaler/pom.xml
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingSummary.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingTracking.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/JobTopology.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/utils/AutoScalerSerDeModule.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/topology/JobTopologyTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStore.java

flink-autoscaler related modules are still using the jackson version of flink-kubernetes-operator instead of flink shaded version. It can be updated after `flink-1.18.1` is released.
The reason is : current autoscaler is using the loaderOptions to limit the serialized size.
- The shaded jackson version of `flink-1.17` is 2.13.4-16.1, it doesn't support the loaderOptions.
- The shaded jackson version of `flink-1.18` is 2.14.2-17.0, it supports the loaderOptions.
For details can be get from this comment[1].
- [FLINK-33287] Using the flink shaded jackson for flink-autoscaler
- Dependencies (does it add or upgrade a dependency): removed some dependencies from autoscaler related modules
- The public API, i.e., is any …

[FLINK-33287] Using the flink shaded jackson for flink-autoscaler

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/CommonStatus.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/ReconciliationStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

https://issues.apache.org/jira/browse/FLINK-33803
This pull requests adds the `observedGeneration` field to the `FlinkDeployment` CRD status. This field is used to persist the generation that was last acted on by the operator. At the end of a successful reconciliation (`reconcile`, `RecoveryFailureException`, `DeploymentFailedException` ), the operator sets the `observedGeneration` field to the current  `generation` number (from the CRD metadata).
- Operator sets `observedGeneration` field within `FlinkDeploymentStatus` after a completed reconciliation
- Test setting `observedGeneration` based on `generation` metadata taken from `lastReconciledSpec`
- The public API, i.e., is …

[FLINK-33803] Set observedGeneration at end of reconciliation

---

.github/workflows/ci.yml
e2e-tests/test_dynamic_config.sh
e2e-tests/test_flink_operator_ha.sh
e2e-tests/utils.sh

Add E2E for Flink operator high availability to verify whether the flink deployment core logic function well when the leader operator instance is deleted.
- Add delete_operator_pod_with_leadership in util.sh
- Add the test_flink_operator_ha.sh for the testing

[FLINK-33006] add e2e for Flink operator HA

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/AutoScalerEventHandler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/AutoscalerEventUtils.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/VertexScalingReport.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/event/AutoScalerEventHandlerTest.java

Currently, the scaling report format is  `Vertex ID %s | Parallelism %d -> %d | Processing capacity %.2f -> %.2f | Target data rate %.2f`.
It has 2 disadvantages:
1. When one job has multiple vertices, the report of all vertices are mixed together without any separator, here is an example:
- `Scaling execution enabled, begin scaling vertices: Vertex ID ea632d67b7d595e5b851708ae9ad79d6 | Parallelism 2 -> 1 | Processing capacity 800466.67 -> 320186.67 | Target data rate 715.10 Vertex ID bc764cd8ddf7a0cff126f51c16239658 | Parallelism 2 -> 1 | Processing capacity 79252.08 -> 31700.83 | Target data rate 895.93 Vertex ID 0a448493b4782967b150582570326227 | Parallelism 8 -> 16 | Processing capacity 716.05 -> 1141.00 | Target data rate 715.54`
- We can see the Vertex ID is the beginning of each …

[FLINK-34104][autoscaler] Improve the ScalingReport format of autoscaling

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java

Do not change the min parallelism requirements when rescaling pipelines with the adaptive scheduler in order to avoid unnecessary failures.
- Set min to previous min
Unit tests added
- If yes, how is the feature documented? JavaDocs

[FLINK-34311] Do not change min resource requirements when rescaling with adaptive scheduler

---

docs/content/docs/custom-resource/overview.md
docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/FlinkVersion.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml

We have previously removed Flink 1.13 and 1.14 support. See https://issues.apache.org/jira/browse/FLINK-33089. This removes some left-overs and adjusts the version check to work on the last-supported version.

[FLINK-33089] Clean up 1.13 and 1.14 references from docs and code

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/AutoscalerEventUtils.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/event/AutoScalerEventHandlerTest.java

`AutoscalerEventUtils#parseVertexScalingReports` uses the `Double.parseDouble` to parse the `CurrentProcessCapacity`, `expectedProcessCapacity` and `targetDataRate`.
But they are formatted by `String.format("%.2f")`, it will use the local format by default. And the decimal point format in EU is `,` instead of `.`.  For example: `String.format(Locale.GERMAN, "%.2f", 812.58)` will return `812,58`.
[FLINK-34329][autoscaler] Fix the bug that scaling report parser doesn't support Locale
- Step1: Using the NumberFormat to support Locale format because the event is formatted in String.format, it uses the Locale by default.
- Step2: Using the Double.parseDouble 
- NumberFormat doesn't support Infinity and NaN
- So we use the `Double.parseDouble` when the step1 doesn't work.
Locale as the …

[FLINK-34329][autoscaler] Fix the bug that scaling report parser doesn't support Locale

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingTracking.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/CollectedMetricHistory.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/TestingMetricsCollector.java

The ScalingTracking of autoscaler is wrong, it's always greater than AutoScalerOptions#STABILIZATION_INTERVAL.
When flink job isStabilizing, ScalingMetricCollector#updateMetrics will return a empty metric history. In the JobAutoScalerImpl#runScalingLogic method, if `collectedMetrics.getMetricHistory().isEmpty()` , we don't update the ScalingTracking.
The default value of AutoScalerOptions#STABILIZATION_INTERVAL is 5 min, so the restartTime is always greater than 5 min.
However, it's quick when we use rescale api.
Update the scaling tracking even if the job is stabilizing.
Adding the test later.
- Core observer or reconciler logic that is regularly …

[FLINK-34178][autoscaler] Fix the bug that observed scaling restart time is always great than `stabilization.interval`

---

docs/content/docs/custom-resource/pod-template.md
docs/content/docs/custom-resource/reference.md
e2e-tests/data/multi-sessionjob.yaml
examples/pod-template.yaml
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/FlinkDeploymentSpec.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/JobManagerSpec.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/TaskManagerSpec.java
flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/utils/BaseTestUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/ReflectiveDiffBuilder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/diff/SpecDiffTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

The PodTemplate fields in the CRD currently incorrectly use the Pod time, when they should be PodTemplateSpec type. This leads to unnecessary (meaningless) fields and a very large CRD for no gain.
Also accidentally changing fields like apiKind would trigger an unnecessary upgrade of the job.
This PR is the first step of correcting this mistake. Unfortunately we cannot simply change the type form Pod to PodTemplateSpec as it's a backward incompatible change for the users.
While Kubernetes itself would drop the now unsupported fields from the stored CRs themselves, users would not be able to submit the same CR again as they would get a validation error from the API server. We should defer the CRD schema change to the next version.
- *Change Pod -> PodTemplateSpec but keep the schema in CRD* …

[FLINK-31220] Replace Pod with PodTemplateSpec for the pod template properties

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

This pull request adds sessionJob's flinkConfiguration to effective config when validating FlinkSessionJob and FlinkDeployment resources.
- Extended unit test for *DefaultValidator*

[FLINK-34398][flink-kubernetes-operator] Consider FlinkSessionJob's flinkConfiguration overrides during session job spec validation

---

Dockerfile

Removed unnecessary `RUN chown ...` commands from Dockerfile to reduce output size image. With this change, the size of the image has been reduced from 469MB to 360MB.
A side-effect of this PR will be that the `NOTICE` file and `licenses` folder will be owned by `flink:flink` instead of `root:root` as well now, but I think that's acceptable.
- Remove most `RUN chown ...` commands from Dockerfile
- Built the image, ran some example deployments
- Inspected the images file structure before and after and verified that all permissions are the same
- Does this pull request introduce a new …

[FLINK-34439] Move chown operations to COPY commands in Dockerfile

---

flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/state/JdbcStateInteractor.java
flink-autoscaler-plugin-jdbc/src/main/resources/schema/derby_schema.sql
flink-autoscaler-plugin-jdbc/src/main/resources/schema/mysql_schema.sql
flink-autoscaler-plugin-jdbc/src/main/resources/schema/postgres_schema.sql
flink-autoscaler-plugin-jdbc/src/test/java/org/apache/flink/autoscaler/jdbc/testutils/databases/derby/DerbyExtension.java
flink-autoscaler-plugin-jdbc/src/test/resources/test_schema/mysql_schema.sql
flink-autoscaler-plugin-jdbc/src/test/resources/test_schema/postgres_schema.sql

JdbcAutoscalerStateStore explicitly writes update_time instead of relying on the database to update.
Some databases doesn't support update the timestamp column automatically. For example, Derby doesn't support update the update_time automatically when we update any data. It's hard to do a general test during I developing the test for JdbcAutoscalerEventHandler.
As the common&open source service, in order to support all databases well, it's better to handle it inside of the service.
In order to unify the design for JdbcAutoscalerEventHandler and JdbcAutoscalerStateStore, we update the design of JdbcAutoscalerStateStore in this PR.
[FLINK-34389][autoscaler] JdbcAutoscalerStateStore explicitly writes update_time

[FLINK-34389][autoscaler] JdbcAutoscalerStateStore explicitly writes update_time

---

docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_section.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java

Waiting for TaskManager and JobManager pods to be removed might cause issues in a slow Kubernetes cluster. Upon upgrade, there is a slim possibility that the operator will attempt to create a new `Deployment` before the last one was removed. This was mitigated by [FLINK-32334](https://issues.apache.org/jira/browse/FLINK-32334), which worked well for `standalone`  mode.
I wanted to simply implement `getTmPodList` for `native` mode at first, but after some investigation it became clear that all Kubernetes resources created by the operator or the JobManager will be children of a `Deployment` with `blockOwnerDeletion: true`, so it made sense to instead change the logic to poll the `Deployment` resources.
I also removed the `Thread.sleep()` calls, and instead use the Fabric8 Informers API, …

[FLINK-34438] Wait for Deployments to be deleted on cluster shutdown

---

docs/content/docs/custom-resource/autoscaler.md
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingTracking.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/FlinkMetric.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingMetric.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingMetrics.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/IOMetrics.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/JobTopology.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/VertexInfo.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/TestingMetricsCollector.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/metrics/ScalingMetricsTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/metrics/TestMetrics.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/topology/JobTopologyTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/utils/MemoryTuningTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStoreTest.java

This PR aims to cover both [FLINK-34213](https://issues.apache.org/jira/browse/FLINK-34213) and [FLINK-34266](https://issues.apache.org/jira/browse/FLINK-34266).
Currently all metric tracking for input / output data rates, busyTime etc happens based on perSecond metrics in Flink. Depending on the frequency of the autoscaler metric collection and the exact processing pattern of the application perSecond metrics can result in completely erroneous autoscaler metric computations.
The most important example of this would be handling large windowed computations or other burst loads where we have spikes in data rates after periods of inactivity. These use-cases currently completely break down with the autoscaler as the jobs are generally scaled too low because incoming data is not measured …

[FLINK-34266] Compute Autoscaler metrics correctly over metric window

---

docs/content/docs/custom-resource/autoscaler.md
docs/layouts/shortcodes/generated/autoscaler_standalone_configuration.html
flink-autoscaler-plugin-jdbc/pom.xml
flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/event/AutoScalerEvent.java
flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/event/JdbcAutoScalerEventHandler.java
flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/event/JdbcEventInteractor.java
flink-autoscaler-plugin-jdbc/src/main/resources/schema/derby_schema.sql
flink-autoscaler-plugin-jdbc/src/main/resources/schema/mysql_schema.sql
flink-autoscaler-plugin-jdbc/src/main/resources/schema/postgres_schema.sql
flink-autoscaler-plugin-jdbc/src/test/java/org/apache/flink/autoscaler/jdbc/event/AbstractJdbcAutoscalerEventHandlerITCase.java
flink-autoscaler-plugin-jdbc/src/test/java/org/apache/flink/autoscaler/jdbc/event/AbstractJdbcEventInteractorITCase.java
flink-autoscaler-plugin-jdbc/src/test/java/org/apache/flink/autoscaler/jdbc/event/CountableJdbcEventInteractor.java
flink-autoscaler-plugin-jdbc/src/test/java/org/apache/flink/autoscaler/jdbc/testutils/databases/derby/DerbyExtension.java
flink-autoscaler-plugin-jdbc/src/test/resources/test_schema/mysql_schema.sql
flink-autoscaler-plugin-jdbc/src/test/resources/test_schema/postgres_schema.sql
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/AutoscalerEventHandlerFactory.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerEntrypoint.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/config/AutoscalerStandaloneOptions.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/AutoscalerEventHandlerFactoryTest.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/AutoScalerEventHandler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/KubernetesAutoScalerEventHandler.java

-  [FLINK-33636][autoscaler] Support the JDBCAutoScalerEventHandler
- Design doc: https://docs.google.com/document/d/1wXs6lLvX5jw6KNsz1pP9rdNLGoeInWkd5lbZo-rQp4s/edit?usp=sharing
- [refactor] Moving the getParallelismHashCode from KubernetesAutoScalerEventHandler to AutoScalerEventHandler
- [FLINK-33636][autoscaler] Support the JDBCAutoScalerEventHandler
- [FLINK-33636][autoscaler] Autoscaler Standalone supports the JdbcAutoScalerEventHandler
- [FLINK-33636][autoscaler] Document the JDBC Autoscaler event handler
Added some test classes:
- AbstractJdbcAutoscalerEventHandlerITCase
- AbstractJdbcEventInteractorITCase
- AutoscalerEventHandlerFactoryTest
- …

[FLINK-33636][autoscaler] Support the JDBCAutoScalerEventHandler

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/JobTopology.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/VertexInfo.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/tuning/MemoryTuning.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingTrackingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/metrics/ScalingMetricsTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/topology/JobTopologyTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/tuning/MemoryTuningTest.java

This is follow up Jira of [FLINK-34471](https://issues.apache.org/jira/browse/FLINK-34471) #781 . [FLINK-34471](https://issues.apache.org/jira/browse/FLINK-34471) assuming all connections type are ALL_TO_ALL. This Jira will optimize it to save some network memory for forward and rescale connection.
Following is the optimization logic:
- When the connection type is FORWARD and the parallelism of 2 tasks are same. We calculate network memory based on FORWARD connection.
- When the connection type is FORWARD and the parallelism of 2 tasks are not same. We calculate network memory based on RESCALE connection.
- When the connection type is RESCALE. We calculate network memory based on RESCALE connection.
[FLINK-34502][autoscaler] Support calculating network memory for forward and rescale edge …

[FLINK-34502][autoscaler] Support calculating network memory for forward and rescale edge

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/JobTopology.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/ShipStrategy.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/topology/VertexInfo.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/tuning/MemoryTuning.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricCollectorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/metrics/ScalingMetricsTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/topology/JobTopologyTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/tuning/MemoryTuningTest.java

JobVertexScaler#scale has a optimization: Try to adjust the parallelism such that it divides the number of key groups without a remainder =>  data is evenly spread across subtasks.
It's only useful when the upstream shuffle type has keyBy. We should avoid this optimization when the upstream shuffle type doesn't have keyBy.
[FLINK-34504][autoscaler] Avoid the parallelism adjustment when the upstream shuffle type doesn't have keyBy
- Improve `JobVertexScalerTest#testParallelismComputation`
- Add `JobVertexScalerTest#testParallelismComputationWithKeyedOperator`
- Add `ScalingExecutorTest#testAdjustByMaxParallelism` …

[FLINK-34504][autoscaler] Avoid the parallelism adjustment when the upstream shuffle type doesn't have keyBy

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/tuning/ConfigChanges.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/tuning/MemoryScaling.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/tuning/MemoryTuning.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/tuning/MemoryScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/tuning/MemoryTuningTest.java

This adds an option to increase heap and managed memory when removing TaskManagers. The scaling is applied after adjusting the memory pools (heap, metaspace, network, managed) and only affects heap memory.
The reason for adding this functionality is that the likelihood of running into memory constrained scenarios when downscaling is increased after applying memory tuning. As a precaution, we temporarily increase the total cluster
memory proportionally to the removed TaskManagers up to the maximum allowed TaskManager memory.

[FLINK-34152] Add an option to scale memory when downscaling

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java

This pull request pass a fixed size thread pool to JOSDK, so that we can set a large reconciliation parallelism as we except .
- set a fixed size thread pool as reconciliation executor in  JOSDK configuration
*org.apache.flink.kubernetes.operator.FlinkOperatorTest#testConfigurationPassedToJOSDK:*
- *Extended check logic about reconciliation thread pool creation *
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: ( no)
- Core observer or reconciler logic that is regularly executed: ( yes)

[FLINK-34566] Pass a FixedThreadPool to set reconciliation parallelism correctly

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/runtime/rest/messages/job/metrics/IOMetricsInfo.java
flink-kubernetes-operator/src/test/java/runtime/rest/messages/job/metrics/IOMetricsInfoTest.java

- *Set the proper key for ineffective event triggering to avoid spamming the user with events*
- *Handle missing aggregated busy metrics gracefully in IOMetricsInfo for Flink 1.15*
Unit tests added
- If yes, how is the feature documented? no

[hotfix] Minor autoscaler event and metric improvements

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java

Users recently reported that scale down as "broken". Turned out that `target.utilization` and `target.utilization.boundary` were set to the same value. This prevents scale down entirely, which is expected and desired.
This PR adds a test to verify this behavior to avoid breaking this in the future.

[FLINK-34642] Add a test for zero lower utilization boundary

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java

We recently improved the JM deployment deletion mechanism, however it seems like task manager pod deletion can get stuck sometimes for a couple of minutes in native mode if we simply try to delete everything at once.
It speeds up the process and leads to cleaner shutdown if we scale down the JM deployment to 0 (shutting down the JM pods first) and then perform the deletion.
- Manually verified in local Kube env
- E2Es
- Unit tests 

[FLINK-34524] Scale down JM deployment to 0 before deletion

---

.github/workflows/ci.yml
flink-autoscaler-standalone/src/main/java/org/apache/flink/runtime/rest/messages/job/metrics/IOMetricsInfo.java

flink-ubernetes-operator is committed to supporting the latest 4 flink minor versions, and autoscaler is a part of flink-ubernetes-operator. Currently, the latest 4 flink minor versions are 1.15, 1.16, 1.17 and 1.18.
But autoscaler doesn't work for flink 1.15.
- [FLINK-28310](https://issues.apache.org/jira/browse/FLINK-28310) added some properties in IOMetricsInfo in flink-1.16
- IOMetricsInfo is a part of JobDetailsInfo
- JobDetailsInfo is necessary for autoscaler [1]
- flink's RestClient doesn't allow miss any property during deserializing the json
That means that the RestClient after 1.15 cannot fetch JobDetailsInfo for 1.15 jobs.
- [[FLINK-34655](https://issues.apache.org/jira/browse/FLINK-34655)] Copy IOMetricsInfo to flink-autoscaler-standalone module
- Removing them after 1.15 are …

 [FLINK-34655] Copy IOMetricsInfo to flink-autoscaler-standalone module 

---

flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/ReconciliationStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/AbstractFlinkResourceObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ReconciliationUtilsTest.java

The operator currently puts the resource into upgrading state after triggering in-place scaling and keeps observing until the desired parallelism is reached before moving to deployed / stable. 
However this means that due to how the adaptive scheduler works this parallelism may never be reached and this is expected.
We should simplify the logic to consider scaling "done" once the resource requirements have been set correctly and then leave the rest to the adaptive scheduler
- *Remove complex logic around in-place, triggering and UPGRADING state*
- *Remove observing logic for in progress scaling*
- *Make sure we are backward compatible*
Unit tests
- Core …

[FLINK-34619] Do not wait for scaling completion in UPGRADE state with in-place scaling

---

examples/autoscaling/autoscaling-dynamic.yaml

autoscaling-dynamic cannot run on my Local
I guess yaml cannot hanlde the `\n` properly with multiple lines. 
It works after changing them to one line.

[FLINK-34744][autoscaler] Fix the issue that autoscaling-dynamic cannot run

---

docs/content/docs/custom-resource/autoscaler.md

The doc is updated after `job.autoscaler.restart.time-tracking.enabled` is supported.
[hotfix] Correct the doc related to restart time tracking

[hotfix] Correct the doc related to restart time tracking

---

flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/event/AutoScalerEventHandler.java

JDBC Autoscaler event handler doesn't allow the event message is null, but the message may be null when we handle the exception.
We consider the exception message as the event message, but the exception message may be null, such as: TimeoutException. (It has been shown in following picture.)
Also, recording a event without any message is meaningless. It doesn't have any benefit for troubleshooting.
- [FLINK-34957][autoscaler] Event handler records the exception stack trace when exception message is null
- Consider the exception message as the event message when exception message isn't null
- The whole Exception as the event message if exception message is null.
Test manually, it works well. We can see the detailed exception from the `LoggingEventHandler`.
- Dependencies (does it add or …

[FLINK-34957][autoscaler] Event handler records the exception stack trace when exception message is null

---

docs/config.toml
docs/content.zh/_index.md
docs/content.zh/docs/concepts/_index.md
docs/content.zh/docs/concepts/architecture.md
docs/content.zh/docs/concepts/controller-flow.md
docs/content.zh/docs/concepts/overview.md
docs/content.zh/docs/custom-resource/_index.md
docs/content.zh/docs/custom-resource/autoscaler.md
docs/content.zh/docs/custom-resource/autotuning.md
docs/content.zh/docs/custom-resource/job-management.md
docs/content.zh/docs/custom-resource/overview.md
docs/content.zh/docs/custom-resource/pod-template.md
docs/content.zh/docs/custom-resource/reference.md
docs/content.zh/docs/development/_index.md
docs/content.zh/docs/development/guide.md
docs/content.zh/docs/development/roadmap.md
docs/content.zh/docs/operations/_index.md
docs/content.zh/docs/operations/compatibility.md
docs/content.zh/docs/operations/configuration.md
docs/content.zh/docs/operations/health.md
docs/content.zh/docs/operations/helm.md
docs/content.zh/docs/operations/ingress.md
docs/content.zh/docs/operations/metrics-logging.md
docs/content.zh/docs/operations/plugins.md
docs/content.zh/docs/operations/rbac.md
docs/content.zh/docs/operations/upgrade.md
docs/content.zh/docs/try-flink-kubernetes-operator/_index.md
docs/content.zh/docs/try-flink-kubernetes-operator/quick-start.md
docs/content.zh/versions.md

https://issues.apache.org/jira/browse/FLINK-34934
Build the Flink-Kubernetes-Operator document translation framework, and subsequently translate English documents one by one.
Copy all documentations to content.zh folder, and add the English and Chinese（中文版） button.

[FLINK-34934] Translation Flink-Kubernetes-Operator document framework construction

---

.github/workflows/ci.yml

The problem with current GHA ci is that it has `CI` name which is the same across multiple Flink projects and Apache INFRA doesn't differentiate it in it's  GHA usage report https://infra-reports.apache.org/#ghactions . The idea is to use different names to cope with this
changed name for gha ci
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: ( no)
- If yes, how is the feature documented? (not applicable )

[FLINK-34961] Use dedicated CI name for Kubernetes Operator to differentiate it in infra-reports

---

flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/flinkcluster/FlinkClusterJobListFetcher.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/flinkcluster/FlinkClusterJobListFetcherTest.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/utils/JobStatusUtils.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/utils/JobStatusUtilsTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java

Currently, the autoscaler will scale a job when the JobStatus is RUNNING. But the JobStatus will be RUNNING once job starts schedule, so it doesn't mean all tasks are running. Especially, when the resource isn't enough or job recovers from large state.
The autoscaler will throw exception and generate the AutoscalerError event when tasks are not ready. Also, we don't need to scale it when some tasks are not ready.
- [FLINK-34906] Only scale when all tasks are running
- Solution: we only scale job that all tasks are running(some of tasks may be finished). 
- Manually test is done
- Added the `JobStatusUtilsTest` …

[FLINK-34906] Only scale when all tasks are running

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java

The `cause instanceof FlinkJobNotFoundException` cat't catch the exception
```
... SessionJobReconciler [ERROR][.../...] Failed to cancel job fffffffffab07a8e0000000000000001, will reschedule after 5000 milliseconds.
java.util.concurrent.ExecutionException: org.apache.flink.runtime.rest.util.RestClientException: [org.apache.flink.runtime.rest.handler.RestHandlerException: Job could not be found.
at org.apache.flink.runtime.rest.handler.job.JobCancellationHandler.lambda$handleRequest$0(JobCancellationHandler.java:128)
...
Caused by: org.apache.flink.runtime.messages.FlinkJobNotFoundException: Could not find Flink job (fffffffffab07a8e0000000000000001)
at org.apache.flink.runtime.dispatcher.Dispatcher.cancelJob(Dispatcher.java:749)
...
Caused by: …
```

[hotfix] Using Flink ExceptionUtils for exception checking

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java

According to [FLINK-35192](https://issues.apache.org/jira/browse/FLINK-35192), the usage of file.deleteOnExit() will register a hashmap entry in the JVM which is cleaned only when the JVM shuts down. As a result, a lot of memory would be used when the operator is running for a long time with plenty of submissions. As we have guaranteed that those temporary config files would be cleaned up in FlinkConfigManager's cache mechanism, we can safely remove the usage of deleteOnExit().
- Remove the usage of deleteOnExit() in FlinkConfigBuilder
This change is already covered by existing tests, such as org.apache.flink.kubernetes.operator.config.FlinkConfigManagerTest#testConfUpdateAndCleanup.
- Dependencies (does it add or upgrade a dependency): (yes …

[FLINK-35192] Remove usage of deleteOnExit() to reduce the memory usage of the operator

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/StatusRecorderTest.java

Fix occasional NPE on getting latest resource for status replace.
- Added a `null`-check for `latest` and `latest.getMetadata()` and throw ex. to retry with delay.
- Separated error handling to a new method to make it testable.
- Added unit test to verify the `null`-check and the thrown ex.

[FLINK-35278] Fix occasional NPE on getting latest resource for status replace

---

docs/content.zh/docs/custom-resource/autoscaler.md
docs/content/docs/custom-resource/autoscaler.md
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/JobListFetcher.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutor.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/flinkcluster/FlinkClusterJobListFetcher.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutorTest.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/flinkcluster/FlinkClusterJobListFetcherTest.java

Currently, autoscaler standalone doesn't support set [autoscaler options](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-release-1.8/docs/operations/configuration/#autoscaler-configuration). We must set them at job level when we use autoscaler standalone. It's not convenient if platform administrator wanna change the default value for some autoscaler options, such as:
- job.autoscaler.enabled
- job.autoscaler.metrics.window
- etc
- [FLINK-35105][autoscaler] Support setting default Autoscaler options at autoscaler standalone level
- This Jira supports setting Autoscaler options at autoscaler standalone level, it's similar with flink kubernetes operator.
- The  autoscaler options of autoscaler standalone will be as the base configuration, and the configuration at …

[FLINK-35105][autoscaler] Support setting default Autoscaler options at autoscaler standalone level

---

flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutor.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutorTest.java

Autoscaler Standalone will fetch job list, and scale them. In general, autoscaler has some cache in memory.
Autoscaler Standalone should clean up them if some jobs cannot be fetched anymore.
- [FLINK-34212][autoscaler] Autoscaler Standalone cleans up stopped jobs to prevent memory leaks
- We assume one job is stopped when one job is fetched in the last control loop and it cannot be fetched in current control loop.
- Added `testCleanupAfterStopped` & `testCleanupForStoppedJobAfterScaling` in StandaloneAutoscalerExecutorTest class
- If yes, …

[FLINK-34212][autoscaler] Autoscaler Standalone cleans up stopped jobs to prevent memory leaks

---

flink-autoscaler-standalone/pom.xml
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/AutoscalerEventHandlerFactory.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/AutoscalerStateStoreFactory.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/utils/HikariJDBCUtil.java
flink-autoscaler-standalone/src/main/resources/META-INF/NOTICE
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/AutoscalerEventHandlerFactoryTest.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/AutoscalerStateStoreFactoryTest.java
flink-autoscaler/pom.xml
pom.xml

*Autoscaler JDBC Support HikariPool to Replace JDBC DirverManager*
- *Add Autoscaler HikariPool Test*
- *Replace JDBC DirverManager Wiht HikariPool DataSource*
- *Added HikariPool Connection Test*
- Dependencies (does it add or upgrade a dependency): (yes)
- If yes, how is the feature documented? (not documented)

[FLINK-34537] Autoscaler JDBC Support HikariPool

---

Dockerfile
docker-entrypoint.sh

According to [FLINK-35192](https://issues.apache.org/jira/browse/FLINK-35192), the current operator image uses glibc as the memory allocator, which may cause memory leaks due to memory fragmentation.
This pr introduces jemalloc as a memory allocator for the operator's image.
Introducing the `DISABLE_JEMALLOC` parameter to control whether the operator's image uses jemalloc as the memory allocator
This change is already covered by existing  ci-tests
- If yes, how is the feature documented?  not documented

[FLINK-35192] support jemalloc in image

---

helm/flink-kubernetes-operator/templates/rbac.yaml

Replace all wildcards in the RBAC HELM template of the flink-operator with it's proper verb names.
- replaced every "*" with a list of verb names suitable to the according sections
- If yes, how is the feature documented? not documented

[FLINK-35310] Replace RBAC verb wildcards with actual verbs

---

docs/content/docs/operations/ingress.md

In the "Simple domain based routing" example, there's no `/` so the ingress doesn't work by default

Fix ingress example in docs

---

docs/content/docs/operations/upgrade.md

The ID in the savepoint folder name that is passed as a parameter, and the ID in the folder name that is given as the log example do NOT match. 
Expected ID in log example: `aec3dd08e76d`
Actual ID given in the log example: `2f40a9c8e4b9`

[hotfix][docs] Fix typo in Log Example Given on upgrade.md File

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/tuning/MemoryTuning.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/tuning/MemoryTuningTest.java

If the heap usage with overhead leads to remaining memory to be assigned to the HEAP no memory will be assigned to the METASPACE leading to JVM failure at startup
By setting this before the HEAP we ensure the JVM can start with appropriate amount of METASPACE memory
- *Compute METASPACE size to set before the HEAP size*
- Extended tests to validate that despite a big HEAP usage that would lead to the whole memory being used by it, the METASPACE has been well set with all appropriate memory
- Does this pull request …

[FLINK-35489][Autoscaler] Ensure METASPACE size is computed before the heap

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java

AutoScale supports setting the maximum floating parallelism by the number of Pulsar partitions.
Since Pulsar Source metrics are related to a single Consumer identifier, a single partition may have multiple consumer identifiers, so some deduplication needs to be done here, grouping by topic and partition ID.

[FLINK-35328] AutoScale supports setting the maximum floating parallelism by the number of Pulsar partitions

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

The admission webhook currently does not verify if FlinkDeployment CR utilizes Flink versions that are not supported by the Operator. This causes the CR to be accepted and the failure to be postponed until the reconciliation phase. We should instead fail fast and provide users direct feedback.
Adds a Flink version check to the validator
Added a test case to the existing test suite
- Does this pull request introduce a new feature? (**yes** / no)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

[FLINK-35052] Reject unsupported versions in the webhook validator

---

Dockerfile

Adds Apache 2 LICENSE to Apache Kubernetes Operator Docker image
- Adds LICENSE file to docker stage image
- Run `mvn clean verify -T1C -DskipTests` 
- `docker build  . -t apache/flink-kubernetes-operator:latest`
- From folder where apache-kubernetes-operator code is checked out, verified checksum
```
❯ docker run -it apache/flink-kubernetes-operator:latest cksum LICENSE
3425401509 11357 LICENSE
❯ cksum LICENSE
3425401509 11357 LICENSE 
```

[FLINK-35593][Kubernetes Operator] Add Apache 2 License to docker image

---

.github/workflows/ci.yml
.github/workflows/publish_snapshot.yml

Use maven batch mode in GH CI workflows, so the produced logs are not polluted with `Progress ...` lines coming from maven interactive mode.
- Add `-B` to every relevant `mvn` call.

[FLINK-35662] Use maven batch mode in CI workflows

---

docs/content.zh/docs/concepts/overview.md
docs/content.zh/docs/custom-resource/overview.md
docs/content/docs/concepts/overview.md
docs/content/docs/custom-resource/overview.md
docs/content/docs/custom-resource/reference.md
examples/flink-beam-example/Dockerfile
examples/flink-beam-example/beam-example.yaml
examples/flink-beam-example/pom.xml
examples/kubernetes-client-examples/src/main/java/org/apache/flink/examples/Basic.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/FlinkVersion.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

Flink 1.15 is being deprecated in the next release. As can be seen in the conversation below, there are no codepaths related to this Flink version, the decision was to deprecate the version, and the operator should still be able to create Flink deployments.
- Deprecated Flink 1.15
- Update tests to use newer versions where it made sense
- Update beam example to use Flink 1.16

[FLINK-35640] Deprecate Flink version 1.15

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Job Ids can and should be rotated on savepoint redeployments as well. It is only important to keep the jobId when we are relying on recovery from HA metadata during last-state restore.
- Change jobid rotation logic from stateless only to (not last-state)
Unit tests, existing e2es

[FLINK-35831] Rotate jobId for both savepoint and stateless deploys

---

docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/UnhealthyDeploymentRestartTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluatorTest.java

Currently the checkpoint progress health check window is configurable by Duration. This makes it hard to enable by default as the sensible interval depends on the checkpoint interval. 
At the same time the operator already contains logic for a minimum progress check interval computed from the checkpoint timeout , tolerable failures and checkpoint interval.
Furthermore for any job with checkpointing enabled this health check is very valuable to have enabled by default similar to the restart health check. This PR also proposes to enable this feature by default with the the minimum checkpoint check interval set.
- Enable checkpoint progress health check by default (for jobs with checkpointing configured)
- Set the minimum based on the calculated that already enforces the lower bound 
Unit …

[FLINK-35126] Rework default checkpoint progress check window

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

Currently the operator always sets the savepoint path even if last-state (HA metadata) must be used. 
This can be misleading to users as the set savepoint path normally should never take effect and can actually lead to incorrect state restored if the HA metadata is deleted by the user at the wrong moment.
To avoid this we can set an explicit dummy savepoint path which will prevent restoring from it accidentally. 
- Set dummy savepoint path during last-state upgrade
- Add/update tests
Unit tests + manual verification

[FLINK-35292] Set dummy savepoint path during last-state upgrade

---

docs/content/docs/concepts/controller-flow.md
docs/content/docs/concepts/overview.md
docs/content/docs/custom-resource/job-management.md
docs/content/docs/custom-resource/overview.md
docs/content/docs/custom-resource/snapshots.md
docs/content/docs/operations/upgrade.md
examples/snapshot/checkpoint.yaml
examples/snapshot/job-from-savepoint.yaml
examples/snapshot/savepoint-already-exists.yaml
examples/snapshot/savepoint-job-defaults.yaml
examples/snapshot/savepoint-job-full-spec.yaml

Adds documentation and examples for [FLINK-35265](https://issues.apache.org/jira/browse/FLINK-35265) which can be found at PR #821 
- Added examples
- Added snapshots.md
- Removed segments from job-management.md and moved them to snapshots.md
- Changed references of `initialSavepointPath` to `flinkStateSnapshotReference.path`
Verified examples

[FLINK-35267][snapshot] FlinkStateSnapshot documentation and examples

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkStateSnapshotUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkStateSnapshotUtilsTest.java

In case the operator is deployed in multiple namespaces, periodic and upgrade FlinkStateSnapshots will always be created in the default namespace.
With this fix, all new FlinkStateSnapshots will be created in the same namespace as the associated Flink job.

[FLINK-35265][snapshot] Create FlinkStateSnapshot in the namespace of job

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtilsTest.java

Suspended `savepoint` upgrade-mode Flink jobs submitted with Operator version 1.9 won't restore from the proper savepoint unless this fix is applied. If `status.jobStatus.upgradeSnapshotReference` is null, the operator will fallback to `status.jobStatus.savepointInfo.lastSavepoint.location` when determining savepoint location.
- Fallback to reading deprecated savepoint fields when using `upgradeSnapshotReference`
- Unit test
- Manual test

[FLINK-36037][snapshot] Add backwards compatibility for job upgrades

---

docs/content/docs/custom-resource/snapshots.md
docs/layouts/shortcodes/generated/dynamic_section.html
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_advanced_section.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/utils/DateTimeUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SnapshotObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventSourceUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkStateSnapshotUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/KubernetesClientUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SnapshotObserverLegacyTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SnapshotObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkStateSnapshotUtilsTest.java

- *Added InformerEventSource for Flink resources to be able to list linked snapshots during reconciliation*
- *If FlinkStateSnapshot resources are enabled, clean them up by age/count in SnapshotObserver*
- *Add unit tests*
- Added unit tests
- Manual testing with checkpoint and snapshot resources, with age and count based cleanup policies
- If yes, how is the feature documented? documentation and examples will be provided in PR #854

[FLINK-35493][snapshot] Add historical cleanup for FlinkStateSnapshot CRs

---

flink-autoscaler-plugin-jdbc/src/test/java/org/apache/flink/autoscaler/jdbc/testutils/databases/mysql/MySQLExtension.java
flink-autoscaler-plugin-jdbc/src/test/java/org/apache/flink/autoscaler/jdbc/testutils/databases/postgres/PostgreSQLExtension.java

During review https://github.com/apache/flink-kubernetes-operator/pull/865, I found t_flink_autoscaler_event_handler is not cleaned after each testing
- [FLINK-36106][autoscaler] Clean up the t_flink_autoscaler_event_handler table after each test

[FLINK-36106][autoscaler] Clean up the t_flink_autoscaler_event_handler table after each test

---

flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/reconciler/ReconciliationMetadata.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/utils/SpecUtils.java
flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/utils/SpecUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

Followup to https://issues.apache.org/jira/browse/FLINK-33803 (https://github.com/apache/flink-kubernetes-operator/pull/755)
> The `observedGeneration` field in the `FlinkDeployment` CRD status is used to persist the generation that was last acted on by the operator. At the end of a successful reconciliation, the operator sets the `observedGeneration` field to the current `generation` number (from the CRD metadata).
This PR removes internal usages of the `lastReconciledSpec` metadata (and generation) that were kept in the initial PR to avoid downstream breakage. `observedGeneration` replaces this semantically. Removing the deprecated fields is to end up with a cleaner codebase.
Note: the removed fields were nested within the `lastReconciledSpec` `String`, thus there is no documentation to …

[FLINK-33803] Remove deprecated `lastReconciledSpec` meta generation in favour of `observedGeneration`

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SnapshotObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SnapshotTriggerTimestampStore.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkStateSnapshotUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/SnapshotTriggerTimestampStoreTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtilsTest.java

SnapshotObserver uses deprecated fields as the latest timestamp of triggered snapshots. These fields are not updated when using FlinkStateSnapshot though. This new method of storing these timestamps is meant to fix this case.
- Add new class to store/retrieve last timestamp a snapshot was triggered
- Updated relevant code to store/retrieve last timestamp in new class
- Added unit tests
- Manual testing

[FLINK-36110][snapshot] Store periodic snapshot trigger timestamps in memory

---

pom.xml

Bump the **assertj-core** version to remediate vulnerabilities on the dependant packages.
Package info:
https://mvnrepository.com/artifact/org.assertj/assertj-core/3.26.3
change info:
https://github.com/r-sidd/flink-kubernetes-operator/blob/main/pom.xml#L99

[FLINK-36170] bump assert4j version

---

flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
pom.xml

Bumping **log4j** to the latest version (2.23.1) - this will remediate a lot of vulnerabilities in dependant packages.
**Package details:**
https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-1.2-api/2.23.1
https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl/2.23.1
https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api/2.23.1
https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.23.1
**Release notes:**
https://logging.apache.org/log4j/2.x/release-notes.html
Lot of bug fixes has been done in the newer versions and I don't see any breaking changes as such.

[FLINK-36179] bump log4j version

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
e2e-tests/data/autoscaler.yaml
flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/state/JdbcAutoScalerStateStore.java
flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/state/StateType.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/DelayedScaleDown.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/AutoScalerStateStore.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/InMemoryAutoScalerStateStore.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/state/AbstractAutoScalerStateStoreTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStore.java

When the source traffic decreases, the autoscaler scales down job in time to save resources. It causes that each job rescales more than 20 times a day.
- [FLINK-36018][autoscaler] Support lazy scale down to avoid frequent rescaling
- Configuration Option:
- Introduce job.autoscaler.scale-down.interval, the default value could be 1 hour.
- Replace job.autoscaler.scale-up.grace-period with job.autoscaler.scale-down.interval
- Core code change:
-  Introducing the `DelayedScaleDown` to store the firstTriggerTime for all vertices.
- The scale down can be triggered when the (now -  firstTriggerTime  > scale-down.interval).
- Updating the return value type of `JobVertexScaler#computeScaleTargetParallelism` from `int` to `ParallelismResult`
- `ParallelismResult` introduced the `required` field, …

[FLINK-36018][autoscaler] Support lazy scale down to avoid frequent rescaling

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

The change allows the flink operator pod to be assigned a node based on pod affinity which gives more flexibility
- Allow pod created by  flink operator to define affinity, so it is more flexible to select a node where the pod can start
- Just a change in K8 env to add a affinity. Node slector is already supported but in some cases its nice to have (https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) 
- Dependencies (does it add or upgrade a dependency): (yes / no) No
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no) No
- Core observer or reconciler logic that is regularly executed: (yes / no) No
- Does this pull request introduce a …

[FLINK-36353][Flink Operator Helm chart] Allow to add affinity for operator pod of helm chart

---

flink-autoscaler-plugin-jdbc/pom.xml
pom.xml

Bump **curator-test** version to latest (**5.7.0**) to remediate the vulnerabilities in the dependant packages.
**Package details:**
https://mvnrepository.com/artifact/org.apache.curator/curator-test/5.7.0
Bump **postgresql** version to **42.5.6** to remediate a direct finding.
**Finding details:**
[CVE-2024-1597](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-1597)
**Package details:**
https://mvnrepository.com/artifact/org.postgresql/postgresql/42.5.6
Bump **derby** version to latest **(10.17.1.0)** to remediate direct finding.
**Finding details:**
[CVE-2022-46337](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-46337)
**Package details:**
https://mvnrepository.com/artifact/org.apache.derby/derby/10.17.1.0
- Does …

FLINK-36197 bump curator-test and postgres

---

.github/workflows/ci.yml

Update to the latest version of the GitHub actions to avoid warnings about outdated NoeJS versions.
Update to the latest version of the GitHub actions to avoid warnings about outdated NoeJS versions.

[FlINK-36393] Update to GitHub build to use the current versions of actions 

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkStateSnapshotController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/FlinkStateSnapshotMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkStateSnapshotControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkStateSnapshotMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkStateSnapshotMetricsUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/TestingMetricListener.java

Add metrics for FlinkStateSnapshot resources and fix several existing issues. Example metrics:
```
...flink-kubernetes-operator.namespace.flink.FlinkStateSnapshot.Savepoint.Count: 3
...flink-kubernetes-operator.namespace.flink.FlinkStateSnapshot.Savepoint.State.TRIGGER_PENDING.Count: 0
...flink-kubernetes-operator.namespace.flink.FlinkStateSnapshot.Savepoint.State.IN_PROGRESS.Count: 0
...flink-kubernetes-operator.namespace.flink.FlinkStateSnapshot.Savepoint.State.ABANDONED.Count: 1
...flink-kubernetes-operator.namespace.flink.FlinkStateSnapshot.Savepoint.State.FAILED.Count: 0
...flink-kubernetes-operator.namespace.flink.FlinkStateSnapshot.Savepoint.State.COMPLETED.Count: 2
...flink-kubernetes-operator.namespace.flink.FlinkStateSnapshot.Checkpoint.Count: 2 …
```

[FLINK-35492][snapshot] Add metrics for snapshot resources

---

.github/workflows/ci.yml
Dockerfile

Fixes the docker build for edge to edge (e2e) ci tests so that they build the operator with the Java version specified by the test matrix.
- *Ensure the CI tests run with appropriate JVM version*
- Dependencies (does it add or upgrade a dependency): *no*
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: *no*
- Core observer or reconciler logic that is regularly executed: *no*
- Does this pull request introduce a new feature? *no*
- If yes, how is the feature documented? *not applicable*

[FLINK-36392] Build with target jdk

---

.github/workflows/ci.yml
Dockerfile
flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStore.java
flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
pom.xml

Enable the building of the operator using alternative Fabric8 http clients.
Enable the building of the operator using alternative Fabric8 http clients.
The build should still work even when run with `-Dfabric8.httpclinent.impl=vertx` or `jdk` or `jetty` for that matter 😁 
- Dependencies (does it add or upgrade a dependency): yes. 
- Does this pull request introduce a new feature? (yes / no)

FLINK-36332 Add option to select the Fabric8 httpclient implemention

---

flink-autoscaler/pom.xml
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RestApiMetricsCollectorTest.java
flink-kubernetes-operator-api/pom.xml
flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetricsTest.java
pom.xml

Operator metrics are lazily initialised. This PR addresses race conditions in tests trying to assert metrics.
An alternative to the `Thread.sleep` proposed in https://github.com/apache/flink-kubernetes-operator/pull/891 
Wait for metrics to be initialised in integration tests.
This change is purely a fix to `RestApiMetricsCollectorTest` & `KubernetesClientMetricsTest`

[FLINK-36473] Wait for metrics before asserting on them

---

.github/workflows/docker_push.yml

Upgrade to the current versions of the docker actions to avoid NodeJS 12 deprecation
Upgrade to the current versions of the docker actions to avoid NodeJS 12 deprecation

[FLINK-36471] Update docker build actions to current versions.

---

docs/content/docs/custom-resource/snapshots.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/CrdConstants.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkStateSnapshotContext.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkStateSnapshotController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SnapshotTriggerTimestampStore.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkResourceContextFactory.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventSourceUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkStateSnapshotUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkStateSnapshotControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SnapshotObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/SnapshotTriggerTimestampStoreTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerUpgradeModeTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkStateSnapshotUtilsTest.java

Adds labels to FlinkStateSnapshot resources managed by the operator to allow for filtering. Currently we have no way to easily filter snapshots resources (e.g. by job reference, snapshot type or state), since the API server only allows to filter by labels for custom resources. 
The only way currently is to download all resources from the API-server and filter the resources client-side. Filtering by labels allows the API-server to serve the snapshots in a more optimized way.
Once [KEP-4358](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/4358-custom-resource-field-selectors/README.md) is available as GA, we can hopefully gradually switch to using spec and status fields as field selectors.
- Before the end of each reconciliation phase of a snapshot, update its …

[FLINK-36109][snapshot] Add labels to snapshot resources

---

flink-autoscaler-standalone/src/main/resources/META-INF/NOTICE
flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
pom.xml

Bump commons-io from 2.11.0 to 2.17.0
Commons-io version 2.11.0 has a direct vulnerability and bumping it to the newer version (2.17.0) will remediate this finding.
**Direct vulnerabilities:**
[CVE-2024-47554](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-47554)
**Package details:**
https://mvnrepository.com/artifact/commons-io/commons-io/2.17.0

[FLINK-36469] Bump commons-io from 2.11.0 to 2.17.0

---

.github/workflows/ci.yml
e2e-tests/cert-manager.yaml

A lot of CI failures are caused by Install cert-manager. Get more details from  FLINK-36513.
[FLINK-36513][ci] Storing the cert-manager.yaml to avoid downloading timeout

[FLINK-36513][ci] Storing the cert-manager.yaml to avoid downloading timeout

---

pom.xml

Bump apache-rat-plugin
Bump apache-rat-plugin from 0.12 to 0.16.1 to remediate the underlying vulnerabilities in the dependencies.
Vulnerabilities from dependencies:
[CVE-2022-4245](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4245)
[CVE-2022-4244](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4244)
[CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250)
- Dependencies (does it add or upgrade a dependency):  yes

[FLINK-36449] Bump apache-rat-plugin

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java

Fix can not setup other values for parameter `rest-service.exposed.type` when using ingress
Only if using ingress and the `rest-service.exposed.type=null`, operator will setup as `ClusterIp` when 
Unit tests + manual verification

[FLINK-36264] Fix can not setup other values for parameter `rest-service.exposed.type`

---

flink-kubernetes-operator/pom.xml

Exclude the vulnerable log4j dependency from curator-test

[FLINK-36450] exclude log4j from curator-test

---

flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/event/JdbcAutoScalerEventHandler.java

Fix that the 'deletedTotalCount' is not updated when cleaning historical event handler records in JDBC event handler
Fix that the 'deletedTotalCount' is not updated when cleaning historical event handler records in JDBC event handler
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

[hotfix][autoscaler] Fix that the 'deletedTotalCount' is not updated when cleaning historical event handler records in JDBC event handler

---

Dockerfile
flink-kubernetes-operator/pom.xml

Rather embarrassingly there is a typo in the new httpclient property luckily as its still un-released we can freely rename it.

[hotfix] typo in property name httpclinent -> httpclient

---

flink-kubernetes-operator-api/pom.xml

The original FLINK-36332 missed a transitive dependency on `kubernetes-httpclient-okhttp` via the flink-kubernetes-operatpr-api which mean anyone choosing an alternative client ended up with both clients on the runtime classpath 😢 
Ensure only requested kubernetes-httpclient is on the runtime classpath.
This change is already covered by existing tests, such as *(please describe tests)

[FLINK-36332] Exclude kubernetes-httpclient form API module.

---

docs/content/docs/operations/upgrade.md

With the usual `helm upgrade`, the new FlinkStateSnapshot CRD won't be installed, and it will need to be installed with `kubectl create`.

[hotfix][docs] Add FlinkStateSnapshot to upgrade docs

---

.github/workflows/ci.yml
.github/workflows/e2e.yaml

As observed in [FLINK-36332](https://github.com/apache/flink-kubernetes-operator/pull/881#issuecomment-2378765602) the CI workflow has become difficult to mange. This PR is attempting to split tests along sensible lines to make the matrix more manageable. 
To do so this PR splits the edge to edge workflow in two. A common workflow definition: [e2e.yaml](https://github.com/apache/flink-kubernetes-operator/pull/893/files#diff-a2de7550554c0198ac7f959c78a19ee0996921c98034411de47a7dd49b0c209b)  which is then reused from multiple different test matrices. 
I think this split allows better control over the variables without having to vary each dimension every time. By making the simplifying assumption that variations in the Java version are adequately tested by the maven builds and the smoke …

[FLINK-36460] Refactoring the CI matrix

---

flink-kubernetes-operator-api/pom.xml
flink-kubernetes-operator/pom.xml
flink-kubernetes-webhook/pom.xml
pom.xml

There is still a stray reference to OkHTTP via the webhook.
- Fully exclude OkHttp
I'd also like to back port this to release-1.10 if possible.

[FLINK-36332] Missed webhook okhttp reference.

---

docs/content.zh/docs/operations/metrics-logging.md
docs/content/docs/operations/metrics-logging.md

This PR is for fixing the name of the metric config which enables the response codes group in "[Metrics and Logging](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/operations/metrics-logging/#kubernetes-client-metrics-by-http-response-code)" doc, to make the naming be consistent with information in "[Configuration](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/operations/configuration/#system-metrics-configuration)" doc.
-  Add operator config prefix `kubernetes.operator.` to make it show the full name of the config
- …

[FLINK-36599] Correct the metric config name in the doc to reduce confusing

---

tools/olm/docker-entry.sh

Bug fix: During OLM bundle creation, the generated bundle lacks necessary file permissions on the CSV.  This leads to a subscription failure.
I added a comment to the JIRA showing the investigation.
* Ensure CSV file permissions are preserved during bundle creation.
Created the OLM bundle locally.

FLINK-36544: [OLM] - ensure file permissions are preserved on the CSV during bundle creation.

---

tools/olm/docker-entry.sh

This pull request fixes a defect ([FLINK-36551](https://issues.apache.org/jira/browse/FLINK-36551))  in `tools/olm/docker_entry.sh`.  In order for Flink Kubernetes Operator to function under OLM the webhook utilises a serving certificate provided by OLM.  docker_entry.sh rewrites the deployment to allow this substitution to occur.
Unfortunately, `docker_entry.sh` makes an assumption about the index of the `keystore` volume within the deployment.  The index has changed over time, meaning  `docker_entry.sh` replaces the wrong volume entry.  This leads to a volume with a duplicate name.  The CSV fails to be become ready as a result.
- [OLM] Fix indexing error when replacing the `keystore` volume within CSV. 
I manually verified the change, firstly by ensuring the `yq` command was having the …

FLINK-36551: [OLM] ensure that docker-entry.sh actually replaces the keystore pod volume

---

docs/layouts/shortcodes/generated/kubernetes_operator_metric_configuration.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkOperatorConfiguration.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/KubernetesOperatorMetricOptions.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetricsFabric8InterceptorTest.java

Adding a simple counter to monitor slow API requests, identifying those that exceed a predefined time threshold, e.g.:
```
kubernetes.client.metrics.slow.request.threshold=5s
```
- Unit tests where added
- Manually can be verified by reducing the threshold to a very low number, e.g.:
```
kubernetes.client.metrics.slow.request.threshold=1 MILLISECOND
```
```
-- Counters ---------------------------------------------------------------------
flink-kubernetes-operator-b48954fcf-w8p4z.k8soperator.default.flink-kubernetes-operator.system.KubeClient.HttpRequest.Slow.Count: 87
```
- Does this pull …

[FLINK-36583] Add Slow Request Kube Client Metrics

---

docs/content.zh/docs/concepts/overview.md
docs/content/docs/concepts/overview.md

Update docs to reflect that v1.20 is supported. 
Currently [this page](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/concepts/overview/) shows that the operator only supports up to Flink v1.19. 
CMIIW but my understanding is that v1.20 support was added as part of https://issues.apache.org/jira/browse/FLINK-36129 and in fact v1.20 is supported since the flink-kubernetes-operator 1.10 release. I'm assuming this was just overlooked in https://github.com/apache/flink-kubernetes-operator/pull/869

[hot-fix][docs] Reflect v1.20 support

---

flink-kubernetes-operator-api/pom.xml
flink-kubernetes-operator/pom.xml
flink-kubernetes-webhook/pom.xml
pom.xml

* Backport a fix (cherry picked from commit c821b48a75c601c3a64bc03bfbada218a68a0e0d) to ensure OKHttp is cleanly excluded from the whole project.
- Ensure that OkHttp is correctly excluded.

[backport][FLINK-36332] Fix okhttp dependency handling

---

docs/content.zh/docs/operations/helm.md
docs/content.zh/docs/operations/metrics-logging.md
docs/content/docs/operations/helm.md
docs/content/docs/operations/metrics-logging.md
helm/flink-kubernetes-operator/conf/log4j-console.properties
helm/flink-kubernetes-operator/conf/log4j-operator.properties

In the [doc](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/operations/metrics-logging/#logging), we didn't explicitly instruct users how to change log level dynamically for operator/job manager/task manager. This is important for troubleshooting, and it is already built-in config in Flink core.
- In `log4j-console.properties` and `log4j-operator.properties` in Helm, added a hint to demo how to set config to change config dynamically.
- In the [doc](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/operations/metrics-logging/#logging), added a hint to demo how to set config to change config dynamically.
- …

[FLINK-36192][log] instruct how to change log level dynamically

---

tools/olm/generate-olm-bundle.sh

The docker container was being run with the uid/gid arguments switched about.
As pointed out by https://issues.apache.org/jira/browse/FLINK-36545, when generating the OLM bundle, the container is run with uid/gid values switched around.
- *Correct uid/gid values used when creating the OLM bundle.*

FLINK-36545: [OLM] fix uid/gid mixup when generating the OLM bundle.

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java

Fix incorrect `messageKey` passed in `ScalingLimited` event. This will cause almost every ScalingLimited event to generate a record, `scaling.event.interval` will not take effect.
Change the calculation method of messagekey to  `SCALING_LIMITED + vertex + newParallelism`
Added test in `JobVertexScalerTest#testSendingScalingLimitedEvents` to test the stability of eventKey when scaleFactor changes do not cause parallelism changes.
- Dependencies (does it add or upgrade a dependency): (yes / no)
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no)
- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / …

[hotfix] Fix incorrect `messageKey` passed in `ScalingLimited` event

---

flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/state/JdbcAutoScalerStateStore.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/DelayedScaleDown.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/DelayedScaleDownTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/state/AbstractAutoScalerStateStoreTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStore.java

Get more details from FLINK-36535.
[FLINK-36535][autoscaler] Optimize the scale down logic based on historical parallelism
1. Using the maximum parallelism within the window instead of the latest parallelism when scaling down
2. Never scale down when (currentTime - triggerTime) < scale-down.interval
- Added the DelayedScaleDownTest
- Rewrite the `testRequiredScaleDownAfterInterval` to `testScaleDownAfterInterval`
- Update the `AbstractAutoScalerStateStoreTest`, `JobVertexScalerTest` and `ScalingExecutorTest`
- Does this pull request …

[FLINK-36535][autoscaler] Optimize the scale down logic based on historical parallelism to reduce the rescale frequency

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

The observedGeneration field wasn't updated anymore when the spec update results in a NOOP reconciliation.
This is a regression of a10fb4501011be4e88fb6164156e3b9e8527950e / https://github.com/apache/flink-kubernetes-operator/pull/834

[FLINK-36890] Update observedGeneration on NOOP reconciliation

---

NOTICE
flink-autoscaler-standalone/src/main/resources/META-INF/NOTICE
flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
flink-kubernetes-standalone/src/main/resources/META-INF/NOTICE
flink-kubernetes-webhook/src/main/resources/META-INF/NOTICE
tools/license/NOTICE-binary_PREAMBLE.txt

Hi @mxm ,Now that it's 2025,maybe we should update NOTICE files.Please take a look in your spare time,thank you!
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens …

[hotfix][docs] Add 2025 on NOTICE

---

flink-autoscaler-plugin-jdbc/src/main/java/org/apache/flink/autoscaler/jdbc/state/JdbcAutoScalerStateStore.java
flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutor.java
flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/StandaloneAutoscalerExecutorTest.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/NoopJobAutoscaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/AutoScalerStateStore.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/state/InMemoryAutoScalerStateStore.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/state/KubernetesAutoScalerStateStore.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java

The autoscaler cleanup logic currently does not actually delete the state of the job from the state store only the cache. This can cause leaks in some cases and unintended retrieval of wrong state if the job is deleted then restarted.
- Change cleanup to clearAll and flush state store
- tests
Unit tests have been extended to cover this more.

[FLINK-37086] Clean up should remove all autoscaler state

---

docs/content/docs/custom-resource/reference.md
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/JobSpec.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractFlinkResourceReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

The main purpose is to allow users to easily and explicitly clear all autoscaler state and parallelism overrides.
Currently users need to toggle the autoscaler on/off to clear the parallelism settings which relies on implicit internal behaviour and is not always easy to execute safely. Unfortunately the on-off workaround requires 2 spec changes which need to be submitted carefully one after the other as the operator may only look at the 2nd one and then nothing happens.
- *Add autoscalerResetNonce to jobSpec*
- *Tests*
New unit tests have been added to cover the reset logic
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: yes
- Does this …

[FLINK-36640] Add autoscalerResetNonce to jobSpec

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricEvaluator.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingMetricEvaluatorTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

detail: FLINK-36836 
- *Introduce two new parameters `job.autoscaler.utilization.min` and `job.autoscaler.utilization.max` to determine the upper and lower limits of utilization*
- Change the previous test cases related to `job.autoscaler.target.utilization.boundary` to `job.autoscaler.utilization.min` and `job.autoscaler.utilization.max` 
- add test `ScalingExecutorTest#testUtilizationBoundariesAndUtilizationMinMaxCompatibility` Verify compatibility of parameters before and after
- Dependencies (does it add or upgrade a dependency): (yes / *no*)
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / *no*)
- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the …

[FLINK-36836][Autoscaler] Supports config the upper and lower limits of target utilization

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/DelayedScaleDown.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/BacklogBasedScalingTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/DelayedScaleDownEndToEndTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/DelayedScaleDownTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/RecommendedParallelismTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingExecutorTest.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/state/AbstractAutoScalerStateStoreTest.java

[FLINK-36863][autoscaler] Use the maximum parallelism in the **_past scale-down.interval window_** when scaling down instead of  in the entire past
See more details from FLINK-36863.
VertexDelayedScaleDownInfo maintain all recommended parallelisms at each time within the past scale-down.interval window period.
- Evicts the recommended parallelism before the scale-down.interval window.
- The max parallelism within the window range as the final parallelism.
- It is similar with [leetcode 239: Sliding Window Maximum](https://leetcode.com/problems/sliding-window-maximum/description/).
- If latest parallelism is greater than the past parallelism, the past parallelism never be the max value, so we could evict all smaller parallelism in the past.
- We only need to maintain a list with …

[FLINK-36863][autoscaler] Use the maximum parallelism in the past scale-down.interval window when scaling down

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManagerTest.java

Use concurrent hashmap to avoid reconciliation errors during initialization 
Unit test added

[FLINK-37166] Use concurrenthashmap in flink config manager

---

flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/lifecycle/ResourceLifecycleState.java
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/CommonStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/config/FlinkConfigBuilderTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkDeploymentController.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/TestingFlinkSessionJobController.java
helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml

The current lifecycle states and events don't properly track resources that are being deleted. Long / stuck delete operations do not result in intuitive states.
This changes introduces 2 new states, deleting and deleted to track the deletion process. Once a resource is marked for deletion it will always return DELETING until the deletion success which will return a one time DELETED state (but this will only be seen as an event as the deleted resource won't be in kubernetes anymore)
- Introduce new states and update reconciler logic
- tests 
Tests, and validation in various envs
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: yes
- Does this …

[FLINK-37229] Add/record DELETING/DELETED lifecycle states

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetrics.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetricsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointStatistics.java

This adds state size, i.e. the size of the last completed checkpoint, to the
deployment status. It also exposes the state size as a deployment metric.

[FLINK-37253] Add state size in application status and deployment metrics

---

.github/workflows/docker_push.yml

The latest [qemu docker image release ](https://hub.docker.com/r/tonistiigi/binfmt) seemingly broke our docker builds. Rolling back and pinning the latest working version (`v7.0.0`)
CI
no

[FLINK-37359] Pin qemu image to 7.0.0

---

examples/autoscaling/autoscaling-dynamic.yaml
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java

Currently autoscaler metrics although collected are not published during stabilization period. We report metrics after the stabilization period only. In practice this could result in larger gaps in metric charts during scale operations that makes it hard for end users to interpret. The metrics could appear to be broken, especially when multiple scale operations executed in a row, for example:
This change mitigates this issue by shortening the gaps in reported metrics. The collected metrics won't be withhold during stabilization period either.
- Removing the logic to report no metrics during stabilization
- Adjusted the logging to better understand the stabilization/metric window periods
- Update the timestamp format to contain millis (unit tests operate with millis)
```
2025-02-17 …
```

[FLINK-36409] Publish some autoscaler metrics during stabilisation period

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java

This pull request fixes a bug where the observer tries changing the JOB STATUS of a FINISHED finite/bounded streaming job back to RECONCILING if the JM is MISSING.
Wraps [AbstractFlinkDeploymentObserver.observeJmDeployment](https://github.com/apache/flink-kubernetes-operator/blob/main/flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java#L155) in an if-statement that only executes if the job is NOT in a terminal state.
- Tested locally
- Unit test to guard against accidental future regression
- Core observer or reconciler logic that is regularly executed: Yes
- Does this pull …

[FLINK-37320] [Observer] FINISHED finite streaming jobs incorrectly being set to RECONCILING

---

flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
pom.xml

1.20.1 is available in mvn repo. It fixed several of bugs, and we always use the .1 (patch version) as the dependency to avoid some potential bugs.
[FLINK-37236] Bump the flink version from 1.20.0 to 1.20.1

[FLINK-37236] Bump the flink version from 1.20.0 to 1.20.1

---

.github/workflows/ci.yml
.github/workflows/e2e.yaml
e2e-tests/data/flinkdep-batch-cr.yaml
e2e-tests/test_batch_job.sh
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java

This pull request is a follow-up to https://github.com/apache/flink-kubernetes-operator/pull/948. It corrects the exception that is caught from `org.apache.flink.runtime.rest.util.RestClientException` to `java.util.concurrent.ExecutionException`.
To make batch testing more robust, I have also introduced a batch e2e test with this PR.
* Updates the Exception and corresponding test
* Introduces a batch e2e test for the operator that uses the bundled Flink WordCount example
* Existing tests
* Newly added batch e2e test
* Tested locally with Minikube and the batch manifest in the JIRA ticket
- …

[FLINK-37370] [Observer] Fix exception caught when handling checkpointing not enabled for batch jobs and add batch e2e test

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/mutator/FlinkResourceMutator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/AbstractFlinkResourceObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SnapshotTriggerTimestampStore.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/ExceptionUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/SnapshotUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/FlinkResourceValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ExceptionUtilsTest.java

The operator often hides the actual issue for deployment errors and do not correctly report the error events.
We are reporting the first 3 possible exceptions in the exception hierarchy in the error events.
- Added new unit tests

[FLINK-37430] Operator hides the actual error on deployment issues

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java

There was a breaking change introduced between 2.0 preview and 2.0 to the HA metadata handling that breaks the last-state upgrade mode.
https://github.pie.apple.com/IPR/apache-flink/commit/292d7f449db89c662c60b265ed99e33416dba614
- *Change logic to be aware of execution plans and job graphs as well*
e2s and new unit test

[FLINK-37571] Fix JobGraph removal for 2.0 last-state upgrades

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java

Change the observer to only verify that at least one JM is available before trying to query it.
Adapted unit tests

[FLINK-37562] Do not check all JM replicas in observer

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java

Do not send autoscaler configs to the Flink Job
unit test

[hotfix] Do not leak autoscaler configs to jobs

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventRecorder.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/ExceptionUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/JobStatusObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/ExceptionUtilsTest.java

Currently we set the error status when the job terminally fails but no event is triggered. We use the recently improved exception utilities to present a nice error message.
- *Trigger event on failed jobs*
- *Use recent improvements in error message handling to improve other event reporting* 
Unit and manual tests

[FLINK-37455] Create error Event when job goes into FAILED state

---

flink-kubernetes-operator/pom.xml
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/exception/DeploymentFailedException.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractFlinkDeploymentObserver.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/exception/DeploymentFailedExceptionTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/PodErrorTest.java

The operator correctly reacts to certain type of pod errors such as image pull/crash loop when they happen on main / sidecar containers. 
However these errors are ignored on initcontainers. Furthermore, volume mount errors which do not manifest in clear container error statueses are not recorded at all. 
This PR aims to collectively fix this and greatly improve startup error handling
- *Check and catch all container and init container error statuses*
- *Add special logic to handle common volume mount errors based on pod events in case of failed startup*
New unit tests + manually verified on different local and prod envs
- Core observer or reconciler logic …

[FLINK-37470] Improve JobManager Deployment / Pod error handling

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

During the change to the snapshot resource logic we removed the logic that adds the upgrade savepoints to the old savepoint info status field and history. This causes inconsistencies for those who are still using that feature.
Simply record upgrade savepoint in deprecated savepoint info to keep consistent 
Unit tests

[FLINK-37530] Record upgrade savepoint correctly in savepointInfo as well

---

pom.xml

Bump commons-io from 2.11.0 to 2.17.0
Bump cyclonedx-maven-plugin from 2.7.9 to 2.9.0 to remediate the findings in the dependant packages.
**Vulnerabilities from dependencies:**
[CVE-2024-38374](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-38374)
**Package details:**
https://mvnrepository.com/artifact/org.cyclonedx/cyclonedx-maven-plugin/2.9.0

[FLINK-36767] Bump cyclonedx-maven-plugin from 2.7.9 to 2.9.0

---

.github/workflows/publish_snapshot.yml

Update version of used github actions in publish-snapshot.yaml
- *Update cache, setup java and checkout to version 4*

Update publish-snapshot workflow actions

---

docs/content.zh/docs/custom-resource/autoscaler.md
docs/content/docs/custom-resource/autoscaler.md

Fix typos
- Fix typos in autoscaler docs
Trivial work
It only affects documentation.
- Does this pull request introduce a new feature? **No**
- If yes, how is the feature documented? **Not applicable**

[hotfix][docs] typo Adaptvie/Adaptive and booleans in autoscaler docs

---

helm/flink-kubernetes-operator/templates/flink-operator.yaml
helm/flink-kubernetes-operator/values.yaml

Customization points for init and side car containers to the helm chart, which are common in non-trivial deployments.

[FLINK-37662][helm] Support init and side car containers

---

docs/layouts/shortcodes/generated/auto_scaler_configuration.html
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobVertexScaler.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/config/AutoScalerOptions.java
flink-autoscaler/src/main/java/org/apache/flink/autoscaler/utils/AutoScalerUtils.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobVertexScalerTest.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java

Currently, target parallelism computation assumes perfect linear scaling. However, real-time workloads often exhibit nonlinear scalability due to factors like network overhead and coordination costs.
This change introduces an observed scalability coefficient, estimated using linear regression on past (parallelism, processing rate) data, to improve the accuracy of scaling decisions.
Implemented a dynamic scaling coefficient to compute target parallelism based on observed scalability. The system estimates the scalability coefficient using a least squares linear regression approach, leveraging historical (parallelism, processing rate) data.
The regression model minimises the sum of squared errors. The baseline processing rate is computed using the smallest observed parallelism in the …

[FLINK-30571] Estimate scalability coefficient from past scaling history using linear regression

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/health/ClusterHealthInfo.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthResult.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/health/ClusterHealthInfoTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthEvaluatorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/ClusterHealthResultTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java

This PR is a feature improvement to include cause in event when restarting unhealthy job:
Before:
```
2025-05-15 14:08:52,863 o.a.f.k.o.l.AuditUtils         [INFO ][default/basic-example] >>> Event[Job]       | Warning | RESTARTUNHEALTHYJOB | Restarting unhealthy job
```
After:
```
2025-05-15 14:08:52,863 o.a.f.k.o.l.AuditUtils         [INFO ][default/basic-example] >>> Event[Job]       | Warning | RESTARTUNHEALTHYJOB | Restart count hit threshold: 1
```
- A new class `ClusterHealthResult` is introduced to store information about the job health and error message
This change added unit tests and can be verified as follows:
- Manually built image and run on local `minikube`
- Verified `ClusterHealthResult` is serialised and deserialised correctly by observer
```
2025-05-15 14:09:50,968 …
```

[FLINK-37769] Include cause in event when restarting unhealthy job

---

flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/CommonStatus.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/AbstractJobReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingFlinkService.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/DeploymentRecoveryTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/lifecycle/ResourceLifecycleMetricsTest.java

*Currently the lifecycle state shows STABLE even if an application deployment was deleted and stays in MISSING / reconciling state. This would fix the lifecycle status of the deployment which would be FAILED in cases when the JM is in MISSING/ERROR state with ERROR: `configmaps have been deleted` indicating TERMINAL error.*
- *Added logic to detect unrecoverable `FlinkDeployment `scenarios*
- *Inserted after existing job status FAILED check*
- *Checks for `JobManagerStatus`:
- *MISSING JobManager Deployment with error `({"type":"org.apache.flink.kubernetes.operator.exception.UpgradeFailureException","message":"HA metadata not available to restore from last state. It is possible that the job has finished or terminally failed, or the configmaps have been deleted. …

[FLINK-32033][Kubernetes-Operator] Fix Lifecycle Status of FlinkDeployment Resource in case of MISSING/ERROR JM status

---

flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
helm/flink-kubernetes-operator/values.yaml
pom.xml

This release fixes an issue with resource indexing on startup:
https://github.com/operator-framework/java-operator-sdk/pull/2881
What does not necessarily create issues in practice, but can lead to inconsistent behavior 
Bump JOSDK version to 5.1.2
Bump JOSDK version to 5.1.2
- Dependencies (does it add or upgrade a dependency): yes 

[FLINK-38207] Update Flink Operator to use JOSDK 5.1.2

---

flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconciler.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventSourceUtils.java
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/IngressUtils.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/FlinkOperatorTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/SessionReconcilerTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/IngressUtilsTest.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/TestingJosdkContext.java

In this alternative, ingress is bound to the CR, not to the job, for proper deletion of the added informer.
Note that this has a side effect, that if job is suspended, the ingress still will be present. What actually might not be a bad thing. (If the users intention is to resume the job)
There are cases where we might want to re-create, for example, in `className` changes. But we can take care of this if needed in a subsequent PR.
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and …

[FLINK-37193] Ingress recreated after perform a change to CR FlinkDeployment

---

docs/content.zh/docs/operations/configuration.md
docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
docs/layouts/shortcodes/generated/system_section.html
flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java

The current documentation for dynamic namespace watching configuration was unclear and led to users raising a couple of tickets - FLINK-37887, FLINK-37391. This PR clarifies the same.
- Add example configuration for enabling dynamic namespace watching
- Clarify that dynamic.namespaces.enabled requires dynamic.config.enabled to be true
- If yes, how is the feature documented? (docs)

[FLINK-37391][docs] Improve documentation for dynamic namespace watching configuration

---

examples/advanced-ingress.yaml
examples/autoscaling/autoscaling-dynamic.yaml
examples/autoscaling/autoscaling.yaml
examples/basic-checkpoint-ha.yaml
examples/basic-ingress.yaml
examples/basic-reactive.yaml
examples/basic-session-deployment-only.yaml
examples/basic.yaml
examples/custom-logging.yaml
examples/flink-beam-example/beam-example.yaml
examples/flink-python-example/python-example.yaml
examples/flink-sql-runner-example/sql-example.yaml
examples/flink-tls-example/basic-secure-deployment-only.yaml
examples/flink-tls-example/basic-secure-session-job-only.yaml
examples/flink-tls-example/basic-secure.yaml
examples/pod-template.yaml
examples/snapshot/job-from-savepoint.yaml

Update samples to use yaml based configs instead of key/value pairs
Updates samples
Such change is already tested in e2e test in PR:
https://github.com/apache/flink-kubernetes-operator/pull/1013

[FLINK-37406] Update examples to use yaml based configs

---

.asf.yaml
flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/ConfigObjectNode.java
flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/spec/ConfigObjectNodeTest.java

Fixes serialization of array values:
```yaml
a: 1
b: 
c: [1,2]
```
now becomes:
```
a: 1
b.c: 1;2
```
This change added tests;

[FLINK-37406] Fix config array serialization

---

flink-kubernetes-operator/src/main/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistory.java
flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java

This PR adds fixes compatibility issue when listing exceptions for Flink v.1.17 jobs
- Allow nullable `failureLabels` in `JobExceptionsInfoWithHistory`
- Added additional unit test in `AbstractFlinkServiceTest` that simulates Flink v1.17 API response

[FLINK-38148][FlinkService] Support Flink v1.17 when listing job exceptions

---

docs/content.zh/docs/concepts/overview.md
docs/content/docs/concepts/overview.md

Fill out the template below to describe the changes contributed by the pull request. That will give reviewers the context they need to do the review.
* In Flink Kubernetes Operator version 1.11, the contents overview does not specify support for Flink 2.0. Therefore, I have added v2_0 to the doc files at the following two paths. *
* /flink-kubernetes-operator/docs/content/docs/concepts/overview.md
* /flink-kubernetes-operator/docs/content.zh/docs/concepts/overview.md
> flink kubernetes operator 1.11 spec FlinkVersion code
* Dependencies (does it add or upgrade a dependency): no
* The public API, i.e., is any changes to the CustomResourceDescriptors: no
* Core observer or reconciler logic that is regularly executed: …

[hotfix][docs] Pull request to update documentation for Flink 2.0 support. (v 1.11)

---

pom.xml
tools/maven/checkstyle.xml

Update checkstyle so it supports newer Java language features like text blocks, etc.
Updated checkstyle maven plugin and related rules.
Run the build, it passes. Try to use a text block in a unit test for exmaple, now passes the build, unlike before.
- Dependencies (does it add or upgrade a dependency): yes 

[FLINK-38293] Update Checkstyle version and related rules in Kubernetes Operator

---

flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingMetricCollector.java
flink-autoscaler/src/test/java/org/apache/flink/autoscaler/MetricsCollectionAndEvaluationTest.java

When using the DynamicKafkaSink, topics can be spread across multiple clusters. This used to work fine, but a regression has been added which considers partitions across different clusters to be identical. This limits the scale out of the source operator.
Here is an example:
```
"1.Source__Kafka_Source_(testTopic).kafkaCluster.my-cluster-1.KafkaSourceReader.topic.testTopic.partition.0.currentOffset",
"1.Source__Kafka_Source_(testTopic).kafkaCluster.my-cluster-2.KafkaSourceReader.topic.testTopic.partition.0.currentOffset"
```
Those would result be treated as one partition, but there are two partitions from separate Kafka clusters.

[FLINK-38381] Enumerate Kafka partitions across Kafka clusters
