apache/flink-kubernetes-operator

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultDeploymentValidator.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DeploymentValidatorTest.java
- Use `HighAvailabilityMode.isHighAvailabilityModeActivated()` to improve the check process of HA mode
- This PR is a followup of #29
> [FLINK-26405] Improve the check of HA mode

- flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandler.java
The current webhook implementations accept requests on all paths and execute validations, which should restrict this to only /validate and log errors on other rest paths.
- `AdmissionHandler` adds the check whether the request path is equal to `/validate` and the log of the error on other rest paths.
> [FLINK-26508] Webhook should only validate on /validate endpoint end log errors for others

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/Mode.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentController.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/BaseObserver.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobObserver.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/Observer.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/ObserverFactory.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/SessionObserver.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/JobReconciler.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/JobObserverTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/SessionObserverTest.java
This PR is mean to extract the `Observer` interface to simplify the observe logic. The main logic is aligned to the `Reconciler` interface
> [FLINK-26546] Extract Observer Interface

- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
The controller test currently uses the `KubernetesMockserver` directly. We could try to use `@EnableKubernetesMockClient(crud = true)` in the `FlinkDeploymentControllerTest` test.
- Adds the `@EnableKubernetesMockClient(crud = true)` annotation to `FlinkDeploymentControllerTest` and removes the `KubernetesMockserver` and `KubernetesClient` start and stop.
> [FLINK-26552] Try to use @EnableKubernetesMockClient(crud = true) in controller test

- .github/workflows/docs.sh
- .github/workflows/docs.yaml
Based on zentol's work in https://github.com/apache/flink/pull/19103/commits/54678bbe907d6f0dc70da226b0209e38fa06c59e.
> [FLINK-26612] Documentation build via GitHub actions

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/JobObserver.java
> [FLINK-26696] Reuse the method of judgment

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilder.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkConfigBuilderTest.java
This is intended to solve some problems encountered when watching specific / multiple namespaces.
cc @mbalassi @wangyang0918
> [FLINK-26676] Make ClusterIP the default rest service type

- docs/content/docs/try-flink-kubernetes-operator/quick-start.md
> chore - fix docs

- .github/workflows/ci.yml
> [FLINK-26795] Fix the CI not fail fast after build failed

- docs/content/docs/operations/ingress.md
- document ingress templates
-  host based routing
-  domain based routing
> [FLINK-26817] Update ingress docs with templating examples

- docs/content/_index.md
- docs/content/docs/try-flink-kubernetes-operator/quick-start.md
> [FLINK-26862] Link the Github repository from Operator documentation

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingClusterClient.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/FlinkServiceTest.java
This PR allows to pick the savepoint directory in the flink config instead of `null` when trigger savepoint. After this PR, upgrading FlinkDeployment from stateless to savepoint could actually work.
> [FLINK-26881] Pick up the savepoint directory in the flink config when trigger savepoint

- tools/releasing/create_source_release.sh
This is the logic I have used to create the first RC, formalizing in a script here
> Add helm packaging to create_source_release.sh script

- flink-kubernetes-operator/pom.xml
- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.automaton
- flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.checker-qual
- flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.kryo
- flink-kubernetes-operator/src/main/resources/META-INF/licenses/LICENSE.minlog
- pom.xml
Backport #125 to release-0.1 branch
> [BP-0.1] [FLINK-26903] Add correct NOTICE file to flink-kubernetes-operator

- .github/workflows/docs.yaml
Also limits nightly build only to relevant branches. Should be merged to `release-0.1` too.
> [FLINK-26991][docs] Limits docs build to main repo

- docs/content/_index.md
Should be merged to `release-0.1` too.
> [FLINK-26934] Initial meetup recording added to docs

- .github/workflows/docs.yaml
Missed this in my previous PR.
> [FLINK-26991][docs] Fix GitHub action building correct branch

- docs/content/docs/operations/configuration.md
- Backport #150 for [FLINK-26611] Document operator config options
> [BP][FLINK-26611] Document operator config options

- docs/content/docs/concepts/overview.md
- docs/content/docs/operations/helm.md
- docs/content/docs/try-flink-kubernetes-operator/quick-start.md
This should be merged after the 0.1.0 release
> [FLINK-26959] Simplify quickstart

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/SessionReconciler.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/SessionReconcilerTest.java
Bp for https://github.com/apache/flink-kubernetes-operator/pull/145
> [BP][FLINK-26996] Break the reconcile after first create session cluster

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java
The error will occur if we use the operator with namespaced scope.
```
[WARN ] Error starting org.apache.flink.kubernetes.operator.controller.FlinkSessionJobController$1@96a75da
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.16.0.1/apis/flink.apache.org/v1alpha1/namespaces/flink-operator/flinkdeployments. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. flinkdeployments.flink.apache.org is forbidden: User "system:serviceaccount:flink-operator:flink-operator" cannot list resource "flinkdeployments" in API group "flink.apache.org" in the namespace "flink-operator".
```
> [FLINK-27098] hotfix: Fixes the createFlinkDepInformerEventSource namespace scope

- docs/content/docs/operations/helm.md
- examples/kustomize/kustomization.yaml
- examples/kustomize/patch.yaml
- examples/kustomize/render
- examples/kustomize/values.yaml
- adding basic example and docs for pod augmentation using Helm + kustomize
> [FLINK-26663] Pod augmentation for the operator

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/FlinkService.java
This pr is meant to clean up the jar file after submitting the job to avoid the jar files exploding after serval upgrade
> [FLINK-27269] Clean up the jar file after submitting the job

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsTest.java
This PR tries to fix the potential NPE in `deleteJobGraphInKubernetesHA` and avoid the unnecessary ConfigMap update.
> [FLINK-27358] Fix NPE and avoid unnecessary configmap update

- docs/content/docs/custom-resource/reference.md
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/AbstractFlinkSpec.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/spec/FlinkDeploymentSpec.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/FlinkSessionJobReconcilerTest.java
- helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
- helm/flink-kubernetes-operator/crds/flinksessionjobs.flink.apache.org-v1.yml
This pr is meant to support restartNonce in session job
> [FLINK-27362] Support restartNonce semantics in session job

- docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/FlinkConfigManager.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/config/KubernetesOperatorConfigOptions.java
This adds the missing cleanup logic + makes size/expiration configurable
> [FLINK-27303] Improve config cache settings + add cleanup

- examples/basic-session-job.yaml
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/CrdConstants.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
- flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandler.java
- flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/FlinkValidator.java
- flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/admissioncontroller/AdmissionController.java
- flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/admissioncontroller/validation/DefaultRequestValidator.java
- flink-kubernetes-webhook/src/main/java/org/apache/flink/kubernetes/operator/admission/admissioncontroller/validation/Validator.java
- flink-kubernetes-webhook/src/test/java/org/apache/flink/kubernetes/operator/admission/AdmissionHandlerTest.java
- helm/flink-kubernetes-operator/templates/webhook.yaml
This PR is meant to complete the validator for flink session job. This also enables the webhook for session job.
> [FLINK-27262] Enrich validator for FlinkSessionJob

- docs/content/docs/operations/helm.md
All the configurable parameters of the helm chart and their default values are needed to document, which could be put in the helm section.
- Documents all the configurable parameters of the helm chart and their default values.
> [FLINK-27008] Document the configurable parameters of the helm chart and their default values

- docs/content/docs/concepts/overview.md
- Restructured the feature summary
- Added links for quick access
- Added Known issues and limitations
> [FLINK-27645] Update overview / supported features page for 1.0.0

- tools/releasing/update_branch_version.sh
We also need to change version of documentation in `update_branch_version.sh`.
> [hotfix] Change version of documentation in update_branch_version.sh

- docs/content/docs/operations/metrics-logging.md
Added Operator specific metrics description
> [FLINK-27647] Improve Metrics documentation to include newly added metrics

- docs/content/docs/operations/helm.md
- Improve the documents of `Watching only specific namespaces` part in `helm.md` to introduce how to make webhook work as expected using different k8s versions.
> [FLINK-27615] Document how to define namespaceSelector for k8s operator's webhook 

- .dockerignore
- Dockerfile
Signed-off-by: tison <wander4096@gmail.com>
> [FLINK-27834] Copy all files except those filtered by .dockerignore

- helm/flink-kubernetes-operator/templates/flink-operator.yaml
Let us also merge this to `release-1.0`. I did not find an easy way to automatically test this, but I verified it manually.
> [FLINK-27956][helm] Operator deployment uses recreate strategy

- docs/content/docs/operations/helm.md
- helm/flink-kubernetes-operator/templates/flink-operator.yaml
- helm/flink-kubernetes-operator/values.yaml
This is in addition to the already merged custom annotations, plus adds missing documentation.
> [FLINK-27788] Custom labels for the operator pod

- flink-kubernetes-operator/pom.xml
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/CrdCompatibilityChecker.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/CrdCompatibilityCheckerTest.java
Add automated CRD compatibility check logic to the maven build comparing against the 1.0.0 release.
Manually verified + unit tests added for the cases covered by the checker
> [FLINK-26955] Add CRD compatibility check to maven build

- docs/content/docs/operations/helm.md
- helm/flink-kubernetes-operator/templates/rbac.yaml
- helm/flink-kubernetes-operator/values.yaml
Removed un-used apiGroup and resources from required RBAC
Signed-off-by: Jeesmon Jacob <jjeesmon@vmware.com>
> [FLINK-27975] Remove unnecessary RBAC rules from operator

- docs/config.toml
Updating config file with adding 0.1 doc to the previous doc versions
> [FLINK-28396] Updating config file with previous doc version

- examples/flink-sql-runner-example/sql-scripts/simple.sql
- examples/flink-sql-runner-example/sql-scripts/statement-set.sql
Improves the current examples, so that they launch streaming jobs. Tested locally. Screenshot if the statement set job below.
> [FLINK-27009] Long running SQL example jobs

- .github/PULL_REQUEST_TEMPLATE.md
I have started from the template in the main Flink repo and made some simplification given the smaller scope of the project.
Let me know if you prefer to make the guide more concise.
> [FLINK-28447] GitHub Pull Request template

- docs/content/docs/operations/helm.md
- docs/content/docs/try-flink-kubernetes-operator/quick-start.md
- docs/layouts/shortcodes/stable_branch.html
Remove hardcoded versions from quickstart and set it based on site config.
Manually verified
> [FLINK-28616][doc] Make quickstart versions references dynamic based on config

- docs/layouts/shortcodes/generated/kubernetes_operator_config_configuration.html
- docs/layouts/shortcodes/generated/system_section.html
- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/OperatorJosdkMetricsTest.java
- pom.xml
> [FLINK-28792] Upgrade to JOSDK 3.1.0

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/crd/status/ReconciliationStatus.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/deployment/AbstractDeploymentObserver.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserver.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationMetadata.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/ReconciliationUtils.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/controller/FlinkDeploymentControllerTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/ApplicationObserverTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/deployment/SessionObserverTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/observer/sessionjob/SessionJobObserverTest.java
> [backport][FLINK-28845] Do not ignore initialSavepointPath if first deploy fails completely

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconciler.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/deployment/ApplicationReconcilerTest.java
Allow for upgrade of deployment with stateful upgrade mode that initially fails due to a non-recoverable error, just like it would be the case when the deployment ever reached stable spec.
Check for presence of stable spec before executing logic that assumes existing state.
Added test for spec change before stable spec for all upgrade modes.
Tested manually by creating deployments with image pull error for SAVEPOINT and LAST_STATE upgrade modes. Verified that in either case spec update to valid image is reconciled and deployment becomes stable.
- Dependencies (does it add or upgrade a dependency): (**no**)
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (**no**)
- Core observer or reconciler logic that is regularly executed: (**yes**)
- Does this pull request …
> [FLINK-29100] Relax upgrade checks to allow stateless restart when no stable spec is present

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/FlinkOperator.java
- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- pom.xml
Java Operator SDK has released [3.2.2](https://github.com/java-operator-sdk/java-operator-sdk/releases/tag/v3.2.2) version, which fixes config service override executor service concurrent reconciliation numbers . Bump the JOSDK version to 3.2.2.
cc @csviri 
- Bump the JOSDK version to 3.2.2
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)
> [FLINK-28574] Bump the JOSDK version to 3.2.2

- helm/flink-kubernetes-operator/conf/flink-conf.yaml
Remove some unnecessary configs from the helm defaults
clean up default flink conf
> [hotfix] Remove strange configs from helm defaults

- examples/kubernetes-client-examples/README.MD
- examples/kubernetes-client-examples/pom.xml
- examples/kubernetes-client-examples/src/main/java/org/apache/flink/examples/Basic.java
- pom.xml
* update docs to create and delete deployment via code
- Updated quickstart.md
> [FLINK-29165][docs] update docs to create and delete deployment via code

- docs/content/docs/custom-resource/job-management.md
- docs/content/docs/operations/configuration.md
- docs/content/docs/operations/helm.md
- docs/content/docs/operations/ingress.md
- docs/content/docs/operations/metrics-logging.md
- docs/content/docs/operations/upgrade.md
- docs/content/docs/try-flink-kubernetes-operator/quick-start.md
In accordance with https://flink.apache.org/contributing/docs-style.html#voice-and-tone.
> [hotfixt][docs] Remove all "simply/easily" usages

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/sessionjob/SessionJobReconciler.java
Add the `jobID` in the session job cleanup error message.
> This will be a bit useful for us to delete it manually by Flink TM restful API
Add the `jobID` in the session job cleanup error message
> [FLINK-29561] Add job id in the cleanup job failed message.

- helm/flink-kubernetes-operator/templates/flink-operator.yaml
- helm/flink-kubernetes-operator/values.yaml
Signed-off-by: Jeesmon Jacob <jjeesmon@vmware.com>
Support for `nodeSelector` in helm chart to scope operator deployment to specific nodes
- Support nodeSelector in helm template for flink operator deployment
Tested with `helm template` command to make sure `nodeSelector` is added to Deployment when `nodeSelector` is set in values.yaml
> [FLINK-29632] Support nodeSelector in helm template for flink operator deployment

- examples/flink-python-example/Dockerfile
*Added improvements in the dockerfile for the python example. This change decouples the tight binding with flink minor version in the dockerfile.*
- Added improvements on the flink python example Dockerfile
This change is a trivial rework / code cleanup without any test coverage. Just fixed the example flink python docker file.
> Added improvements on the flink python example Dockerfile

- docs/content/docs/operations/helm.md
Add missing values entry in helm doc
- Helm document update for nodeSelector
> [hotfix][doc] Update missing doc entry for nodeSelector

- .asf.yaml
See also https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection
> [hotfix] Prevent release branches from deleted and force pushes

- .github/workflows/docs.sh
* The current version is two years old, consider upgrading to the latest stable version.I upgraded the version of hogo to version 0.104.0.
* I have modified some files in the _.github/workflows/docs.sh_ directory.
*I checked the changes.*
> [FLINK-29955] Upgrade hogo version to v0.104.0

- examples/flink-sql-runner-example/pom.xml
- examples/kubernetes-client-examples/pom.xml
> [FLINK-29798][build] Exclude example modules from maven deploy phase

- docs/content/docs/operations/metrics-logging.md
* Keep the yaml format consistent.
* I have modified some files in the _.github/workflows/docs.sh_ directory.
*I checked the changes.*
> [hotfix][doc] keep the yaml format consistent

- e2e-tests/utils.sh
Multi session job test is silently not checking the operator log for errors:
```
Checking for operator log errors...
error: You must provide one or more resources by argument or filename.
Example resource specifications include:
'-f rsrc.yaml'
'--filename=rsrc.json'
'<resource> <name>'
'<resource>'
No errors in log files.
```
The issue is that `test_multi_sessionjob.sh` changes the default namespace but the operator pod find functionality not considered namespace changes. In this PR I've fixed that.
* Consider namespace when getting operator pod
* Fixed indentation couple of places
* Error check added in `get_jm_pod_name`
- Core …
> [FLINK-30187] Get operator log considering namespace

- .github/workflows/docs.sh
- docs/config.toml
- flink-kubernetes-operator-api/pom.xml
- flink-kubernetes-operator/pom.xml
- pom.xml
> [FLINK-27037] Add Javadocs publishing to docs generation

- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/StandaloneFlinkServiceTest.java
Follow up to https://github.com/apache/flink-kubernetes-operator/pull/468
test only change
updated unit test
no change
> [FLINK-30287] add unit test

- docs/content/docs/concepts/overview.md
> [docs] Update Known issues for v1.3

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/validation/DefaultValidator.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/validation/DefaultValidatorTest.java
The PR adds validation for flinkVersion changes on SUSPENDED application. If the flinkVersion is changed for an application that was suspended with last-state upgrade mode (relying on the HA metadata) this may lead to state loss depending on the flink version.
This validation is necessary to avoid unintentional state loss. 
If the user wants to change the flink version in these cases, they first have to restart the job with the old version then perform the upgrade from that state or use a savepoint.
- *Added required validation & tests*
New validator unit tests added to check the version change scenarios. …
> [FLINK-30527] Validate flinkVersion change for suspended jobs

- docs/content/docs/custom-resource/autoscaler.md
- examples/autoscaling/autoscaling.yaml
Minor improvement for the autoscaler doc page + example yaml
> [docs] Autoscaler doc and example improvement

- NOTICE
- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- flink-kubernetes-standalone/src/main/resources/META-INF/NOTICE
- flink-kubernetes-webhook/src/main/resources/META-INF/NOTICE
- tools/license/NOTICE-binary_PREAMBLE.txt
> [hotfix] Add year 2023 to Notice files

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobAutoScaler.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/JobVertexScaler.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/RestApiMetricsCollector.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingExecutor.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricCollector.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/ScalingMetricEvaluator.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/KubernetesClientUtils.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/KubernetesClientUtilsTest.java
Some cleanup of the autoscaler logging to reduce info level noise + small test and improvements for the scaling spec replacement logic.
> [hotfix] Minor logging and scaling execution improvements for autoscaler

- examples/advanced-ingress.yaml
- examples/basic-checkpoint-ha.yaml
- examples/basic-ingress.yaml
- examples/basic-reactive.yaml
- examples/basic-session-deployment-and-job.yaml
- examples/basic-session-deployment-only.yaml
- examples/basic.yaml
- examples/custom-logging.yaml
- examples/flink-python-example/Dockerfile
- examples/flink-python-example/python-example.yaml
- examples/flink-sql-runner-example/Dockerfile
- examples/flink-sql-runner-example/sql-example.yaml
- examples/pod-template.yaml
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/CustomCheckpointingStatisticsHeaders.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/CustomDashboardConfigurationHeaders.java
- pom.xml
> [FLINK-29871] Upgraded flink dependencies to 1.16

- Dockerfile
- docker-entrypoint.sh
- docs/content/docs/operations/plugins.md
Allow users to add additional dependencies onto operator classpath
- Create a target folder with a dedicated environment variable for user dependencies in root dockerFile
- Dependencies (does it add or upgrade a dependency): (yes / no) no
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no)  no
- Core observer or reconciler logic that is regularly executed: (yes / no)  no
- Does this pull request introduce a new feature? (yes / no) yes
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) docs
> [FLINK-31140] - Load additional dependencies in operator classpath

- flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetrics.java
- flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/MetricsCollectionAndEvaluationTest.java
- flink-kubernetes-operator-autoscaler/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/metrics/ScalingMetricsTest.java
The logic for computing true processing rates rely on recordsProcessed /
recordProcessingTime style computations which do not really work well when
everything is 0. This leads to no scaling actions when the load suddenly drops
to 0.
The change here takes a pragmatic approach. Instead of special-casing zero
rates throughout the code, we set rates and busyness to near zero values. This
keeps the code functional as-is while ensuring scale down happens.
This concept corresponds to scaling Flink jobs via the parallelism which
naturally cannot be scaled to zero.
Based on #542 (first commit).
> [FLINK-30575] Ensure zero rates lead to scale down 

- flink-kubernetes-operator-autoscaler/src/main/java/org/apache/flink/kubernetes/operator/autoscaler/AutoScalerInfo.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/KubernetesClientUtils.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/StatusRecorder.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/KubernetesClientMetricsTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/KubernetesClientUtilsTest.java
- flink-kubernetes-standalone/src/main/java/org/apache/flink/kubernetes/operator/kubeclient/Fabric8FlinkStandaloneKubeClient.java
- helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml
- pom.xml
This new version brings critical stability fixes for the informers. I fixed the newly introduced deprecation warnings.
> [FLINK-31407] Bump fabric8 version to 6.5.0

- docs/content/docs/operations/upgrade.md
* The documentation has been properly adjusted to facilitate user upgrades.
* I modified the "docs/content/docs/operations/upgrade.md" file in the project.
*I checked the changes.*
Hi, @gyfora please take a look in your free time ,thanks!
> [FLINK-31577] Improve the upgrade documentation for k8s operator

- docs/content/docs/custom-resource/autoscaler.md
- examples/autoscaling/Dockerfile
- examples/autoscaling/autoscaling.yaml
Upgrade autoscaling example to 1.17.0 image and update related documentation and comments.
- Upgrade autoscaling example to 1.17.0 image.
- Add comments to avoid fs permission confusion.
> [FLINK-31614] Upgrade autoscaling example to 1.17.0 image

- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/FlinkDeploymentSpec.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/FlinkSessionJobSpec.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/IngressSpec.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/JobManagerSpec.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/JobSpec.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/Resource.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/spec/TaskManagerSpec.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/FlinkDeploymentReconciliationStatus.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/FlinkDeploymentStatus.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/FlinkSessionJobReconciliationStatus.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/FlinkSessionJobStatus.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/JobStatus.java
- flink-kubernetes-operator-api/src/main/java/org/apache/flink/kubernetes/operator/api/status/TaskManagerInfo.java
- flink-kubernetes-operator-api/src/test/java/org/apache/flink/kubernetes/operator/api/validation/CrdCompatibilityCheckerTest.java
- flink-kubernetes-operator-api/src/test/resources/test-deployment-with-unknown-fields.yaml
- flink-kubernetes-operator-api/src/test/resources/test-deployment.yaml
- flink-kubernetes-operator-api/src/test/resources/test-session-job-with-unknown-fields.yaml
- flink-kubernetes-operator-api/src/test/resources/test-session-job.yaml
Ignore unknown CRD fields to prevent failure in creating CR.
Added class-level annotation `@JsonIgnoreProperties(ignoreUnknown = true)`. for:
- FlinkSessionJobStatus 
- FlinkSessionJobSpec
- FlinkDeploymentStatus
- FlinkDeploymentSpec 
Added unit test to verify that: 
- Unknown CRD fields are ignored and doesn't result in error when creating CR.
- Known CRD fields are not ignored/removed.
> [FLINK-31794] Ignore unknown CRD fields

- docs/content/docs/custom-resource/autoscaler.md
… the new consolidated source scaling logic
Update autoscaler doc to reflect the changes brought by the new consolidated source scaling logic.
> [FLINK-31991] Update autoscaler doc to reflect the changes brought by the new consolidated source scaling logic

- README.md
- docs/content/docs/concepts/overview.md
- docs/content/docs/custom-resource/job-management.md
- docs/content/docs/custom-resource/overview.md
- docs/content/docs/custom-resource/pod-template.md
- docs/content/docs/development/roadmap.md
- docs/content/docs/operations/health.md
Doc updates for recently added features.
> [docs] Update documentation to cover some recent improvements

- helm/flink-kubernetes-operator/templates/rbac.yaml
Noticing in the 1.5.0-rc1 and 1.5.0-rc2 that we're having a problem deploying on OpenShift.  The solution is to either manually update the flink-kubernetes-operator.v1.5.0 clusterrole, but a better way is to update the rbac.yaml.  In either case, a `- flinkdeployments/finalizers` is needed in the flink.apache.org apiGroup.
The following PR adds this finalizer for the deployment to succeed.
- *the `- flinkdeployments/finalizers` resource is added to the  flink.apache.org apiGroup*
- Core observer or reconciler logic that is regularly executed: No
- Does this pull request introduce a …
> FLINK-32103 Update RBAC for OpenShift Deployment

- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- pom.xml
> [FLINK-32243] Bump okhttp version to 4.11.0

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/reconciler/diff/DiffBuilder.java
- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkService.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestUtils.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingClusterClient.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/TestingRestClient.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/reconciler/diff/SpecDiffTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/AbstractFlinkServiceTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/RestResponseTest.java
Based on coverage analysis we identified a few large holes in the test coverage. This PR aims to address many of the uncovered parts, mostly around the AbstractFlinkService. After this PR we have 85%+ coverage on the important parts :) 
- *Add AbstractFlinkServiceTest*
- *Move some unit test cases from NativeFlinkServiceTests to Abstract...*
- *Simplify DiffBuilder array comparison, add missing unit tests*
It basically verifies itself :)
> Test improvements

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/FlinkUtils.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/FlinkUtilsZookeeperHATest.java
Backport https://github.com/apache/flink-kubernetes-operator/pull/654 to release 1.6
> [FLINK-32890] Correct HA patch check for zookeeper metadata store

- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- pom.xml
Upgrade JOSDK to 4.4.4 which contains fix on leader election stop not called
- Update dependencies
> [FLINK-33125] Bump JOSDK to 4.4.4

- .github/workflows/ci.yml
- e2e-tests/test_dynamic_config.sh
- e2e-tests/utils.sh
Add e2e for dynamic config feature of Flink Operator
- add test_dynamic_config.sh
Run e2e in the GitHub CI.
> [FLINK-30519] add dynamic config e2e

- docs/content/docs/operations/upgrade.md
Fix a spelling error in upgrade documentation.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large …
> Fix a speling error in upgrade.md

- flink-autoscaler/src/main/java/org/apache/flink/autoscaler/JobAutoScalerImpl.java
- flink-autoscaler/src/main/java/org/apache/flink/autoscaler/metrics/ScalingHistoryUtils.java
- flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
Currently, we just clear ParallelismOverrides  after autoscaler is disabled.
We should clear CollectedMetrics and ScalingHistory  as well to prevent state leak.
- CollectedMetrics can be cleared directly.
- ScalingHistory can be cleared based on trim logic( VERTEX_SCALING_HISTORY_AGE)
[FLINK-33527][autoscaler] Clear all physical states after autoscaler is disabled
- *JobAutoScalerImplTest#testAutoscalerDisabled*
> [FLINK-33527][autoscaler] Clear all physical states after autoscaler is disabled

- .asf.yaml
- .github/workflows/docs.yaml
- Dockerfile
- docs/config.toml
- examples/autoscaling/pom.xml
- examples/flink-beam-example/pom.xml
- examples/flink-sql-runner-example/pom.xml
- examples/kubernetes-client-examples/pom.xml
- flink-autoscaler-standalone/pom.xml
- flink-autoscaler/pom.xml
- flink-kubernetes-docs/pom.xml
- flink-kubernetes-operator-api/pom.xml
- flink-kubernetes-operator/pom.xml
- flink-kubernetes-standalone/pom.xml
- flink-kubernetes-webhook/pom.xml
- helm/flink-kubernetes-operator/Chart.yaml
- pom.xml
> [release] Update version to 1.8-SNAPSHOT

- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/autoscaler/state/ConfigMapViewTest.java
Follow up to #710 which was meant to be committed before merge.
> [FLINK-33572] Add a unit test for ConfigMapView

- flink-autoscaler/src/test/java/org/apache/flink/autoscaler/ScalingTrackingTest.java
This is a trivial addition of tests for removal of old records in `ScalingTracking`
> [FLINK-30593] Add tests for ScalingTracking#removeOldRecords()

- docs/content/docs/operations/upgrade.md
Update the docs regarding Java client library upgrades. I'm curious to hear your opinion on this one.
> Add Java client library update process to the Upgrade page

- docs/content/docs/concepts/controller-flow.md
Fix a few things in the docs
Fix a few things in the docs
No verification - simple doc changes.
> [docs] Fix a few docs mistakes

- docs/content/docs/custom-resource/job-management.md
Typo: add missing word "start"
> [docs] Typo: add missing word "start"

- NOTICE
- flink-autoscaler-standalone/src/main/resources/META-INF/NOTICE
- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- flink-kubernetes-standalone/src/main/resources/META-INF/NOTICE
- flink-kubernetes-webhook/src/main/resources/META-INF/NOTICE
- tools/license/NOTICE-binary_PREAMBLE.txt
Add year 2024 to Notice files
Add year 2024 to Notice files
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing …
> [hotfix] Add year 2024 to Notice files

- docs/content/_index.md
Improve the feature description of flink-operator in the document
Add Flink Job Autoscaler in _index.md
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*
- …
> [hotfix] Add the feature description of flink-operator in the document

- flink-autoscaler/src/main/java/org/apache/flink/autoscaler/ScalingExecutor.java
- flink-autoscaler/src/main/java/org/apache/flink/autoscaler/utils/ResourceCheckUtils.java
- flink-autoscaler/src/test/java/org/apache/flink/autoscaler/utils/ResourceCheckUtilsTest.java
While working on #762, I realized this change can be extracted and merged independently.
> [FLINK-33771] Extract method to estimate task slots and add dedicated test

- docs/content/docs/operations/helm.md
Helm docs do not mention the chart repo, which will be useful for anyone who doesn't want to download the source code or is using argocd/terraform
- Docs update
This change is a trivial rework - docs update.
> Add helm chart repo to helm docs

- docs/content/docs/custom-resource/overview.md
add flink version details
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 …
> [hotfix] Improve FlinkDeployment spec overview doc

- .asf.yaml
- .github/workflows/docs.yaml
- Dockerfile
- docs/config.toml
- examples/autoscaling/pom.xml
- examples/flink-beam-example/pom.xml
- examples/flink-sql-runner-example/pom.xml
- examples/kubernetes-client-examples/pom.xml
- flink-autoscaler-plugin-jdbc/pom.xml
- flink-autoscaler-standalone/pom.xml
- flink-autoscaler/pom.xml
- flink-kubernetes-docs/pom.xml
- flink-kubernetes-operator-api/pom.xml
- flink-kubernetes-operator/pom.xml
- flink-kubernetes-standalone/pom.xml
- flink-kubernetes-webhook/pom.xml
- helm/flink-kubernetes-operator/Chart.yaml
- pom.xml
This bumps the snapshot version for the 1.8 release.
> [release] Update version to 1.9-SNAPSHOT

- docs/content/docs/custom-resource/autoscaler.md
- docs/content/docs/custom-resource/autotuning.md
This adds documentation for Flink Autotuning.
> [FLINK-34538][docs] Add Autotuning documentation

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/service/NativeFlinkService.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/service/NativeFlinkServiceTest.java
We introduced a logic to scale down the JobManager before the task managers are killed to have a more graceful shutdown sequence.
Currently this is always done in native mode, but it makes more sense to restrict this functionality to foreground deletion. Foreground deletion is the default and recommended propagation but in some cases users may want to use background deletion to speed up the process. In these cases we should not force a synchronous, potentially slow step.
Furthermore instead of using the entire deletion timeout we should reduce this to only use a portion of it as it's an optional step and we should always have keep enough time for the TM shutdown.
- *Only shut down JMs first in Foreground deletion*
- *Use only half the total shutdown timeout for JM shutdown but not more …
> [FLINK-34947] Only scale down JM in Foreground deletion propagation and reduce timeout

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/utils/EventUtils.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/utils/EventUtilsTest.java
This patch is to tackle the corner case where `cleanup` of CustomResource is constantly failing due to event publish failure, and therefore cause the `cleanup` hanging forever.
Operator attempts to publish events when reconcile changes or cleaning up for a CustomResource. This patch allows the reconcile & clean up logic to proceed, if and only if the event publishing fails as a result of 403 forbidden, which happens when the namespace is being deleted (in terminating state). k8s rejects events / resource creation in a terminating namespace.
In this way, at-least-once events delivery is still guaranteed in other cases. Event consumers need to account for the "namespace deleted" scenario, which all resources within are implicitly deleted.
- Fix event publish blocking reconcile & cleanup …
> [FLINK-31860] FlinkDeployments never finalize when namespace is deleted

- docs/content.zh/docs/concepts/architecture.md
https://issues.apache.org/jira/browse/FLINK-34970
Translate architecture documents into Chinese
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-34970] Translate architecture documents into Chinese

- docs/content.zh/docs/concepts/overview.md
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …
> [FLINK-34980] Translate overview document into Chinese

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetrics.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/operator/metrics/FlinkDeploymentMetricsTest.java
* Adds new convenience metric for tracking minor version of running applications per namespace
* Changes current Flink version metric to report version as a dimension (both metrics are now dimensions)
* Updated existing test to cover this too
> [FLINK-35183] MinorVersion metric for tracking applications

- docs/content/docs/operations/rbac.md
- *`kubectl -f example/basic.yaml ` ->  `kubectl apply -f example/basic.yaml `*
- Dependencies (does it add or upgrade a dependency): (yes / no) no
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: (yes / no) no
- Core observer or reconciler logic that is regularly executed: (yes / no) no
- Does this pull request introduce a new feature? (yes / no) no
> [hotfix][javadocs] update rbac.md

- docs/content.zh/docs/custom-resource/pod-template.md
- docs/content/docs/custom-resource/pod-template.md
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …
> [FLINK-35448] Translate pod templates documentation into Chinese

- docs/content/docs/custom-resource/reference.md
- docs/template/crd-ref.template
Add missing documentation for `FlinkSessionJob` CRD.
Add docs for `FlinkSessionJob` CRD.
This change is a trivial rework / code cleanup without any test coverage, other than verifying locally.
> [hotfix] [docs] reference.md: Add missing FlinkSessionJob CRD

- .github/workflows/ci.yml
Add missing 1.19 from e2e matrix
> [ci] Add Flink 1.19 version to e2e test matrix

- flink-autoscaler-standalone/src/main/java/org/apache/flink/autoscaler/standalone/realizer/RescaleApiScalingRealizer.java
- flink-autoscaler-standalone/src/test/java/org/apache/flink/autoscaler/standalone/realizer/RescaleApiScalingRealizerTest.java
- flink-autoscaler/src/main/java/org/apache/flink/autoscaler/realizer/ScalingRealizer.java
- flink-autoscaler/src/test/java/org/apache/flink/autoscaler/JobAutoScalerImplTest.java
Throw exceptions that occur during the execution of RescaleApiScalingRealizer so that eventHandler can handle it
- Throws exceptions that occur with `RescaleApiScalingRealizer#realizeParallelismOverrides`
- A test method `testRealizeParallelismOverridesExceptions` has been added to JobAutoScalerImplTest, which will simulate an exception occurring in realizeParallelismOverrides and detect whether the EventHandler handles the exception.
> [FLINK-35896][autoscaler] Handle exception events in RescaleApiScalingRealizer

- helm/flink-kubernetes-operator/templates/webhook.yaml
allow CREATE/UPDATE operation on flinkdeployments resource on webhook mutation endpoint
- update webhook.yaml in helm chart to add CREATE/UPDATE operation on flinkdeployments resource
This change is verified by locally deploy the helm chart and verified the mutation endpoint is able to modify the flinkdep CRD.
- Core observer or reconciler logic that is regularly executed: No
- Does this pull request introduce a new feature? No
> [FLINK-36685][Kubernetes Operator]  allow CREATE/UPDATE operation on flinkdeployments resource on webhook mutation endpoint

- pom.xml
Update dependency on org.quartz-scheduler:quartz used in flink-autoscaler module from 2.3.2 to 2.4.0
- Change version in pom from 2.3.2 to 2.4.0
Please refer to https://nvd.nist.gov/vuln/detail/cve-2023-39017 for more details about the vulnerability
- Dependencies (does it add or upgrade a dependency): (yes)
> [FLINK-36920][Kubernetes Operator] Bump quartz-scheduler from 2.3.2 to 2.4.0

- flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecorator.java
- flink-kubernetes-operator/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecoratorTest.java
Flink 2.x deployments are not compatible with some deprecated non-yaml-compliant keys.
We should do upfront config validation to avoid cryptic yaml conversion errors.
Unit tests, existing e2es
> [FLINK-37405] Validate config prefixes for Flink 2.0

- flink-autoscaler-standalone/src/main/resources/META-INF/NOTICE
- flink-kubernetes-operator/src/main/resources/META-INF/NOTICE
- pom.xml
* Update common-lang3 dependency
- Update common-lang3 dependency version
- Dependencies (does it add or upgrade a dependency): (yes)
> [FLINK-38159] Update commons-lang3 dependency to 3.18.0
